import IRequest from '../../core/interface/IRequest';
import * as Gs2Matchmaking from '../model';
export default class CreateNamespaceRequest implements IRequest {
    private requestId;
    private contextStack;
    private name;
    private description;
    private enableRating;
    private createGatheringTriggerType;
    private createGatheringTriggerRealtimeNamespaceId;
    private createGatheringTriggerScriptId;
    private completeMatchmakingTriggerType;
    private completeMatchmakingTriggerRealtimeNamespaceId;
    private completeMatchmakingTriggerScriptId;
    private changeRatingScript;
    private joinNotification;
    private leaveNotification;
    private completeNotification;
    private changeRatingNotification;
    private logSetting;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getEnableRating(): boolean | null;
    setEnableRating(enableRating: boolean | null): this;
    withEnableRating(enableRating: boolean | null): this;
    getCreateGatheringTriggerType(): string | null;
    setCreateGatheringTriggerType(createGatheringTriggerType: string | null): this;
    withCreateGatheringTriggerType(createGatheringTriggerType: string | null): this;
    getCreateGatheringTriggerRealtimeNamespaceId(): string | null;
    setCreateGatheringTriggerRealtimeNamespaceId(createGatheringTriggerRealtimeNamespaceId: string | null): this;
    withCreateGatheringTriggerRealtimeNamespaceId(createGatheringTriggerRealtimeNamespaceId: string | null): this;
    getCreateGatheringTriggerScriptId(): string | null;
    setCreateGatheringTriggerScriptId(createGatheringTriggerScriptId: string | null): this;
    withCreateGatheringTriggerScriptId(createGatheringTriggerScriptId: string | null): this;
    getCompleteMatchmakingTriggerType(): string | null;
    setCompleteMatchmakingTriggerType(completeMatchmakingTriggerType: string | null): this;
    withCompleteMatchmakingTriggerType(completeMatchmakingTriggerType: string | null): this;
    getCompleteMatchmakingTriggerRealtimeNamespaceId(): string | null;
    setCompleteMatchmakingTriggerRealtimeNamespaceId(completeMatchmakingTriggerRealtimeNamespaceId: string | null): this;
    withCompleteMatchmakingTriggerRealtimeNamespaceId(completeMatchmakingTriggerRealtimeNamespaceId: string | null): this;
    getCompleteMatchmakingTriggerScriptId(): string | null;
    setCompleteMatchmakingTriggerScriptId(completeMatchmakingTriggerScriptId: string | null): this;
    withCompleteMatchmakingTriggerScriptId(completeMatchmakingTriggerScriptId: string | null): this;
    getChangeRatingScript(): Gs2Matchmaking.ScriptSetting | null;
    setChangeRatingScript(changeRatingScript: Gs2Matchmaking.ScriptSetting | null): this;
    withChangeRatingScript(changeRatingScript: Gs2Matchmaking.ScriptSetting | null): this;
    getJoinNotification(): Gs2Matchmaking.NotificationSetting | null;
    setJoinNotification(joinNotification: Gs2Matchmaking.NotificationSetting | null): this;
    withJoinNotification(joinNotification: Gs2Matchmaking.NotificationSetting | null): this;
    getLeaveNotification(): Gs2Matchmaking.NotificationSetting | null;
    setLeaveNotification(leaveNotification: Gs2Matchmaking.NotificationSetting | null): this;
    withLeaveNotification(leaveNotification: Gs2Matchmaking.NotificationSetting | null): this;
    getCompleteNotification(): Gs2Matchmaking.NotificationSetting | null;
    setCompleteNotification(completeNotification: Gs2Matchmaking.NotificationSetting | null): this;
    withCompleteNotification(completeNotification: Gs2Matchmaking.NotificationSetting | null): this;
    getChangeRatingNotification(): Gs2Matchmaking.NotificationSetting | null;
    setChangeRatingNotification(changeRatingNotification: Gs2Matchmaking.NotificationSetting | null): this;
    withChangeRatingNotification(changeRatingNotification: Gs2Matchmaking.NotificationSetting | null): this;
    getLogSetting(): Gs2Matchmaking.LogSetting | null;
    setLogSetting(logSetting: Gs2Matchmaking.LogSetting | null): this;
    withLogSetting(logSetting: Gs2Matchmaking.LogSetting | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): CreateNamespaceRequest;
    toDict(): {
        [key: string]: any;
    };
}
