import IRequest from '../../core/interface/IRequest';
import * as Gs2Formation from '../model';
export default class AcquireActionsToFormPropertiesRequest implements IRequest {
    private requestId;
    private contextStack;
    private namespaceName;
    private userId;
    private moldName;
    private index;
    private acquireAction;
    private queueNamespaceId;
    private keyId;
    private config;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getUserId(): string | null;
    setUserId(userId: string | null): this;
    withUserId(userId: string | null): this;
    getMoldName(): string | null;
    setMoldName(moldName: string | null): this;
    withMoldName(moldName: string | null): this;
    getIndex(): number | null;
    setIndex(index: number | null): this;
    withIndex(index: number | null): this;
    getAcquireAction(): Gs2Formation.AcquireAction | null;
    setAcquireAction(acquireAction: Gs2Formation.AcquireAction | null): this;
    withAcquireAction(acquireAction: Gs2Formation.AcquireAction | null): this;
    getQueueNamespaceId(): string | null;
    setQueueNamespaceId(queueNamespaceId: string | null): this;
    withQueueNamespaceId(queueNamespaceId: string | null): this;
    getKeyId(): string | null;
    setKeyId(keyId: string | null): this;
    withKeyId(keyId: string | null): this;
    getConfig(): Gs2Formation.AcquireActionConfig[] | null;
    setConfig(config: Gs2Formation.AcquireActionConfig[] | null): this;
    withConfig(config: Gs2Formation.AcquireActionConfig[] | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): AcquireActionsToFormPropertiesRequest;
    toDict(): {
        [key: string]: any;
    };
}
