"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SetCapacityByStampSheetRequest = exports.SubCapacityByStampTaskRequest = exports.AddCapacityByStampSheetRequest = exports.DeleteMoldByUserIdRequest = exports.DeleteMoldRequest = exports.SubMoldCapacityByUserIdRequest = exports.SubMoldCapacityRequest = exports.AddMoldCapacityByUserIdRequest = exports.SetMoldCapacityByUserIdRequest = exports.GetMoldByUserIdRequest = exports.GetMoldRequest = exports.DescribeMoldsByUserIdRequest = exports.DescribeMoldsRequest = exports.UpdateCurrentFormMasterFromGitHubRequest = exports.UpdateCurrentFormMasterRequest = exports.GetCurrentFormMasterRequest = exports.ExportMasterRequest = exports.DeletePropertyFormModelMasterRequest = exports.UpdatePropertyFormModelMasterRequest = exports.GetPropertyFormModelMasterRequest = exports.CreatePropertyFormModelMasterRequest = exports.DescribePropertyFormModelMastersRequest = exports.GetPropertyFormModelRequest = exports.DescribePropertyFormModelsRequest = exports.DeleteMoldModelMasterRequest = exports.UpdateMoldModelMasterRequest = exports.GetMoldModelMasterRequest = exports.CreateMoldModelMasterRequest = exports.DescribeMoldModelMastersRequest = exports.GetMoldModelRequest = exports.DescribeMoldModelsRequest = exports.DeleteFormModelMasterRequest = exports.UpdateFormModelMasterRequest = exports.GetFormModelMasterRequest = exports.CreateFormModelMasterRequest = exports.DescribeFormModelMastersRequest = exports.GetFormModelRequest = exports.CheckImportUserDataByUserIdRequest = exports.ImportUserDataByUserIdRequest = exports.PrepareImportUserDataByUserIdRequest = exports.CheckCleanUserDataByUserIdRequest = exports.CleanUserDataByUserIdRequest = exports.CheckDumpUserDataByUserIdRequest = exports.DumpUserDataByUserIdRequest = exports.DeleteNamespaceRequest = exports.UpdateNamespaceRequest = exports.GetNamespaceRequest = exports.GetNamespaceStatusRequest = exports.CreateNamespaceRequest = exports.DescribeNamespacesRequest = void 0;
exports.AcquireActionToPropertyFormPropertiesByStampSheetRequest = exports.DeletePropertyFormByUserIdRequest = exports.DeletePropertyFormRequest = exports.AcquireActionsToPropertyFormPropertiesRequest = exports.SetPropertyFormWithSignatureRequest = exports.SetPropertyFormByUserIdRequest = exports.GetPropertyFormWithSignatureByUserIdRequest = exports.GetPropertyFormWithSignatureRequest = exports.GetPropertyFormByUserIdRequest = exports.GetPropertyFormRequest = exports.DescribePropertyFormsByUserIdRequest = exports.DescribePropertyFormsRequest = exports.SetFormByStampSheetRequest = exports.AcquireActionToFormPropertiesByStampSheetRequest = exports.DeleteFormByUserIdRequest = exports.DeleteFormRequest = exports.AcquireActionsToFormPropertiesRequest = exports.SetFormWithSignatureRequest = exports.SetFormByUserIdRequest = exports.SetFormRequest = exports.GetFormWithSignatureByUserIdRequest = exports.GetFormWithSignatureRequest = exports.GetFormByUserIdRequest = exports.GetFormRequest = exports.DescribeFormsByUserIdRequest = exports.DescribeFormsRequest = void 0;
var tslib_1 = require("tslib");
/*
Copyright 2016 Game Server Services, Inc. or its affiliates. All Rights
Reserved.

Licensed under the Apache License, Version 2.0 (the "License").
You may not use this file except in compliance with the License.
A copy of the License is located at

 http://www.apache.org/licenses/LICENSE-2.0

or in the "license" file accompanying this file. This file is distributed
on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied. See the License for the specific language governing
permissions and limitations under the License.
 */
var DescribeNamespacesRequest_1 = tslib_1.__importDefault(require("./DescribeNamespacesRequest"));
exports.DescribeNamespacesRequest = DescribeNamespacesRequest_1.default;
var CreateNamespaceRequest_1 = tslib_1.__importDefault(require("./CreateNamespaceRequest"));
exports.CreateNamespaceRequest = CreateNamespaceRequest_1.default;
var GetNamespaceStatusRequest_1 = tslib_1.__importDefault(require("./GetNamespaceStatusRequest"));
exports.GetNamespaceStatusRequest = GetNamespaceStatusRequest_1.default;
var GetNamespaceRequest_1 = tslib_1.__importDefault(require("./GetNamespaceRequest"));
exports.GetNamespaceRequest = GetNamespaceRequest_1.default;
var UpdateNamespaceRequest_1 = tslib_1.__importDefault(require("./UpdateNamespaceRequest"));
exports.UpdateNamespaceRequest = UpdateNamespaceRequest_1.default;
var DeleteNamespaceRequest_1 = tslib_1.__importDefault(require("./DeleteNamespaceRequest"));
exports.DeleteNamespaceRequest = DeleteNamespaceRequest_1.default;
var DumpUserDataByUserIdRequest_1 = tslib_1.__importDefault(require("./DumpUserDataByUserIdRequest"));
exports.DumpUserDataByUserIdRequest = DumpUserDataByUserIdRequest_1.default;
var CheckDumpUserDataByUserIdRequest_1 = tslib_1.__importDefault(require("./CheckDumpUserDataByUserIdRequest"));
exports.CheckDumpUserDataByUserIdRequest = CheckDumpUserDataByUserIdRequest_1.default;
var CleanUserDataByUserIdRequest_1 = tslib_1.__importDefault(require("./CleanUserDataByUserIdRequest"));
exports.CleanUserDataByUserIdRequest = CleanUserDataByUserIdRequest_1.default;
var CheckCleanUserDataByUserIdRequest_1 = tslib_1.__importDefault(require("./CheckCleanUserDataByUserIdRequest"));
exports.CheckCleanUserDataByUserIdRequest = CheckCleanUserDataByUserIdRequest_1.default;
var PrepareImportUserDataByUserIdRequest_1 = tslib_1.__importDefault(require("./PrepareImportUserDataByUserIdRequest"));
exports.PrepareImportUserDataByUserIdRequest = PrepareImportUserDataByUserIdRequest_1.default;
var ImportUserDataByUserIdRequest_1 = tslib_1.__importDefault(require("./ImportUserDataByUserIdRequest"));
exports.ImportUserDataByUserIdRequest = ImportUserDataByUserIdRequest_1.default;
var CheckImportUserDataByUserIdRequest_1 = tslib_1.__importDefault(require("./CheckImportUserDataByUserIdRequest"));
exports.CheckImportUserDataByUserIdRequest = CheckImportUserDataByUserIdRequest_1.default;
var GetFormModelRequest_1 = tslib_1.__importDefault(require("./GetFormModelRequest"));
exports.GetFormModelRequest = GetFormModelRequest_1.default;
var DescribeFormModelMastersRequest_1 = tslib_1.__importDefault(require("./DescribeFormModelMastersRequest"));
exports.DescribeFormModelMastersRequest = DescribeFormModelMastersRequest_1.default;
var CreateFormModelMasterRequest_1 = tslib_1.__importDefault(require("./CreateFormModelMasterRequest"));
exports.CreateFormModelMasterRequest = CreateFormModelMasterRequest_1.default;
var GetFormModelMasterRequest_1 = tslib_1.__importDefault(require("./GetFormModelMasterRequest"));
exports.GetFormModelMasterRequest = GetFormModelMasterRequest_1.default;
var UpdateFormModelMasterRequest_1 = tslib_1.__importDefault(require("./UpdateFormModelMasterRequest"));
exports.UpdateFormModelMasterRequest = UpdateFormModelMasterRequest_1.default;
var DeleteFormModelMasterRequest_1 = tslib_1.__importDefault(require("./DeleteFormModelMasterRequest"));
exports.DeleteFormModelMasterRequest = DeleteFormModelMasterRequest_1.default;
var DescribeMoldModelsRequest_1 = tslib_1.__importDefault(require("./DescribeMoldModelsRequest"));
exports.DescribeMoldModelsRequest = DescribeMoldModelsRequest_1.default;
var GetMoldModelRequest_1 = tslib_1.__importDefault(require("./GetMoldModelRequest"));
exports.GetMoldModelRequest = GetMoldModelRequest_1.default;
var DescribeMoldModelMastersRequest_1 = tslib_1.__importDefault(require("./DescribeMoldModelMastersRequest"));
exports.DescribeMoldModelMastersRequest = DescribeMoldModelMastersRequest_1.default;
var CreateMoldModelMasterRequest_1 = tslib_1.__importDefault(require("./CreateMoldModelMasterRequest"));
exports.CreateMoldModelMasterRequest = CreateMoldModelMasterRequest_1.default;
var GetMoldModelMasterRequest_1 = tslib_1.__importDefault(require("./GetMoldModelMasterRequest"));
exports.GetMoldModelMasterRequest = GetMoldModelMasterRequest_1.default;
var UpdateMoldModelMasterRequest_1 = tslib_1.__importDefault(require("./UpdateMoldModelMasterRequest"));
exports.UpdateMoldModelMasterRequest = UpdateMoldModelMasterRequest_1.default;
var DeleteMoldModelMasterRequest_1 = tslib_1.__importDefault(require("./DeleteMoldModelMasterRequest"));
exports.DeleteMoldModelMasterRequest = DeleteMoldModelMasterRequest_1.default;
var DescribePropertyFormModelsRequest_1 = tslib_1.__importDefault(require("./DescribePropertyFormModelsRequest"));
exports.DescribePropertyFormModelsRequest = DescribePropertyFormModelsRequest_1.default;
var GetPropertyFormModelRequest_1 = tslib_1.__importDefault(require("./GetPropertyFormModelRequest"));
exports.GetPropertyFormModelRequest = GetPropertyFormModelRequest_1.default;
var DescribePropertyFormModelMastersRequest_1 = tslib_1.__importDefault(require("./DescribePropertyFormModelMastersRequest"));
exports.DescribePropertyFormModelMastersRequest = DescribePropertyFormModelMastersRequest_1.default;
var CreatePropertyFormModelMasterRequest_1 = tslib_1.__importDefault(require("./CreatePropertyFormModelMasterRequest"));
exports.CreatePropertyFormModelMasterRequest = CreatePropertyFormModelMasterRequest_1.default;
var GetPropertyFormModelMasterRequest_1 = tslib_1.__importDefault(require("./GetPropertyFormModelMasterRequest"));
exports.GetPropertyFormModelMasterRequest = GetPropertyFormModelMasterRequest_1.default;
var UpdatePropertyFormModelMasterRequest_1 = tslib_1.__importDefault(require("./UpdatePropertyFormModelMasterRequest"));
exports.UpdatePropertyFormModelMasterRequest = UpdatePropertyFormModelMasterRequest_1.default;
var DeletePropertyFormModelMasterRequest_1 = tslib_1.__importDefault(require("./DeletePropertyFormModelMasterRequest"));
exports.DeletePropertyFormModelMasterRequest = DeletePropertyFormModelMasterRequest_1.default;
var ExportMasterRequest_1 = tslib_1.__importDefault(require("./ExportMasterRequest"));
exports.ExportMasterRequest = ExportMasterRequest_1.default;
var GetCurrentFormMasterRequest_1 = tslib_1.__importDefault(require("./GetCurrentFormMasterRequest"));
exports.GetCurrentFormMasterRequest = GetCurrentFormMasterRequest_1.default;
var UpdateCurrentFormMasterRequest_1 = tslib_1.__importDefault(require("./UpdateCurrentFormMasterRequest"));
exports.UpdateCurrentFormMasterRequest = UpdateCurrentFormMasterRequest_1.default;
var UpdateCurrentFormMasterFromGitHubRequest_1 = tslib_1.__importDefault(require("./UpdateCurrentFormMasterFromGitHubRequest"));
exports.UpdateCurrentFormMasterFromGitHubRequest = UpdateCurrentFormMasterFromGitHubRequest_1.default;
var DescribeMoldsRequest_1 = tslib_1.__importDefault(require("./DescribeMoldsRequest"));
exports.DescribeMoldsRequest = DescribeMoldsRequest_1.default;
var DescribeMoldsByUserIdRequest_1 = tslib_1.__importDefault(require("./DescribeMoldsByUserIdRequest"));
exports.DescribeMoldsByUserIdRequest = DescribeMoldsByUserIdRequest_1.default;
var GetMoldRequest_1 = tslib_1.__importDefault(require("./GetMoldRequest"));
exports.GetMoldRequest = GetMoldRequest_1.default;
var GetMoldByUserIdRequest_1 = tslib_1.__importDefault(require("./GetMoldByUserIdRequest"));
exports.GetMoldByUserIdRequest = GetMoldByUserIdRequest_1.default;
var SetMoldCapacityByUserIdRequest_1 = tslib_1.__importDefault(require("./SetMoldCapacityByUserIdRequest"));
exports.SetMoldCapacityByUserIdRequest = SetMoldCapacityByUserIdRequest_1.default;
var AddMoldCapacityByUserIdRequest_1 = tslib_1.__importDefault(require("./AddMoldCapacityByUserIdRequest"));
exports.AddMoldCapacityByUserIdRequest = AddMoldCapacityByUserIdRequest_1.default;
var SubMoldCapacityRequest_1 = tslib_1.__importDefault(require("./SubMoldCapacityRequest"));
exports.SubMoldCapacityRequest = SubMoldCapacityRequest_1.default;
var SubMoldCapacityByUserIdRequest_1 = tslib_1.__importDefault(require("./SubMoldCapacityByUserIdRequest"));
exports.SubMoldCapacityByUserIdRequest = SubMoldCapacityByUserIdRequest_1.default;
var DeleteMoldRequest_1 = tslib_1.__importDefault(require("./DeleteMoldRequest"));
exports.DeleteMoldRequest = DeleteMoldRequest_1.default;
var DeleteMoldByUserIdRequest_1 = tslib_1.__importDefault(require("./DeleteMoldByUserIdRequest"));
exports.DeleteMoldByUserIdRequest = DeleteMoldByUserIdRequest_1.default;
var AddCapacityByStampSheetRequest_1 = tslib_1.__importDefault(require("./AddCapacityByStampSheetRequest"));
exports.AddCapacityByStampSheetRequest = AddCapacityByStampSheetRequest_1.default;
var SubCapacityByStampTaskRequest_1 = tslib_1.__importDefault(require("./SubCapacityByStampTaskRequest"));
exports.SubCapacityByStampTaskRequest = SubCapacityByStampTaskRequest_1.default;
var SetCapacityByStampSheetRequest_1 = tslib_1.__importDefault(require("./SetCapacityByStampSheetRequest"));
exports.SetCapacityByStampSheetRequest = SetCapacityByStampSheetRequest_1.default;
var DescribeFormsRequest_1 = tslib_1.__importDefault(require("./DescribeFormsRequest"));
exports.DescribeFormsRequest = DescribeFormsRequest_1.default;
var DescribeFormsByUserIdRequest_1 = tslib_1.__importDefault(require("./DescribeFormsByUserIdRequest"));
exports.DescribeFormsByUserIdRequest = DescribeFormsByUserIdRequest_1.default;
var GetFormRequest_1 = tslib_1.__importDefault(require("./GetFormRequest"));
exports.GetFormRequest = GetFormRequest_1.default;
var GetFormByUserIdRequest_1 = tslib_1.__importDefault(require("./GetFormByUserIdRequest"));
exports.GetFormByUserIdRequest = GetFormByUserIdRequest_1.default;
var GetFormWithSignatureRequest_1 = tslib_1.__importDefault(require("./GetFormWithSignatureRequest"));
exports.GetFormWithSignatureRequest = GetFormWithSignatureRequest_1.default;
var GetFormWithSignatureByUserIdRequest_1 = tslib_1.__importDefault(require("./GetFormWithSignatureByUserIdRequest"));
exports.GetFormWithSignatureByUserIdRequest = GetFormWithSignatureByUserIdRequest_1.default;
var SetFormRequest_1 = tslib_1.__importDefault(require("./SetFormRequest"));
exports.SetFormRequest = SetFormRequest_1.default;
var SetFormByUserIdRequest_1 = tslib_1.__importDefault(require("./SetFormByUserIdRequest"));
exports.SetFormByUserIdRequest = SetFormByUserIdRequest_1.default;
var SetFormWithSignatureRequest_1 = tslib_1.__importDefault(require("./SetFormWithSignatureRequest"));
exports.SetFormWithSignatureRequest = SetFormWithSignatureRequest_1.default;
var AcquireActionsToFormPropertiesRequest_1 = tslib_1.__importDefault(require("./AcquireActionsToFormPropertiesRequest"));
exports.AcquireActionsToFormPropertiesRequest = AcquireActionsToFormPropertiesRequest_1.default;
var DeleteFormRequest_1 = tslib_1.__importDefault(require("./DeleteFormRequest"));
exports.DeleteFormRequest = DeleteFormRequest_1.default;
var DeleteFormByUserIdRequest_1 = tslib_1.__importDefault(require("./DeleteFormByUserIdRequest"));
exports.DeleteFormByUserIdRequest = DeleteFormByUserIdRequest_1.default;
var AcquireActionToFormPropertiesByStampSheetRequest_1 = tslib_1.__importDefault(require("./AcquireActionToFormPropertiesByStampSheetRequest"));
exports.AcquireActionToFormPropertiesByStampSheetRequest = AcquireActionToFormPropertiesByStampSheetRequest_1.default;
var SetFormByStampSheetRequest_1 = tslib_1.__importDefault(require("./SetFormByStampSheetRequest"));
exports.SetFormByStampSheetRequest = SetFormByStampSheetRequest_1.default;
var DescribePropertyFormsRequest_1 = tslib_1.__importDefault(require("./DescribePropertyFormsRequest"));
exports.DescribePropertyFormsRequest = DescribePropertyFormsRequest_1.default;
var DescribePropertyFormsByUserIdRequest_1 = tslib_1.__importDefault(require("./DescribePropertyFormsByUserIdRequest"));
exports.DescribePropertyFormsByUserIdRequest = DescribePropertyFormsByUserIdRequest_1.default;
var GetPropertyFormRequest_1 = tslib_1.__importDefault(require("./GetPropertyFormRequest"));
exports.GetPropertyFormRequest = GetPropertyFormRequest_1.default;
var GetPropertyFormByUserIdRequest_1 = tslib_1.__importDefault(require("./GetPropertyFormByUserIdRequest"));
exports.GetPropertyFormByUserIdRequest = GetPropertyFormByUserIdRequest_1.default;
var GetPropertyFormWithSignatureRequest_1 = tslib_1.__importDefault(require("./GetPropertyFormWithSignatureRequest"));
exports.GetPropertyFormWithSignatureRequest = GetPropertyFormWithSignatureRequest_1.default;
var GetPropertyFormWithSignatureByUserIdRequest_1 = tslib_1.__importDefault(require("./GetPropertyFormWithSignatureByUserIdRequest"));
exports.GetPropertyFormWithSignatureByUserIdRequest = GetPropertyFormWithSignatureByUserIdRequest_1.default;
var SetPropertyFormByUserIdRequest_1 = tslib_1.__importDefault(require("./SetPropertyFormByUserIdRequest"));
exports.SetPropertyFormByUserIdRequest = SetPropertyFormByUserIdRequest_1.default;
var SetPropertyFormWithSignatureRequest_1 = tslib_1.__importDefault(require("./SetPropertyFormWithSignatureRequest"));
exports.SetPropertyFormWithSignatureRequest = SetPropertyFormWithSignatureRequest_1.default;
var AcquireActionsToPropertyFormPropertiesRequest_1 = tslib_1.__importDefault(require("./AcquireActionsToPropertyFormPropertiesRequest"));
exports.AcquireActionsToPropertyFormPropertiesRequest = AcquireActionsToPropertyFormPropertiesRequest_1.default;
var DeletePropertyFormRequest_1 = tslib_1.__importDefault(require("./DeletePropertyFormRequest"));
exports.DeletePropertyFormRequest = DeletePropertyFormRequest_1.default;
var DeletePropertyFormByUserIdRequest_1 = tslib_1.__importDefault(require("./DeletePropertyFormByUserIdRequest"));
exports.DeletePropertyFormByUserIdRequest = DeletePropertyFormByUserIdRequest_1.default;
var AcquireActionToPropertyFormPropertiesByStampSheetRequest_1 = tslib_1.__importDefault(require("./AcquireActionToPropertyFormPropertiesByStampSheetRequest"));
exports.AcquireActionToPropertyFormPropertiesByStampSheetRequest = AcquireActionToPropertyFormPropertiesByStampSheetRequest_1.default;
//# sourceMappingURL=index.js.map