/*
Copyright 2016 Game Server Services, Inc. or its affiliates. All Rights
Reserved.

Licensed under the Apache License, Version 2.0 (the "License").
You may not use this file except in compliance with the License.
A copy of the License is located at

 http://www.apache.org/licenses/LICENSE-2.0

or in the "license" file accompanying this file. This file is distributed
on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied. See the License for the specific language governing
permissions and limitations under the License.
 */

import {
  Namespace,
  ExperienceModelMaster,
  ExperienceModel,
  ThresholdMaster,
  Threshold,
  CurrentExperienceMaster,
  Status,
  ResponseCache,
  GitHubCheckoutSetting,
  ScriptSetting,
  LogSetting,
} from './model';
import {
  DescribeNamespacesRequest,
  CreateNamespaceRequest,
  GetNamespaceStatusRequest,
  GetNamespaceRequest,
  UpdateNamespaceRequest,
  DeleteNamespaceRequest,
  DescribeExperienceModelMastersRequest,
  CreateExperienceModelMasterRequest,
  GetExperienceModelMasterRequest,
  UpdateExperienceModelMasterRequest,
  DeleteExperienceModelMasterRequest,
  DescribeExperienceModelsRequest,
  GetExperienceModelRequest,
  DescribeThresholdMastersRequest,
  CreateThresholdMasterRequest,
  GetThresholdMasterRequest,
  UpdateThresholdMasterRequest,
  DeleteThresholdMasterRequest,
  ExportMasterRequest,
  GetCurrentExperienceMasterRequest,
  UpdateCurrentExperienceMasterRequest,
  UpdateCurrentExperienceMasterFromGitHubRequest,
  DescribeStatusesRequest,
  DescribeStatusesByUserIdRequest,
  GetStatusRequest,
  GetStatusByUserIdRequest,
  GetStatusWithSignatureRequest,
  AddExperienceByUserIdRequest,
  SetExperienceByUserIdRequest,
  AddRankCapByUserIdRequest,
  SetRankCapByUserIdRequest,
  DeleteStatusByUserIdRequest,
  AddExperienceByStampSheetRequest,
  AddRankCapByStampSheetRequest,
  SetRankCapByStampSheetRequest,
} from './request';
import {
  DescribeNamespacesResult,
  CreateNamespaceResult,
  GetNamespaceStatusResult,
  GetNamespaceResult,
  UpdateNamespaceResult,
  DeleteNamespaceResult,
  DescribeExperienceModelMastersResult,
  CreateExperienceModelMasterResult,
  GetExperienceModelMasterResult,
  UpdateExperienceModelMasterResult,
  DeleteExperienceModelMasterResult,
  DescribeExperienceModelsResult,
  GetExperienceModelResult,
  DescribeThresholdMastersResult,
  CreateThresholdMasterResult,
  GetThresholdMasterResult,
  UpdateThresholdMasterResult,
  DeleteThresholdMasterResult,
  ExportMasterResult,
  GetCurrentExperienceMasterResult,
  UpdateCurrentExperienceMasterResult,
  UpdateCurrentExperienceMasterFromGitHubResult,
  DescribeStatusesResult,
  DescribeStatusesByUserIdResult,
  GetStatusResult,
  GetStatusByUserIdResult,
  GetStatusWithSignatureResult,
  AddExperienceByUserIdResult,
  SetExperienceByUserIdResult,
  AddRankCapByUserIdResult,
  SetRankCapByUserIdResult,
  DeleteStatusByUserIdResult,
  AddExperienceByStampSheetResult,
  AddRankCapByStampSheetResult,
  SetRankCapByStampSheetResult,
} from './result';
import { Gs2ExperienceRestClient } from './rest';

export default {
  Namespace,
  ExperienceModelMaster,
  ExperienceModel,
  ThresholdMaster,
  Threshold,
  CurrentExperienceMaster,
  Status,
  ResponseCache,
  GitHubCheckoutSetting,
  ScriptSetting,
  LogSetting,
  DescribeNamespacesRequest,
  DescribeNamespacesResult,
  CreateNamespaceRequest,
  CreateNamespaceResult,
  GetNamespaceStatusRequest,
  GetNamespaceStatusResult,
  GetNamespaceRequest,
  GetNamespaceResult,
  UpdateNamespaceRequest,
  UpdateNamespaceResult,
  DeleteNamespaceRequest,
  DeleteNamespaceResult,
  DescribeExperienceModelMastersRequest,
  DescribeExperienceModelMastersResult,
  CreateExperienceModelMasterRequest,
  CreateExperienceModelMasterResult,
  GetExperienceModelMasterRequest,
  GetExperienceModelMasterResult,
  UpdateExperienceModelMasterRequest,
  UpdateExperienceModelMasterResult,
  DeleteExperienceModelMasterRequest,
  DeleteExperienceModelMasterResult,
  DescribeExperienceModelsRequest,
  DescribeExperienceModelsResult,
  GetExperienceModelRequest,
  GetExperienceModelResult,
  DescribeThresholdMastersRequest,
  DescribeThresholdMastersResult,
  CreateThresholdMasterRequest,
  CreateThresholdMasterResult,
  GetThresholdMasterRequest,
  GetThresholdMasterResult,
  UpdateThresholdMasterRequest,
  UpdateThresholdMasterResult,
  DeleteThresholdMasterRequest,
  DeleteThresholdMasterResult,
  ExportMasterRequest,
  ExportMasterResult,
  GetCurrentExperienceMasterRequest,
  GetCurrentExperienceMasterResult,
  UpdateCurrentExperienceMasterRequest,
  UpdateCurrentExperienceMasterResult,
  UpdateCurrentExperienceMasterFromGitHubRequest,
  UpdateCurrentExperienceMasterFromGitHubResult,
  DescribeStatusesRequest,
  DescribeStatusesResult,
  DescribeStatusesByUserIdRequest,
  DescribeStatusesByUserIdResult,
  GetStatusRequest,
  GetStatusResult,
  GetStatusByUserIdRequest,
  GetStatusByUserIdResult,
  GetStatusWithSignatureRequest,
  GetStatusWithSignatureResult,
  AddExperienceByUserIdRequest,
  AddExperienceByUserIdResult,
  SetExperienceByUserIdRequest,
  SetExperienceByUserIdResult,
  AddRankCapByUserIdRequest,
  AddRankCapByUserIdResult,
  SetRankCapByUserIdRequest,
  SetRankCapByUserIdResult,
  DeleteStatusByUserIdRequest,
  DeleteStatusByUserIdResult,
  AddExperienceByStampSheetRequest,
  AddExperienceByStampSheetResult,
  AddRankCapByStampSheetRequest,
  AddRankCapByStampSheetResult,
  SetRankCapByStampSheetRequest,
  SetRankCapByStampSheetResult,
  Gs2ExperienceRestClient,
};
