/*
Copyright 2016 Game Server Services, Inc. or its affiliates. All Rights
Reserved.

Licensed under the Apache License, Version 2.0 (the "License").
You may not use this file except in compliance with the License.
A copy of the License is located at

 http://www.apache.org/licenses/LICENSE-2.0

or in the "license" file accompanying this file. This file is distributed
on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied. See the License for the specific language governing
permissions and limitations under the License.
 */

import {
  Namespace,
  Message,
  CurrentMessageMaster,
  GlobalMessageMaster,
  GlobalMessage,
  Received,
  ResponseCache,
  Config,
  ScriptSetting,
  NotificationSetting,
  GitHubCheckoutSetting,
  LogSetting,
  TimeSpan,
  AcquireAction,
} from './model';
import {
  DescribeNamespacesRequest,
  CreateNamespaceRequest,
  GetNamespaceStatusRequest,
  GetNamespaceRequest,
  UpdateNamespaceRequest,
  DeleteNamespaceRequest,
  DescribeMessagesRequest,
  DescribeMessagesByUserIdRequest,
  SendMessageByUserIdRequest,
  GetMessageRequest,
  GetMessageByUserIdRequest,
  ReceiveGlobalMessageRequest,
  ReceiveGlobalMessageByUserIdRequest,
  OpenMessageRequest,
  OpenMessageByUserIdRequest,
  ReadMessageRequest,
  ReadMessageByUserIdRequest,
  DeleteMessageRequest,
  DeleteMessageByUserIdRequest,
  OpenByStampTaskRequest,
  ExportMasterRequest,
  GetCurrentMessageMasterRequest,
  UpdateCurrentMessageMasterRequest,
  UpdateCurrentMessageMasterFromGitHubRequest,
  DescribeGlobalMessageMastersRequest,
  CreateGlobalMessageMasterRequest,
  GetGlobalMessageMasterRequest,
  UpdateGlobalMessageMasterRequest,
  DeleteGlobalMessageMasterRequest,
  DescribeGlobalMessagesRequest,
  GetGlobalMessageRequest,
  GetReceivedByUserIdRequest,
  UpdateReceivedByUserIdRequest,
  DeleteReceivedByUserIdRequest,
} from './request';
import {
  DescribeNamespacesResult,
  CreateNamespaceResult,
  GetNamespaceStatusResult,
  GetNamespaceResult,
  UpdateNamespaceResult,
  DeleteNamespaceResult,
  DescribeMessagesResult,
  DescribeMessagesByUserIdResult,
  SendMessageByUserIdResult,
  GetMessageResult,
  GetMessageByUserIdResult,
  ReceiveGlobalMessageResult,
  ReceiveGlobalMessageByUserIdResult,
  OpenMessageResult,
  OpenMessageByUserIdResult,
  ReadMessageResult,
  ReadMessageByUserIdResult,
  DeleteMessageResult,
  DeleteMessageByUserIdResult,
  OpenByStampTaskResult,
  ExportMasterResult,
  GetCurrentMessageMasterResult,
  UpdateCurrentMessageMasterResult,
  UpdateCurrentMessageMasterFromGitHubResult,
  DescribeGlobalMessageMastersResult,
  CreateGlobalMessageMasterResult,
  GetGlobalMessageMasterResult,
  UpdateGlobalMessageMasterResult,
  DeleteGlobalMessageMasterResult,
  DescribeGlobalMessagesResult,
  GetGlobalMessageResult,
  GetReceivedByUserIdResult,
  UpdateReceivedByUserIdResult,
  DeleteReceivedByUserIdResult,
} from './result';
import { Gs2InboxRestClient } from './rest';

export default {
  Namespace,
  Message,
  CurrentMessageMaster,
  GlobalMessageMaster,
  GlobalMessage,
  Received,
  ResponseCache,
  Config,
  ScriptSetting,
  NotificationSetting,
  GitHubCheckoutSetting,
  LogSetting,
  TimeSpan,
  AcquireAction,
  DescribeNamespacesRequest,
  DescribeNamespacesResult,
  CreateNamespaceRequest,
  CreateNamespaceResult,
  GetNamespaceStatusRequest,
  GetNamespaceStatusResult,
  GetNamespaceRequest,
  GetNamespaceResult,
  UpdateNamespaceRequest,
  UpdateNamespaceResult,
  DeleteNamespaceRequest,
  DeleteNamespaceResult,
  DescribeMessagesRequest,
  DescribeMessagesResult,
  DescribeMessagesByUserIdRequest,
  DescribeMessagesByUserIdResult,
  SendMessageByUserIdRequest,
  SendMessageByUserIdResult,
  GetMessageRequest,
  GetMessageResult,
  GetMessageByUserIdRequest,
  GetMessageByUserIdResult,
  ReceiveGlobalMessageRequest,
  ReceiveGlobalMessageResult,
  ReceiveGlobalMessageByUserIdRequest,
  ReceiveGlobalMessageByUserIdResult,
  OpenMessageRequest,
  OpenMessageResult,
  OpenMessageByUserIdRequest,
  OpenMessageByUserIdResult,
  ReadMessageRequest,
  ReadMessageResult,
  ReadMessageByUserIdRequest,
  ReadMessageByUserIdResult,
  DeleteMessageRequest,
  DeleteMessageResult,
  DeleteMessageByUserIdRequest,
  DeleteMessageByUserIdResult,
  OpenByStampTaskRequest,
  OpenByStampTaskResult,
  ExportMasterRequest,
  ExportMasterResult,
  GetCurrentMessageMasterRequest,
  GetCurrentMessageMasterResult,
  UpdateCurrentMessageMasterRequest,
  UpdateCurrentMessageMasterResult,
  UpdateCurrentMessageMasterFromGitHubRequest,
  UpdateCurrentMessageMasterFromGitHubResult,
  DescribeGlobalMessageMastersRequest,
  DescribeGlobalMessageMastersResult,
  CreateGlobalMessageMasterRequest,
  CreateGlobalMessageMasterResult,
  GetGlobalMessageMasterRequest,
  GetGlobalMessageMasterResult,
  UpdateGlobalMessageMasterRequest,
  UpdateGlobalMessageMasterResult,
  DeleteGlobalMessageMasterRequest,
  DeleteGlobalMessageMasterResult,
  DescribeGlobalMessagesRequest,
  DescribeGlobalMessagesResult,
  GetGlobalMessageRequest,
  GetGlobalMessageResult,
  GetReceivedByUserIdRequest,
  GetReceivedByUserIdResult,
  UpdateReceivedByUserIdRequest,
  UpdateReceivedByUserIdResult,
  DeleteReceivedByUserIdRequest,
  DeleteReceivedByUserIdResult,
  Gs2InboxRestClient,
};
