import IModel from '../../core/interface/IModel';
import ScriptSetting from './ScriptSetting';
import NotificationSetting from './NotificationSetting';
import LogSetting from './LogSetting';
export default class Namespace implements IModel {
    private namespaceId;
    private name;
    private description;
    private isAutomaticDeletingEnabled;
    private receiveMessageScript;
    private readMessageScript;
    private deleteMessageScript;
    private queueNamespaceId;
    private keyId;
    private receiveNotification;
    private logSetting;
    private createdAt;
    private updatedAt;
    getNamespaceId(): string | null;
    setNamespaceId(namespaceId: string | null): this;
    withNamespaceId(namespaceId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getIsAutomaticDeletingEnabled(): boolean | null;
    setIsAutomaticDeletingEnabled(isAutomaticDeletingEnabled: boolean | null): this;
    withIsAutomaticDeletingEnabled(isAutomaticDeletingEnabled: boolean | null): this;
    getReceiveMessageScript(): ScriptSetting | null;
    setReceiveMessageScript(receiveMessageScript: ScriptSetting | null): this;
    withReceiveMessageScript(receiveMessageScript: ScriptSetting | null): this;
    getReadMessageScript(): ScriptSetting | null;
    setReadMessageScript(readMessageScript: ScriptSetting | null): this;
    withReadMessageScript(readMessageScript: ScriptSetting | null): this;
    getDeleteMessageScript(): ScriptSetting | null;
    setDeleteMessageScript(deleteMessageScript: ScriptSetting | null): this;
    withDeleteMessageScript(deleteMessageScript: ScriptSetting | null): this;
    getQueueNamespaceId(): string | null;
    setQueueNamespaceId(queueNamespaceId: string | null): this;
    withQueueNamespaceId(queueNamespaceId: string | null): this;
    getKeyId(): string | null;
    setKeyId(keyId: string | null): this;
    withKeyId(keyId: string | null): this;
    getReceiveNotification(): NotificationSetting | null;
    setReceiveNotification(receiveNotification: NotificationSetting | null): this;
    withReceiveNotification(receiveNotification: NotificationSetting | null): this;
    getLogSetting(): LogSetting | null;
    setLogSetting(logSetting: LogSetting | null): this;
    withLogSetting(logSetting: LogSetting | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): Namespace | null;
    toDict(): {
        [key: string]: any;
    };
}
