import IModel from '../../core/interface/IModel';
import * as Gs2Stamina from '../../stamina/model';
export default class StaminaModel implements IModel {
    private staminaModelId;
    private name;
    private metadata;
    private recoverIntervalMinutes;
    private recoverValue;
    private initialCapacity;
    private isOverflow;
    private maxCapacity;
    private maxStaminaTable;
    private recoverIntervalTable;
    private recoverValueTable;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static getStaminaName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null, staminaName: string | null): string | null;
    getStaminaModelId(): string | null;
    setStaminaModelId(staminaModelId: string | null): this;
    withStaminaModelId(staminaModelId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getRecoverIntervalMinutes(): number | null;
    setRecoverIntervalMinutes(recoverIntervalMinutes: number | null): this;
    withRecoverIntervalMinutes(recoverIntervalMinutes: number | null): this;
    getRecoverValue(): number | null;
    setRecoverValue(recoverValue: number | null): this;
    withRecoverValue(recoverValue: number | null): this;
    getInitialCapacity(): number | null;
    setInitialCapacity(initialCapacity: number | null): this;
    withInitialCapacity(initialCapacity: number | null): this;
    getIsOverflow(): boolean | null;
    setIsOverflow(isOverflow: boolean | null): this;
    withIsOverflow(isOverflow: boolean | null): this;
    getMaxCapacity(): number | null;
    setMaxCapacity(maxCapacity: number | null): this;
    withMaxCapacity(maxCapacity: number | null): this;
    getMaxStaminaTable(): Gs2Stamina.MaxStaminaTable | null;
    setMaxStaminaTable(maxStaminaTable: Gs2Stamina.MaxStaminaTable | null): this;
    withMaxStaminaTable(maxStaminaTable: Gs2Stamina.MaxStaminaTable | null): this;
    getRecoverIntervalTable(): Gs2Stamina.RecoverIntervalTable | null;
    setRecoverIntervalTable(recoverIntervalTable: Gs2Stamina.RecoverIntervalTable | null): this;
    withRecoverIntervalTable(recoverIntervalTable: Gs2Stamina.RecoverIntervalTable | null): this;
    getRecoverValueTable(): Gs2Stamina.RecoverValueTable | null;
    setRecoverValueTable(recoverValueTable: Gs2Stamina.RecoverValueTable | null): this;
    withRecoverValueTable(recoverValueTable: Gs2Stamina.RecoverValueTable | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): StaminaModel | null;
    toDict(): {
        [key: string]: any;
    };
}
