import IModel from '../../core/interface/IModel';
export default class Stamina implements IModel {
    private staminaId;
    private staminaName;
    private userId;
    private value;
    private maxValue;
    private recoverIntervalMinutes;
    private recoverValue;
    private overflowValue;
    private nextRecoverAt;
    private lastRecoveredAt;
    private createdAt;
    private updatedAt;
    getStaminaId(): string | null;
    setStaminaId(staminaId: string | null): this;
    withStaminaId(staminaId: string | null): this;
    getStaminaName(): string | null;
    setStaminaName(staminaName: string | null): this;
    withStaminaName(staminaName: string | null): this;
    getUserId(): string | null;
    setUserId(userId: string | null): this;
    withUserId(userId: string | null): this;
    getValue(): number | null;
    setValue(value: number | null): this;
    withValue(value: number | null): this;
    getMaxValue(): number | null;
    setMaxValue(maxValue: number | null): this;
    withMaxValue(maxValue: number | null): this;
    getRecoverIntervalMinutes(): number | null;
    setRecoverIntervalMinutes(recoverIntervalMinutes: number | null): this;
    withRecoverIntervalMinutes(recoverIntervalMinutes: number | null): this;
    getRecoverValue(): number | null;
    setRecoverValue(recoverValue: number | null): this;
    withRecoverValue(recoverValue: number | null): this;
    getOverflowValue(): number | null;
    setOverflowValue(overflowValue: number | null): this;
    withOverflowValue(overflowValue: number | null): this;
    getNextRecoverAt(): number | null;
    setNextRecoverAt(nextRecoverAt: number | null): this;
    withNextRecoverAt(nextRecoverAt: number | null): this;
    getLastRecoveredAt(): number | null;
    setLastRecoveredAt(lastRecoveredAt: number | null): this;
    withLastRecoveredAt(lastRecoveredAt: number | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): Stamina | null;
    toDict(): {
        [key: string]: any;
    };
}
