import IModel from '../../core/interface/IModel';
export default class StaminaModelMaster implements IModel {
    private staminaModelId;
    private name;
    private metadata;
    private description;
    private recoverIntervalMinutes;
    private recoverValue;
    private initialCapacity;
    private isOverflow;
    private maxCapacity;
    private maxStaminaTableName;
    private recoverIntervalTableName;
    private recoverValueTableName;
    private createdAt;
    private updatedAt;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static getStaminaName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null, staminaName: string | null): string | null;
    getStaminaModelId(): string | null;
    setStaminaModelId(staminaModelId: string | null): this;
    withStaminaModelId(staminaModelId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getRecoverIntervalMinutes(): number | null;
    setRecoverIntervalMinutes(recoverIntervalMinutes: number | null): this;
    withRecoverIntervalMinutes(recoverIntervalMinutes: number | null): this;
    getRecoverValue(): number | null;
    setRecoverValue(recoverValue: number | null): this;
    withRecoverValue(recoverValue: number | null): this;
    getInitialCapacity(): number | null;
    setInitialCapacity(initialCapacity: number | null): this;
    withInitialCapacity(initialCapacity: number | null): this;
    getIsOverflow(): boolean | null;
    setIsOverflow(isOverflow: boolean | null): this;
    withIsOverflow(isOverflow: boolean | null): this;
    getMaxCapacity(): number | null;
    setMaxCapacity(maxCapacity: number | null): this;
    withMaxCapacity(maxCapacity: number | null): this;
    getMaxStaminaTableName(): string | null;
    setMaxStaminaTableName(maxStaminaTableName: string | null): this;
    withMaxStaminaTableName(maxStaminaTableName: string | null): this;
    getRecoverIntervalTableName(): string | null;
    setRecoverIntervalTableName(recoverIntervalTableName: string | null): this;
    withRecoverIntervalTableName(recoverIntervalTableName: string | null): this;
    getRecoverValueTableName(): string | null;
    setRecoverValueTableName(recoverValueTableName: string | null): this;
    withRecoverValueTableName(recoverValueTableName: string | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): StaminaModelMaster | null;
    toDict(): {
        [key: string]: any;
    };
}
