import IModel from '../../core/interface/IModel';
import ScriptSetting from './ScriptSetting';
import NotificationSetting from './NotificationSetting';
import LogSetting from './LogSetting';
export default class Namespace implements IModel {
    private namespaceId;
    private name;
    private description;
    private allowCreateRoom;
    private postMessageScript;
    private createRoomScript;
    private deleteRoomScript;
    private subscribeRoomScript;
    private unsubscribeRoomScript;
    private postNotification;
    private logSetting;
    private createdAt;
    private updatedAt;
    getNamespaceId(): string | null;
    setNamespaceId(namespaceId: string | null): this;
    withNamespaceId(namespaceId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getAllowCreateRoom(): boolean | null;
    setAllowCreateRoom(allowCreateRoom: boolean | null): this;
    withAllowCreateRoom(allowCreateRoom: boolean | null): this;
    getPostMessageScript(): ScriptSetting | null;
    setPostMessageScript(postMessageScript: ScriptSetting | null): this;
    withPostMessageScript(postMessageScript: ScriptSetting | null): this;
    getCreateRoomScript(): ScriptSetting | null;
    setCreateRoomScript(createRoomScript: ScriptSetting | null): this;
    withCreateRoomScript(createRoomScript: ScriptSetting | null): this;
    getDeleteRoomScript(): ScriptSetting | null;
    setDeleteRoomScript(deleteRoomScript: ScriptSetting | null): this;
    withDeleteRoomScript(deleteRoomScript: ScriptSetting | null): this;
    getSubscribeRoomScript(): ScriptSetting | null;
    setSubscribeRoomScript(subscribeRoomScript: ScriptSetting | null): this;
    withSubscribeRoomScript(subscribeRoomScript: ScriptSetting | null): this;
    getUnsubscribeRoomScript(): ScriptSetting | null;
    setUnsubscribeRoomScript(unsubscribeRoomScript: ScriptSetting | null): this;
    withUnsubscribeRoomScript(unsubscribeRoomScript: ScriptSetting | null): this;
    getPostNotification(): NotificationSetting | null;
    setPostNotification(postNotification: NotificationSetting | null): this;
    withPostNotification(postNotification: NotificationSetting | null): this;
    getLogSetting(): LogSetting | null;
    setLogSetting(logSetting: LogSetting | null): this;
    withLogSetting(logSetting: LogSetting | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): Namespace | null;
    toDict(): {
        [key: string]: any;
    };
}
