import IModel from '../../core/interface/IModel';
import * as Gs2Chat from '../../chat/model';
export default class Namespace implements IModel {
    private namespaceId;
    private name;
    private description;
    private transactionSetting;
    private allowCreateRoom;
    private messageLifeTimeDays;
    private postMessageScript;
    private createRoomScript;
    private deleteRoomScript;
    private subscribeRoomScript;
    private unsubscribeRoomScript;
    private postNotification;
    private logSetting;
    private createdAt;
    private updatedAt;
    private revision;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null): string | null;
    getNamespaceId(): string | null;
    setNamespaceId(namespaceId: string | null): this;
    withNamespaceId(namespaceId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getTransactionSetting(): Gs2Chat.TransactionSetting | null;
    setTransactionSetting(transactionSetting: Gs2Chat.TransactionSetting | null): this;
    withTransactionSetting(transactionSetting: Gs2Chat.TransactionSetting | null): this;
    getAllowCreateRoom(): boolean | null;
    setAllowCreateRoom(allowCreateRoom: boolean | null): this;
    withAllowCreateRoom(allowCreateRoom: boolean | null): this;
    getMessageLifeTimeDays(): number | null;
    setMessageLifeTimeDays(messageLifeTimeDays: number | null): this;
    withMessageLifeTimeDays(messageLifeTimeDays: number | null): this;
    getPostMessageScript(): Gs2Chat.ScriptSetting | null;
    setPostMessageScript(postMessageScript: Gs2Chat.ScriptSetting | null): this;
    withPostMessageScript(postMessageScript: Gs2Chat.ScriptSetting | null): this;
    getCreateRoomScript(): Gs2Chat.ScriptSetting | null;
    setCreateRoomScript(createRoomScript: Gs2Chat.ScriptSetting | null): this;
    withCreateRoomScript(createRoomScript: Gs2Chat.ScriptSetting | null): this;
    getDeleteRoomScript(): Gs2Chat.ScriptSetting | null;
    setDeleteRoomScript(deleteRoomScript: Gs2Chat.ScriptSetting | null): this;
    withDeleteRoomScript(deleteRoomScript: Gs2Chat.ScriptSetting | null): this;
    getSubscribeRoomScript(): Gs2Chat.ScriptSetting | null;
    setSubscribeRoomScript(subscribeRoomScript: Gs2Chat.ScriptSetting | null): this;
    withSubscribeRoomScript(subscribeRoomScript: Gs2Chat.ScriptSetting | null): this;
    getUnsubscribeRoomScript(): Gs2Chat.ScriptSetting | null;
    setUnsubscribeRoomScript(unsubscribeRoomScript: Gs2Chat.ScriptSetting | null): this;
    withUnsubscribeRoomScript(unsubscribeRoomScript: Gs2Chat.ScriptSetting | null): this;
    getPostNotification(): Gs2Chat.NotificationSetting | null;
    setPostNotification(postNotification: Gs2Chat.NotificationSetting | null): this;
    withPostNotification(postNotification: Gs2Chat.NotificationSetting | null): this;
    getLogSetting(): Gs2Chat.LogSetting | null;
    setLogSetting(logSetting: Gs2Chat.LogSetting | null): this;
    withLogSetting(logSetting: Gs2Chat.LogSetting | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    getRevision(): number | null;
    setRevision(revision: number | null): this;
    withRevision(revision: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): Namespace | null;
    toDict(): {
        [key: string]: any;
    };
}
