import IRequest from '../../core/interface/IRequest';
import * as Gs2Buff from '../model';
export default class UpdateBuffEntryModelMasterRequest implements IRequest {
    private requestId;
    private contextStack;
    private namespaceName;
    private buffEntryName;
    private description;
    private metadata;
    private targetType;
    private targetModel;
    private targetAction;
    private expression;
    private priority;
    private applyPeriodScheduleEventId;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getBuffEntryName(): string | null;
    setBuffEntryName(buffEntryName: string | null): this;
    withBuffEntryName(buffEntryName: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getTargetType(): string | null;
    setTargetType(targetType: string | null): this;
    withTargetType(targetType: string | null): this;
    getTargetModel(): Gs2Buff.BuffTargetModel | null;
    setTargetModel(targetModel: Gs2Buff.BuffTargetModel | null): this;
    withTargetModel(targetModel: Gs2Buff.BuffTargetModel | null): this;
    getTargetAction(): Gs2Buff.BuffTargetAction | null;
    setTargetAction(targetAction: Gs2Buff.BuffTargetAction | null): this;
    withTargetAction(targetAction: Gs2Buff.BuffTargetAction | null): this;
    getExpression(): string | null;
    setExpression(expression: string | null): this;
    withExpression(expression: string | null): this;
    getPriority(): number | null;
    setPriority(priority: number | null): this;
    withPriority(priority: number | null): this;
    getApplyPeriodScheduleEventId(): string | null;
    setApplyPeriodScheduleEventId(applyPeriodScheduleEventId: string | null): this;
    withApplyPeriodScheduleEventId(applyPeriodScheduleEventId: string | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): UpdateBuffEntryModelMasterRequest;
    toDict(): {
        [key: string]: any;
    };
}
