import IModel from '../../core/interface/IModel';
import PlatformSetting from './PlatformSetting';
import ScriptSetting from './ScriptSetting';
import LogSetting from './LogSetting';
export default class Namespace implements IModel {
    private namespaceId;
    private name;
    private description;
    private currencyUsagePriority;
    private sharedFreeCurrency;
    private platformSetting;
    private changeBalanceScript;
    private logSetting;
    private createdAt;
    private updatedAt;
    private revision;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null): string | null;
    getNamespaceId(): string | null;
    setNamespaceId(namespaceId: string | null): this;
    withNamespaceId(namespaceId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getCurrencyUsagePriority(): string | null;
    setCurrencyUsagePriority(currencyUsagePriority: string | null): this;
    withCurrencyUsagePriority(currencyUsagePriority: string | null): this;
    getSharedFreeCurrency(): boolean | null;
    setSharedFreeCurrency(sharedFreeCurrency: boolean | null): this;
    withSharedFreeCurrency(sharedFreeCurrency: boolean | null): this;
    getPlatformSetting(): PlatformSetting | null;
    setPlatformSetting(platformSetting: PlatformSetting | null): this;
    withPlatformSetting(platformSetting: PlatformSetting | null): this;
    getChangeBalanceScript(): ScriptSetting | null;
    setChangeBalanceScript(changeBalanceScript: ScriptSetting | null): this;
    withChangeBalanceScript(changeBalanceScript: ScriptSetting | null): this;
    getLogSetting(): LogSetting | null;
    setLogSetting(logSetting: LogSetting | null): this;
    withLogSetting(logSetting: LogSetting | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    getRevision(): number | null;
    setRevision(revision: number | null): this;
    withRevision(revision: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): Namespace | null;
    toDict(): {
        [key: string]: any;
    };
}
