import IModel from '../../core/interface/IModel';
import * as Gs2Money2 from '../../money2/model';
export default class StoreSubscriptionContentModelMaster implements IModel {
    private storeSubscriptionContentModelId;
    private name;
    private description;
    private metadata;
    private scheduleNamespaceId;
    private triggerName;
    private reallocateSpanDays;
    private triggerExtendMode;
    private rollupHour;
    private appleAppStore;
    private googlePlay;
    private createdAt;
    private updatedAt;
    private revision;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static getContentName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null, contentName: string | null): string | null;
    getStoreSubscriptionContentModelId(): string | null;
    setStoreSubscriptionContentModelId(storeSubscriptionContentModelId: string | null): this;
    withStoreSubscriptionContentModelId(storeSubscriptionContentModelId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getScheduleNamespaceId(): string | null;
    setScheduleNamespaceId(scheduleNamespaceId: string | null): this;
    withScheduleNamespaceId(scheduleNamespaceId: string | null): this;
    getTriggerName(): string | null;
    setTriggerName(triggerName: string | null): this;
    withTriggerName(triggerName: string | null): this;
    getReallocateSpanDays(): number | null;
    setReallocateSpanDays(reallocateSpanDays: number | null): this;
    withReallocateSpanDays(reallocateSpanDays: number | null): this;
    getTriggerExtendMode(): string | null;
    setTriggerExtendMode(triggerExtendMode: string | null): this;
    withTriggerExtendMode(triggerExtendMode: string | null): this;
    getRollupHour(): number | null;
    setRollupHour(rollupHour: number | null): this;
    withRollupHour(rollupHour: number | null): this;
    getAppleAppStore(): Gs2Money2.AppleAppStoreSubscriptionContent | null;
    setAppleAppStore(appleAppStore: Gs2Money2.AppleAppStoreSubscriptionContent | null): this;
    withAppleAppStore(appleAppStore: Gs2Money2.AppleAppStoreSubscriptionContent | null): this;
    getGooglePlay(): Gs2Money2.GooglePlaySubscriptionContent | null;
    setGooglePlay(googlePlay: Gs2Money2.GooglePlaySubscriptionContent | null): this;
    withGooglePlay(googlePlay: Gs2Money2.GooglePlaySubscriptionContent | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    getRevision(): number | null;
    setRevision(revision: number | null): this;
    withRevision(revision: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): StoreSubscriptionContentModelMaster | null;
    toDict(): {
        [key: string]: any;
    };
}
