import IRequest from '../../core/interface/IRequest';
export default class UpdateCategoryModelMasterRequest implements IRequest {
    private requestId;
    private contextStack;
    private namespaceName;
    private categoryName;
    private description;
    private metadata;
    private minimumValue;
    private maximumValue;
    private orderDirection;
    private scope;
    private uniqueByUserId;
    private sum;
    private calculateFixedTimingHour;
    private calculateFixedTimingMinute;
    private calculateIntervalMinutes;
    private entryPeriodEventId;
    private accessPeriodEventId;
    private generation;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getCategoryName(): string | null;
    setCategoryName(categoryName: string | null): this;
    withCategoryName(categoryName: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getMinimumValue(): number | null;
    setMinimumValue(minimumValue: number | null): this;
    withMinimumValue(minimumValue: number | null): this;
    getMaximumValue(): number | null;
    setMaximumValue(maximumValue: number | null): this;
    withMaximumValue(maximumValue: number | null): this;
    getOrderDirection(): string | null;
    setOrderDirection(orderDirection: string | null): this;
    withOrderDirection(orderDirection: string | null): this;
    getScope(): string | null;
    setScope(scope: string | null): this;
    withScope(scope: string | null): this;
    getUniqueByUserId(): boolean | null;
    setUniqueByUserId(uniqueByUserId: boolean | null): this;
    withUniqueByUserId(uniqueByUserId: boolean | null): this;
    getSum(): boolean | null;
    setSum(sum: boolean | null): this;
    withSum(sum: boolean | null): this;
    getCalculateFixedTimingHour(): number | null;
    setCalculateFixedTimingHour(calculateFixedTimingHour: number | null): this;
    withCalculateFixedTimingHour(calculateFixedTimingHour: number | null): this;
    getCalculateFixedTimingMinute(): number | null;
    setCalculateFixedTimingMinute(calculateFixedTimingMinute: number | null): this;
    withCalculateFixedTimingMinute(calculateFixedTimingMinute: number | null): this;
    getCalculateIntervalMinutes(): number | null;
    setCalculateIntervalMinutes(calculateIntervalMinutes: number | null): this;
    withCalculateIntervalMinutes(calculateIntervalMinutes: number | null): this;
    getEntryPeriodEventId(): string | null;
    setEntryPeriodEventId(entryPeriodEventId: string | null): this;
    withEntryPeriodEventId(entryPeriodEventId: string | null): this;
    getAccessPeriodEventId(): string | null;
    setAccessPeriodEventId(accessPeriodEventId: string | null): this;
    withAccessPeriodEventId(accessPeriodEventId: string | null): this;
    getGeneration(): string | null;
    setGeneration(generation: string | null): this;
    withGeneration(generation: string | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): UpdateCategoryModelMasterRequest;
    toDict(): {
        [key: string]: any;
    };
}
