import IModel from '../../core/interface/IModel';
import ExperienceNamespaceStatistics from './ExperienceNamespaceStatistics';
import ExperienceNamespaceDistributions from './ExperienceNamespaceDistributions';
import ExperienceExperienceModel from './ExperienceExperienceModel';
export default class ExperienceNamespace implements IModel {
    private namespaceId;
    private year;
    private month;
    private day;
    private namespaceName;
    private statistics;
    private distributions;
    private experienceModels;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getYear(grn: string): string | null;
    static getMonth(grn: string): string | null;
    static getDay(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, year: string | null, month: string | null, day: string | null, namespaceName: string | null): string | null;
    getNamespaceId(): string | null;
    setNamespaceId(namespaceId: string | null): this;
    withNamespaceId(namespaceId: string | null): this;
    getYear(): number | null;
    setYear(year: number | null): this;
    withYear(year: number | null): this;
    getMonth(): number | null;
    setMonth(month: number | null): this;
    withMonth(month: number | null): this;
    getDay(): number | null;
    setDay(day: number | null): this;
    withDay(day: number | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getStatistics(): ExperienceNamespaceStatistics | null;
    setStatistics(statistics: ExperienceNamespaceStatistics | null): this;
    withStatistics(statistics: ExperienceNamespaceStatistics | null): this;
    getDistributions(): ExperienceNamespaceDistributions | null;
    setDistributions(distributions: ExperienceNamespaceDistributions | null): this;
    withDistributions(distributions: ExperienceNamespaceDistributions | null): this;
    getExperienceModels(): ExperienceExperienceModel[] | null;
    setExperienceModels(experienceModels: ExperienceExperienceModel[] | null): this;
    withExperienceModels(experienceModels: ExperienceExperienceModel[] | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): ExperienceNamespace | null;
    toDict(): {
        [key: string]: any;
    };
}
