import IModel from '../../core/interface/IModel';
import ShowcaseNamespaceStatistics from './ShowcaseNamespaceStatistics';
import ShowcaseNamespaceDistributions from './ShowcaseNamespaceDistributions';
import ShowcaseShowcase from './ShowcaseShowcase';
export default class ShowcaseNamespace implements IModel {
    private namespaceId;
    private year;
    private month;
    private day;
    private namespaceName;
    private statistics;
    private distributions;
    private showcases;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getYear(grn: string): string | null;
    static getMonth(grn: string): string | null;
    static getDay(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, year: string | null, month: string | null, day: string | null, namespaceName: string | null): string | null;
    getNamespaceId(): string | null;
    setNamespaceId(namespaceId: string | null): this;
    withNamespaceId(namespaceId: string | null): this;
    getYear(): number | null;
    setYear(year: number | null): this;
    withYear(year: number | null): this;
    getMonth(): number | null;
    setMonth(month: number | null): this;
    withMonth(month: number | null): this;
    getDay(): number | null;
    setDay(day: number | null): this;
    withDay(day: number | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getStatistics(): ShowcaseNamespaceStatistics | null;
    setStatistics(statistics: ShowcaseNamespaceStatistics | null): this;
    withStatistics(statistics: ShowcaseNamespaceStatistics | null): this;
    getDistributions(): ShowcaseNamespaceDistributions | null;
    setDistributions(distributions: ShowcaseNamespaceDistributions | null): this;
    withDistributions(distributions: ShowcaseNamespaceDistributions | null): this;
    getShowcases(): ShowcaseShowcase[] | null;
    setShowcases(showcases: ShowcaseShowcase[] | null): this;
    withShowcases(showcases: ShowcaseShowcase[] | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): ShowcaseNamespace | null;
    toDict(): {
        [key: string]: any;
    };
}
