import IModel from '../../core/interface/IModel';
export default class UseServices implements IModel {
    private account;
    private chat;
    private datastore;
    private dictionary;
    private exchange;
    private experience;
    private formation;
    private friend;
    private inbox;
    private inventory;
    private key;
    private limit;
    private matchmaking;
    private mission;
    private money;
    private quest;
    private ranking;
    private showcase;
    private stamina;
    getAccount(): boolean | null;
    setAccount(account: boolean | null): this;
    withAccount(account: boolean | null): this;
    getChat(): boolean | null;
    setChat(chat: boolean | null): this;
    withChat(chat: boolean | null): this;
    getDatastore(): boolean | null;
    setDatastore(datastore: boolean | null): this;
    withDatastore(datastore: boolean | null): this;
    getDictionary(): boolean | null;
    setDictionary(dictionary: boolean | null): this;
    withDictionary(dictionary: boolean | null): this;
    getExchange(): boolean | null;
    setExchange(exchange: boolean | null): this;
    withExchange(exchange: boolean | null): this;
    getExperience(): boolean | null;
    setExperience(experience: boolean | null): this;
    withExperience(experience: boolean | null): this;
    getFormation(): boolean | null;
    setFormation(formation: boolean | null): this;
    withFormation(formation: boolean | null): this;
    getFriend(): boolean | null;
    setFriend(friend: boolean | null): this;
    withFriend(friend: boolean | null): this;
    getInbox(): boolean | null;
    setInbox(inbox: boolean | null): this;
    withInbox(inbox: boolean | null): this;
    getInventory(): boolean | null;
    setInventory(inventory: boolean | null): this;
    withInventory(inventory: boolean | null): this;
    getKey(): boolean | null;
    setKey(key: boolean | null): this;
    withKey(key: boolean | null): this;
    getLimit(): boolean | null;
    setLimit(limit: boolean | null): this;
    withLimit(limit: boolean | null): this;
    getMatchmaking(): boolean | null;
    setMatchmaking(matchmaking: boolean | null): this;
    withMatchmaking(matchmaking: boolean | null): this;
    getMission(): boolean | null;
    setMission(mission: boolean | null): this;
    withMission(mission: boolean | null): this;
    getMoney(): boolean | null;
    setMoney(money: boolean | null): this;
    withMoney(money: boolean | null): this;
    getQuest(): boolean | null;
    setQuest(quest: boolean | null): this;
    withQuest(quest: boolean | null): this;
    getRanking(): boolean | null;
    setRanking(ranking: boolean | null): this;
    withRanking(ranking: boolean | null): this;
    getShowcase(): boolean | null;
    setShowcase(showcase: boolean | null): this;
    withShowcase(showcase: boolean | null): this;
    getStamina(): boolean | null;
    setStamina(stamina: boolean | null): this;
    withStamina(stamina: boolean | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): UseServices | null;
    toDict(): {
        [key: string]: any;
    };
}
