import IModel from '../../core/interface/IModel';
import * as Gs2Showcase from '../../showcase/model';
export default class RandomShowcaseMaster implements IModel {
    private showcaseId;
    private name;
    private description;
    private metadata;
    private maximumNumberOfChoice;
    private displayItems;
    private baseTimestamp;
    private resetIntervalHours;
    private salesPeriodEventId;
    private createdAt;
    private updatedAt;
    private revision;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static getShowcaseName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null, showcaseName: string | null): string | null;
    getShowcaseId(): string | null;
    setShowcaseId(showcaseId: string | null): this;
    withShowcaseId(showcaseId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getMaximumNumberOfChoice(): number | null;
    setMaximumNumberOfChoice(maximumNumberOfChoice: number | null): this;
    withMaximumNumberOfChoice(maximumNumberOfChoice: number | null): this;
    getDisplayItems(): Gs2Showcase.RandomDisplayItemModel[] | null;
    setDisplayItems(displayItems: Gs2Showcase.RandomDisplayItemModel[] | null): this;
    withDisplayItems(displayItems: Gs2Showcase.RandomDisplayItemModel[] | null): this;
    getBaseTimestamp(): number | null;
    setBaseTimestamp(baseTimestamp: number | null): this;
    withBaseTimestamp(baseTimestamp: number | null): this;
    getResetIntervalHours(): number | null;
    setResetIntervalHours(resetIntervalHours: number | null): this;
    withResetIntervalHours(resetIntervalHours: number | null): this;
    getSalesPeriodEventId(): string | null;
    setSalesPeriodEventId(salesPeriodEventId: string | null): this;
    withSalesPeriodEventId(salesPeriodEventId: string | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    getRevision(): number | null;
    setRevision(revision: number | null): this;
    withRevision(revision: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): RandomShowcaseMaster | null;
    toDict(): {
        [key: string]: any;
    };
}
