import IRequest from '../../core/interface/IRequest';
export default class CreateMissionGroupModelMasterRequest implements IRequest {
    private requestId;
    private contextStack;
    private namespaceName;
    private name;
    private metadata;
    private description;
    private resetType;
    private resetDayOfMonth;
    private resetDayOfWeek;
    private resetHour;
    private anchorTimestamp;
    private days;
    private completeNotificationNamespaceId;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getResetType(): string | null;
    setResetType(resetType: string | null): this;
    withResetType(resetType: string | null): this;
    getResetDayOfMonth(): number | null;
    setResetDayOfMonth(resetDayOfMonth: number | null): this;
    withResetDayOfMonth(resetDayOfMonth: number | null): this;
    getResetDayOfWeek(): string | null;
    setResetDayOfWeek(resetDayOfWeek: string | null): this;
    withResetDayOfWeek(resetDayOfWeek: string | null): this;
    getResetHour(): number | null;
    setResetHour(resetHour: number | null): this;
    withResetHour(resetHour: number | null): this;
    getAnchorTimestamp(): number | null;
    setAnchorTimestamp(anchorTimestamp: number | null): this;
    withAnchorTimestamp(anchorTimestamp: number | null): this;
    getDays(): number | null;
    setDays(days: number | null): this;
    withDays(days: number | null): this;
    getCompleteNotificationNamespaceId(): string | null;
    setCompleteNotificationNamespaceId(completeNotificationNamespaceId: string | null): this;
    withCompleteNotificationNamespaceId(completeNotificationNamespaceId: string | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): CreateMissionGroupModelMasterRequest;
    toDict(): {
        [key: string]: any;
    };
}
