import IRequest from '../../core/interface/IRequest';
import * as Gs2Mission from '../model';
export default class UpdateNamespaceRequest implements IRequest {
    private requestId;
    private contextStack;
    private namespaceName;
    private description;
    private missionCompleteScript;
    private counterIncrementScript;
    private receiveRewardsScript;
    private queueNamespaceId;
    private keyId;
    private completeNotification;
    private logSetting;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getMissionCompleteScript(): Gs2Mission.ScriptSetting | null;
    setMissionCompleteScript(missionCompleteScript: Gs2Mission.ScriptSetting | null): this;
    withMissionCompleteScript(missionCompleteScript: Gs2Mission.ScriptSetting | null): this;
    getCounterIncrementScript(): Gs2Mission.ScriptSetting | null;
    setCounterIncrementScript(counterIncrementScript: Gs2Mission.ScriptSetting | null): this;
    withCounterIncrementScript(counterIncrementScript: Gs2Mission.ScriptSetting | null): this;
    getReceiveRewardsScript(): Gs2Mission.ScriptSetting | null;
    setReceiveRewardsScript(receiveRewardsScript: Gs2Mission.ScriptSetting | null): this;
    withReceiveRewardsScript(receiveRewardsScript: Gs2Mission.ScriptSetting | null): this;
    getQueueNamespaceId(): string | null;
    setQueueNamespaceId(queueNamespaceId: string | null): this;
    withQueueNamespaceId(queueNamespaceId: string | null): this;
    getKeyId(): string | null;
    setKeyId(keyId: string | null): this;
    withKeyId(keyId: string | null): this;
    getCompleteNotification(): Gs2Mission.NotificationSetting | null;
    setCompleteNotification(completeNotification: Gs2Mission.NotificationSetting | null): this;
    withCompleteNotification(completeNotification: Gs2Mission.NotificationSetting | null): this;
    getLogSetting(): Gs2Mission.LogSetting | null;
    setLogSetting(logSetting: Gs2Mission.LogSetting | null): this;
    withLogSetting(logSetting: Gs2Mission.LogSetting | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): UpdateNamespaceRequest;
    toDict(): {
        [key: string]: any;
    };
}
