import IModel from '@/gs2/core/interface/IModel';
export declare class Billing implements IModel {
    private billingId;
    private projectName;
    private year;
    private month;
    private region;
    private service;
    private activityType;
    private unit;
    private unitName;
    private price;
    private currency;
    private createdAt;
    private updatedAt;
    getBillingId(): string | null;
    setBillingId(billingId: string | null): this;
    withBillingId(billingId: string | null): this;
    getProjectName(): string | null;
    setProjectName(projectName: string | null): this;
    withProjectName(projectName: string | null): this;
    getYear(): number | null;
    setYear(year: number | null): this;
    withYear(year: number | null): this;
    getMonth(): number | null;
    setMonth(month: number | null): this;
    withMonth(month: number | null): this;
    getRegion(): string | null;
    setRegion(region: string | null): this;
    withRegion(region: string | null): this;
    getService(): string | null;
    setService(service: string | null): this;
    withService(service: string | null): this;
    getActivityType(): string | null;
    setActivityType(activityType: string | null): this;
    withActivityType(activityType: string | null): this;
    getUnit(): number | null;
    setUnit(unit: number | null): this;
    withUnit(unit: number | null): this;
    getUnitName(): string | null;
    setUnitName(unitName: string | null): this;
    withUnitName(unitName: string | null): this;
    getPrice(): number | null;
    setPrice(price: number | null): this;
    withPrice(price: number | null): this;
    getCurrency(): string | null;
    setCurrency(currency: string | null): this;
    withCurrency(currency: string | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): Billing | null;
    toDict(): {
        [key: string]: any;
    };
}
