import AbstractGs2RestClient from '../core/AbstractGs2RestClient';
import { Gs2RestSession } from '../core/model';
import * as Request from './request';
import * as Result from './result';
export default class Gs2ScheduleRestClient extends AbstractGs2RestClient {
    constructor(session: Gs2RestSession);
    describeNamespaces(request: Request.DescribeNamespacesRequest): Promise<Result.DescribeNamespacesResult>;
    createNamespace(request: Request.CreateNamespaceRequest): Promise<Result.CreateNamespaceResult>;
    getNamespaceStatus(request: Request.GetNamespaceStatusRequest): Promise<Result.GetNamespaceStatusResult>;
    getNamespace(request: Request.GetNamespaceRequest): Promise<Result.GetNamespaceResult>;
    updateNamespace(request: Request.UpdateNamespaceRequest): Promise<Result.UpdateNamespaceResult>;
    deleteNamespace(request: Request.DeleteNamespaceRequest): Promise<Result.DeleteNamespaceResult>;
    getServiceVersion(request: Request.GetServiceVersionRequest): Promise<Result.GetServiceVersionResult>;
    dumpUserDataByUserId(request: Request.DumpUserDataByUserIdRequest): Promise<Result.DumpUserDataByUserIdResult>;
    checkDumpUserDataByUserId(request: Request.CheckDumpUserDataByUserIdRequest): Promise<Result.CheckDumpUserDataByUserIdResult>;
    cleanUserDataByUserId(request: Request.CleanUserDataByUserIdRequest): Promise<Result.CleanUserDataByUserIdResult>;
    checkCleanUserDataByUserId(request: Request.CheckCleanUserDataByUserIdRequest): Promise<Result.CheckCleanUserDataByUserIdResult>;
    prepareImportUserDataByUserId(request: Request.PrepareImportUserDataByUserIdRequest): Promise<Result.PrepareImportUserDataByUserIdResult>;
    importUserDataByUserId(request: Request.ImportUserDataByUserIdRequest): Promise<Result.ImportUserDataByUserIdResult>;
    checkImportUserDataByUserId(request: Request.CheckImportUserDataByUserIdRequest): Promise<Result.CheckImportUserDataByUserIdResult>;
    describeEventMasters(request: Request.DescribeEventMastersRequest): Promise<Result.DescribeEventMastersResult>;
    createEventMaster(request: Request.CreateEventMasterRequest): Promise<Result.CreateEventMasterResult>;
    getEventMaster(request: Request.GetEventMasterRequest): Promise<Result.GetEventMasterResult>;
    updateEventMaster(request: Request.UpdateEventMasterRequest): Promise<Result.UpdateEventMasterResult>;
    deleteEventMaster(request: Request.DeleteEventMasterRequest): Promise<Result.DeleteEventMasterResult>;
    describeTriggers(request: Request.DescribeTriggersRequest): Promise<Result.DescribeTriggersResult>;
    describeTriggersByUserId(request: Request.DescribeTriggersByUserIdRequest): Promise<Result.DescribeTriggersByUserIdResult>;
    getTrigger(request: Request.GetTriggerRequest): Promise<Result.GetTriggerResult>;
    getTriggerByUserId(request: Request.GetTriggerByUserIdRequest): Promise<Result.GetTriggerByUserIdResult>;
    triggerByUserId(request: Request.TriggerByUserIdRequest): Promise<Result.TriggerByUserIdResult>;
    extendTriggerByUserId(request: Request.ExtendTriggerByUserIdRequest): Promise<Result.ExtendTriggerByUserIdResult>;
    triggerByStampSheet(request: Request.TriggerByStampSheetRequest): Promise<Result.TriggerByStampSheetResult>;
    extendTriggerByStampSheet(request: Request.ExtendTriggerByStampSheetRequest): Promise<Result.ExtendTriggerByStampSheetResult>;
    deleteTrigger(request: Request.DeleteTriggerRequest): Promise<Result.DeleteTriggerResult>;
    deleteTriggerByUserId(request: Request.DeleteTriggerByUserIdRequest): Promise<Result.DeleteTriggerByUserIdResult>;
    verifyTrigger(request: Request.VerifyTriggerRequest): Promise<Result.VerifyTriggerResult>;
    verifyTriggerByUserId(request: Request.VerifyTriggerByUserIdRequest): Promise<Result.VerifyTriggerByUserIdResult>;
    deleteTriggerByStampTask(request: Request.DeleteTriggerByStampTaskRequest): Promise<Result.DeleteTriggerByStampTaskResult>;
    verifyTriggerByStampTask(request: Request.VerifyTriggerByStampTaskRequest): Promise<Result.VerifyTriggerByStampTaskResult>;
    describeEvents(request: Request.DescribeEventsRequest): Promise<Result.DescribeEventsResult>;
    describeEventsByUserId(request: Request.DescribeEventsByUserIdRequest): Promise<Result.DescribeEventsByUserIdResult>;
    describeRawEvents(request: Request.DescribeRawEventsRequest): Promise<Result.DescribeRawEventsResult>;
    getEvent(request: Request.GetEventRequest): Promise<Result.GetEventResult>;
    getEventByUserId(request: Request.GetEventByUserIdRequest): Promise<Result.GetEventByUserIdResult>;
    getRawEvent(request: Request.GetRawEventRequest): Promise<Result.GetRawEventResult>;
    verifyEvent(request: Request.VerifyEventRequest): Promise<Result.VerifyEventResult>;
    verifyEventByUserId(request: Request.VerifyEventByUserIdRequest): Promise<Result.VerifyEventByUserIdResult>;
    verifyEventByStampTask(request: Request.VerifyEventByStampTaskRequest): Promise<Result.VerifyEventByStampTaskResult>;
    exportMaster(request: Request.ExportMasterRequest): Promise<Result.ExportMasterResult>;
    getCurrentEventMaster(request: Request.GetCurrentEventMasterRequest): Promise<Result.GetCurrentEventMasterResult>;
    preUpdateCurrentEventMaster(request: Request.PreUpdateCurrentEventMasterRequest): Promise<Result.PreUpdateCurrentEventMasterResult>;
    updateCurrentEventMaster(request: Request.UpdateCurrentEventMasterRequest): Promise<Result.UpdateCurrentEventMasterResult>;
    updateCurrentEventMasterFromGitHub(request: Request.UpdateCurrentEventMasterFromGitHubRequest): Promise<Result.UpdateCurrentEventMasterFromGitHubResult>;
}
