import IModel from '../../core/interface/IModel';
import * as Gs2JobQueue from '../../jobQueue/model';
export default class Namespace implements IModel {
    private namespaceId;
    private name;
    private description;
    private enableAutoRun;
    private runNotification;
    private pushNotification;
    private logSetting;
    private createdAt;
    private updatedAt;
    private revision;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null): string | null;
    getNamespaceId(): string | null;
    setNamespaceId(namespaceId: string | null): this;
    withNamespaceId(namespaceId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getEnableAutoRun(): boolean | null;
    setEnableAutoRun(enableAutoRun: boolean | null): this;
    withEnableAutoRun(enableAutoRun: boolean | null): this;
    getRunNotification(): Gs2JobQueue.NotificationSetting | null;
    setRunNotification(runNotification: Gs2JobQueue.NotificationSetting | null): this;
    withRunNotification(runNotification: Gs2JobQueue.NotificationSetting | null): this;
    getPushNotification(): Gs2JobQueue.NotificationSetting | null;
    setPushNotification(pushNotification: Gs2JobQueue.NotificationSetting | null): this;
    withPushNotification(pushNotification: Gs2JobQueue.NotificationSetting | null): this;
    getLogSetting(): Gs2JobQueue.LogSetting | null;
    setLogSetting(logSetting: Gs2JobQueue.LogSetting | null): this;
    withLogSetting(logSetting: Gs2JobQueue.LogSetting | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    getRevision(): number | null;
    setRevision(revision: number | null): this;
    withRevision(revision: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): Namespace | null;
    toDict(): {
        [key: string]: any;
    };
}
