import IRequest from '../../core/interface/IRequest';
import * as Gs2Grade from '../model';
export default class CreateGradeModelMasterRequest implements IRequest {
    private requestId;
    private contextStack;
    private namespaceName;
    private name;
    private description;
    private metadata;
    private defaultGrades;
    private experienceModelId;
    private gradeEntries;
    private acquireActionRates;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getDefaultGrades(): Gs2Grade.DefaultGradeModel[] | null;
    setDefaultGrades(defaultGrades: Gs2Grade.DefaultGradeModel[] | null): this;
    withDefaultGrades(defaultGrades: Gs2Grade.DefaultGradeModel[] | null): this;
    getExperienceModelId(): string | null;
    setExperienceModelId(experienceModelId: string | null): this;
    withExperienceModelId(experienceModelId: string | null): this;
    getGradeEntries(): Gs2Grade.GradeEntryModel[] | null;
    setGradeEntries(gradeEntries: Gs2Grade.GradeEntryModel[] | null): this;
    withGradeEntries(gradeEntries: Gs2Grade.GradeEntryModel[] | null): this;
    getAcquireActionRates(): Gs2Grade.AcquireActionRate[] | null;
    setAcquireActionRates(acquireActionRates: Gs2Grade.AcquireActionRate[] | null): this;
    withAcquireActionRates(acquireActionRates: Gs2Grade.AcquireActionRate[] | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): CreateGradeModelMasterRequest;
    toDict(): {
        [key: string]: any;
    };
}
