import IModel from '../../core/interface/IModel';
import * as Gs2Matchmaking from '../../matchmaking/model';
export default class Namespace implements IModel {
    private namespaceId;
    private name;
    private description;
    private transactionSetting;
    private enableRating;
    private enableDisconnectDetection;
    private disconnectDetectionTimeoutSeconds;
    private createGatheringTriggerType;
    private createGatheringTriggerRealtimeNamespaceId;
    private createGatheringTriggerScriptId;
    private completeMatchmakingTriggerType;
    private completeMatchmakingTriggerRealtimeNamespaceId;
    private completeMatchmakingTriggerScriptId;
    private enableCollaborateSeasonRating;
    private collaborateSeasonRatingNamespaceId;
    private collaborateSeasonRatingTtl;
    private changeRatingScript;
    private joinNotification;
    private leaveNotification;
    private completeNotification;
    private changeRatingNotification;
    private logSetting;
    private createdAt;
    private updatedAt;
    private revision;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null): string | null;
    getNamespaceId(): string | null;
    setNamespaceId(namespaceId: string | null): this;
    withNamespaceId(namespaceId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getTransactionSetting(): Gs2Matchmaking.TransactionSetting | null;
    setTransactionSetting(transactionSetting: Gs2Matchmaking.TransactionSetting | null): this;
    withTransactionSetting(transactionSetting: Gs2Matchmaking.TransactionSetting | null): this;
    getEnableRating(): boolean | null;
    setEnableRating(enableRating: boolean | null): this;
    withEnableRating(enableRating: boolean | null): this;
    getEnableDisconnectDetection(): string | null;
    setEnableDisconnectDetection(enableDisconnectDetection: string | null): this;
    withEnableDisconnectDetection(enableDisconnectDetection: string | null): this;
    getDisconnectDetectionTimeoutSeconds(): number | null;
    setDisconnectDetectionTimeoutSeconds(disconnectDetectionTimeoutSeconds: number | null): this;
    withDisconnectDetectionTimeoutSeconds(disconnectDetectionTimeoutSeconds: number | null): this;
    getCreateGatheringTriggerType(): string | null;
    setCreateGatheringTriggerType(createGatheringTriggerType: string | null): this;
    withCreateGatheringTriggerType(createGatheringTriggerType: string | null): this;
    getCreateGatheringTriggerRealtimeNamespaceId(): string | null;
    setCreateGatheringTriggerRealtimeNamespaceId(createGatheringTriggerRealtimeNamespaceId: string | null): this;
    withCreateGatheringTriggerRealtimeNamespaceId(createGatheringTriggerRealtimeNamespaceId: string | null): this;
    getCreateGatheringTriggerScriptId(): string | null;
    setCreateGatheringTriggerScriptId(createGatheringTriggerScriptId: string | null): this;
    withCreateGatheringTriggerScriptId(createGatheringTriggerScriptId: string | null): this;
    getCompleteMatchmakingTriggerType(): string | null;
    setCompleteMatchmakingTriggerType(completeMatchmakingTriggerType: string | null): this;
    withCompleteMatchmakingTriggerType(completeMatchmakingTriggerType: string | null): this;
    getCompleteMatchmakingTriggerRealtimeNamespaceId(): string | null;
    setCompleteMatchmakingTriggerRealtimeNamespaceId(completeMatchmakingTriggerRealtimeNamespaceId: string | null): this;
    withCompleteMatchmakingTriggerRealtimeNamespaceId(completeMatchmakingTriggerRealtimeNamespaceId: string | null): this;
    getCompleteMatchmakingTriggerScriptId(): string | null;
    setCompleteMatchmakingTriggerScriptId(completeMatchmakingTriggerScriptId: string | null): this;
    withCompleteMatchmakingTriggerScriptId(completeMatchmakingTriggerScriptId: string | null): this;
    getEnableCollaborateSeasonRating(): string | null;
    setEnableCollaborateSeasonRating(enableCollaborateSeasonRating: string | null): this;
    withEnableCollaborateSeasonRating(enableCollaborateSeasonRating: string | null): this;
    getCollaborateSeasonRatingNamespaceId(): string | null;
    setCollaborateSeasonRatingNamespaceId(collaborateSeasonRatingNamespaceId: string | null): this;
    withCollaborateSeasonRatingNamespaceId(collaborateSeasonRatingNamespaceId: string | null): this;
    getCollaborateSeasonRatingTtl(): number | null;
    setCollaborateSeasonRatingTtl(collaborateSeasonRatingTtl: number | null): this;
    withCollaborateSeasonRatingTtl(collaborateSeasonRatingTtl: number | null): this;
    getChangeRatingScript(): Gs2Matchmaking.ScriptSetting | null;
    setChangeRatingScript(changeRatingScript: Gs2Matchmaking.ScriptSetting | null): this;
    withChangeRatingScript(changeRatingScript: Gs2Matchmaking.ScriptSetting | null): this;
    getJoinNotification(): Gs2Matchmaking.NotificationSetting | null;
    setJoinNotification(joinNotification: Gs2Matchmaking.NotificationSetting | null): this;
    withJoinNotification(joinNotification: Gs2Matchmaking.NotificationSetting | null): this;
    getLeaveNotification(): Gs2Matchmaking.NotificationSetting | null;
    setLeaveNotification(leaveNotification: Gs2Matchmaking.NotificationSetting | null): this;
    withLeaveNotification(leaveNotification: Gs2Matchmaking.NotificationSetting | null): this;
    getCompleteNotification(): Gs2Matchmaking.NotificationSetting | null;
    setCompleteNotification(completeNotification: Gs2Matchmaking.NotificationSetting | null): this;
    withCompleteNotification(completeNotification: Gs2Matchmaking.NotificationSetting | null): this;
    getChangeRatingNotification(): Gs2Matchmaking.NotificationSetting | null;
    setChangeRatingNotification(changeRatingNotification: Gs2Matchmaking.NotificationSetting | null): this;
    withChangeRatingNotification(changeRatingNotification: Gs2Matchmaking.NotificationSetting | null): this;
    getLogSetting(): Gs2Matchmaking.LogSetting | null;
    setLogSetting(logSetting: Gs2Matchmaking.LogSetting | null): this;
    withLogSetting(logSetting: Gs2Matchmaking.LogSetting | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    getRevision(): number | null;
    setRevision(revision: number | null): this;
    withRevision(revision: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): Namespace | null;
    toDict(): {
        [key: string]: any;
    };
}
