import IModel from '../../core/interface/IModel';
import ScriptSetting from './ScriptSetting';
import NotificationSetting from './NotificationSetting';
import LogSetting from './LogSetting';
export default class Namespace implements IModel {
    private namespaceId;
    private name;
    private description;
    private enableRating;
    private createGatheringTriggerType;
    private createGatheringTriggerRealtimeNamespaceId;
    private createGatheringTriggerScriptId;
    private completeMatchmakingTriggerType;
    private completeMatchmakingTriggerRealtimeNamespaceId;
    private completeMatchmakingTriggerScriptId;
    private changeRatingScript;
    private joinNotification;
    private leaveNotification;
    private completeNotification;
    private logSetting;
    private createdAt;
    private updatedAt;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null): string | null;
    getNamespaceId(): string | null;
    setNamespaceId(namespaceId: string | null): this;
    withNamespaceId(namespaceId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getEnableRating(): boolean | null;
    setEnableRating(enableRating: boolean | null): this;
    withEnableRating(enableRating: boolean | null): this;
    getCreateGatheringTriggerType(): string | null;
    setCreateGatheringTriggerType(createGatheringTriggerType: string | null): this;
    withCreateGatheringTriggerType(createGatheringTriggerType: string | null): this;
    getCreateGatheringTriggerRealtimeNamespaceId(): string | null;
    setCreateGatheringTriggerRealtimeNamespaceId(createGatheringTriggerRealtimeNamespaceId: string | null): this;
    withCreateGatheringTriggerRealtimeNamespaceId(createGatheringTriggerRealtimeNamespaceId: string | null): this;
    getCreateGatheringTriggerScriptId(): string | null;
    setCreateGatheringTriggerScriptId(createGatheringTriggerScriptId: string | null): this;
    withCreateGatheringTriggerScriptId(createGatheringTriggerScriptId: string | null): this;
    getCompleteMatchmakingTriggerType(): string | null;
    setCompleteMatchmakingTriggerType(completeMatchmakingTriggerType: string | null): this;
    withCompleteMatchmakingTriggerType(completeMatchmakingTriggerType: string | null): this;
    getCompleteMatchmakingTriggerRealtimeNamespaceId(): string | null;
    setCompleteMatchmakingTriggerRealtimeNamespaceId(completeMatchmakingTriggerRealtimeNamespaceId: string | null): this;
    withCompleteMatchmakingTriggerRealtimeNamespaceId(completeMatchmakingTriggerRealtimeNamespaceId: string | null): this;
    getCompleteMatchmakingTriggerScriptId(): string | null;
    setCompleteMatchmakingTriggerScriptId(completeMatchmakingTriggerScriptId: string | null): this;
    withCompleteMatchmakingTriggerScriptId(completeMatchmakingTriggerScriptId: string | null): this;
    getChangeRatingScript(): ScriptSetting | null;
    setChangeRatingScript(changeRatingScript: ScriptSetting | null): this;
    withChangeRatingScript(changeRatingScript: ScriptSetting | null): this;
    getJoinNotification(): NotificationSetting | null;
    setJoinNotification(joinNotification: NotificationSetting | null): this;
    withJoinNotification(joinNotification: NotificationSetting | null): this;
    getLeaveNotification(): NotificationSetting | null;
    setLeaveNotification(leaveNotification: NotificationSetting | null): this;
    withLeaveNotification(leaveNotification: NotificationSetting | null): this;
    getCompleteNotification(): NotificationSetting | null;
    setCompleteNotification(completeNotification: NotificationSetting | null): this;
    withCompleteNotification(completeNotification: NotificationSetting | null): this;
    getLogSetting(): LogSetting | null;
    setLogSetting(logSetting: LogSetting | null): this;
    withLogSetting(logSetting: LogSetting | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): Namespace | null;
    toDict(): {
        [key: string]: any;
    };
}
