import IModel from '../../core/interface/IModel';
export default class SeasonGathering implements IModel {
    private seasonGatheringId;
    private seasonName;
    private season;
    private tier;
    private name;
    private participants;
    private createdAt;
    private revision;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static getSeasonName(grn: string): string | null;
    static getSeason(grn: string): string | null;
    static getTier(grn: string): string | null;
    static getSeasonGatheringName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null, seasonName: string | null, season: string | null, tier: string | null, seasonGatheringName: string | null): string | null;
    getSeasonGatheringId(): string | null;
    setSeasonGatheringId(seasonGatheringId: string | null): this;
    withSeasonGatheringId(seasonGatheringId: string | null): this;
    getSeasonName(): string | null;
    setSeasonName(seasonName: string | null): this;
    withSeasonName(seasonName: string | null): this;
    getSeason(): number | null;
    setSeason(season: number | null): this;
    withSeason(season: number | null): this;
    getTier(): number | null;
    setTier(tier: number | null): this;
    withTier(tier: number | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getParticipants(): string[] | null;
    setParticipants(participants: string[] | null): this;
    withParticipants(participants: string[] | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getRevision(): number | null;
    setRevision(revision: number | null): this;
    withRevision(revision: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): SeasonGathering | null;
    toDict(): {
        [key: string]: any;
    };
}
