import IRequest from '../../core/interface/IRequest';
import * as Gs2Guild from '../model';
export default class CreateGuildByUserIdRequest implements IRequest {
    private requestId;
    private contextStack;
    private namespaceName;
    private userId;
    private guildModelName;
    private displayName;
    private attribute1;
    private attribute2;
    private attribute3;
    private attribute4;
    private attribute5;
    private joinPolicy;
    private customRoles;
    private guildMemberDefaultRole;
    private timeOffsetToken;
    private duplicationAvoider;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getUserId(): string | null;
    setUserId(userId: string | null): this;
    withUserId(userId: string | null): this;
    getGuildModelName(): string | null;
    setGuildModelName(guildModelName: string | null): this;
    withGuildModelName(guildModelName: string | null): this;
    getDisplayName(): string | null;
    setDisplayName(displayName: string | null): this;
    withDisplayName(displayName: string | null): this;
    getAttribute1(): number | null;
    setAttribute1(attribute1: number | null): this;
    withAttribute1(attribute1: number | null): this;
    getAttribute2(): number | null;
    setAttribute2(attribute2: number | null): this;
    withAttribute2(attribute2: number | null): this;
    getAttribute3(): number | null;
    setAttribute3(attribute3: number | null): this;
    withAttribute3(attribute3: number | null): this;
    getAttribute4(): number | null;
    setAttribute4(attribute4: number | null): this;
    withAttribute4(attribute4: number | null): this;
    getAttribute5(): number | null;
    setAttribute5(attribute5: number | null): this;
    withAttribute5(attribute5: number | null): this;
    getJoinPolicy(): string | null;
    setJoinPolicy(joinPolicy: string | null): this;
    withJoinPolicy(joinPolicy: string | null): this;
    getCustomRoles(): Gs2Guild.RoleModel[] | null;
    setCustomRoles(customRoles: Gs2Guild.RoleModel[] | null): this;
    withCustomRoles(customRoles: Gs2Guild.RoleModel[] | null): this;
    getGuildMemberDefaultRole(): string | null;
    setGuildMemberDefaultRole(guildMemberDefaultRole: string | null): this;
    withGuildMemberDefaultRole(guildMemberDefaultRole: string | null): this;
    getTimeOffsetToken(): string | null;
    setTimeOffsetToken(timeOffsetToken: string | null): this;
    withTimeOffsetToken(timeOffsetToken: string | null): this;
    getDuplicationAvoider(): string | null;
    setDuplicationAvoider(duplicationAvoider: string | null): this;
    withDuplicationAvoider(duplicationAvoider: string | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): CreateGuildByUserIdRequest;
    toDict(): {
        [key: string]: any;
    };
}
