import IRequest from '../../core/interface/IRequest';
import * as Gs2Guild from '../model';
export default class CreateNamespaceRequest implements IRequest {
    private requestId;
    private contextStack;
    private name;
    private description;
    private transactionSetting;
    private changeNotification;
    private joinNotification;
    private leaveNotification;
    private changeMemberNotification;
    private receiveRequestNotification;
    private removeRequestNotification;
    private createGuildScript;
    private updateGuildScript;
    private joinGuildScript;
    private receiveJoinRequestScript;
    private leaveGuildScript;
    private changeRoleScript;
    private deleteGuildScript;
    private logSetting;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getTransactionSetting(): Gs2Guild.TransactionSetting | null;
    setTransactionSetting(transactionSetting: Gs2Guild.TransactionSetting | null): this;
    withTransactionSetting(transactionSetting: Gs2Guild.TransactionSetting | null): this;
    getChangeNotification(): Gs2Guild.NotificationSetting | null;
    setChangeNotification(changeNotification: Gs2Guild.NotificationSetting | null): this;
    withChangeNotification(changeNotification: Gs2Guild.NotificationSetting | null): this;
    getJoinNotification(): Gs2Guild.NotificationSetting | null;
    setJoinNotification(joinNotification: Gs2Guild.NotificationSetting | null): this;
    withJoinNotification(joinNotification: Gs2Guild.NotificationSetting | null): this;
    getLeaveNotification(): Gs2Guild.NotificationSetting | null;
    setLeaveNotification(leaveNotification: Gs2Guild.NotificationSetting | null): this;
    withLeaveNotification(leaveNotification: Gs2Guild.NotificationSetting | null): this;
    getChangeMemberNotification(): Gs2Guild.NotificationSetting | null;
    setChangeMemberNotification(changeMemberNotification: Gs2Guild.NotificationSetting | null): this;
    withChangeMemberNotification(changeMemberNotification: Gs2Guild.NotificationSetting | null): this;
    getReceiveRequestNotification(): Gs2Guild.NotificationSetting | null;
    setReceiveRequestNotification(receiveRequestNotification: Gs2Guild.NotificationSetting | null): this;
    withReceiveRequestNotification(receiveRequestNotification: Gs2Guild.NotificationSetting | null): this;
    getRemoveRequestNotification(): Gs2Guild.NotificationSetting | null;
    setRemoveRequestNotification(removeRequestNotification: Gs2Guild.NotificationSetting | null): this;
    withRemoveRequestNotification(removeRequestNotification: Gs2Guild.NotificationSetting | null): this;
    getCreateGuildScript(): Gs2Guild.ScriptSetting | null;
    setCreateGuildScript(createGuildScript: Gs2Guild.ScriptSetting | null): this;
    withCreateGuildScript(createGuildScript: Gs2Guild.ScriptSetting | null): this;
    getUpdateGuildScript(): Gs2Guild.ScriptSetting | null;
    setUpdateGuildScript(updateGuildScript: Gs2Guild.ScriptSetting | null): this;
    withUpdateGuildScript(updateGuildScript: Gs2Guild.ScriptSetting | null): this;
    getJoinGuildScript(): Gs2Guild.ScriptSetting | null;
    setJoinGuildScript(joinGuildScript: Gs2Guild.ScriptSetting | null): this;
    withJoinGuildScript(joinGuildScript: Gs2Guild.ScriptSetting | null): this;
    getReceiveJoinRequestScript(): Gs2Guild.ScriptSetting | null;
    setReceiveJoinRequestScript(receiveJoinRequestScript: Gs2Guild.ScriptSetting | null): this;
    withReceiveJoinRequestScript(receiveJoinRequestScript: Gs2Guild.ScriptSetting | null): this;
    getLeaveGuildScript(): Gs2Guild.ScriptSetting | null;
    setLeaveGuildScript(leaveGuildScript: Gs2Guild.ScriptSetting | null): this;
    withLeaveGuildScript(leaveGuildScript: Gs2Guild.ScriptSetting | null): this;
    getChangeRoleScript(): Gs2Guild.ScriptSetting | null;
    setChangeRoleScript(changeRoleScript: Gs2Guild.ScriptSetting | null): this;
    withChangeRoleScript(changeRoleScript: Gs2Guild.ScriptSetting | null): this;
    getDeleteGuildScript(): Gs2Guild.ScriptSetting | null;
    setDeleteGuildScript(deleteGuildScript: Gs2Guild.ScriptSetting | null): this;
    withDeleteGuildScript(deleteGuildScript: Gs2Guild.ScriptSetting | null): this;
    getLogSetting(): Gs2Guild.LogSetting | null;
    setLogSetting(logSetting: Gs2Guild.LogSetting | null): this;
    withLogSetting(logSetting: Gs2Guild.LogSetting | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): CreateNamespaceRequest;
    toDict(): {
        [key: string]: any;
    };
}
