import IRequest from '../../core/interface/IRequest';
import * as Gs2Guild from '../model';
export default class UpdateNamespaceRequest implements IRequest {
    private requestId;
    private contextStack;
    private namespaceName;
    private description;
    private joinNotification;
    private leaveNotification;
    private changeMemberNotification;
    private receiveRequestNotification;
    private removeRequestNotification;
    private logSetting;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getJoinNotification(): Gs2Guild.NotificationSetting | null;
    setJoinNotification(joinNotification: Gs2Guild.NotificationSetting | null): this;
    withJoinNotification(joinNotification: Gs2Guild.NotificationSetting | null): this;
    getLeaveNotification(): Gs2Guild.NotificationSetting | null;
    setLeaveNotification(leaveNotification: Gs2Guild.NotificationSetting | null): this;
    withLeaveNotification(leaveNotification: Gs2Guild.NotificationSetting | null): this;
    getChangeMemberNotification(): Gs2Guild.NotificationSetting | null;
    setChangeMemberNotification(changeMemberNotification: Gs2Guild.NotificationSetting | null): this;
    withChangeMemberNotification(changeMemberNotification: Gs2Guild.NotificationSetting | null): this;
    getReceiveRequestNotification(): Gs2Guild.NotificationSetting | null;
    setReceiveRequestNotification(receiveRequestNotification: Gs2Guild.NotificationSetting | null): this;
    withReceiveRequestNotification(receiveRequestNotification: Gs2Guild.NotificationSetting | null): this;
    getRemoveRequestNotification(): Gs2Guild.NotificationSetting | null;
    setRemoveRequestNotification(removeRequestNotification: Gs2Guild.NotificationSetting | null): this;
    withRemoveRequestNotification(removeRequestNotification: Gs2Guild.NotificationSetting | null): this;
    getLogSetting(): Gs2Guild.LogSetting | null;
    setLogSetting(logSetting: Gs2Guild.LogSetting | null): this;
    withLogSetting(logSetting: Gs2Guild.LogSetting | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): UpdateNamespaceRequest;
    toDict(): {
        [key: string]: any;
    };
}
