"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DescribeMissionCounterMetricsRequest = exports.GetMatchmakingNamespaceMetricsRequest = exports.DescribeMatchmakingNamespaceMetricsRequest = exports.GetLotteryNamespaceMetricsRequest = exports.DescribeLotteryNamespaceMetricsRequest = exports.GetLotteryLotteryMetricsRequest = exports.DescribeLotteryLotteryMetricsRequest = exports.GetLimitNamespaceMetricsRequest = exports.DescribeLimitNamespaceMetricsRequest = exports.GetLimitLimitModelMetricsRequest = exports.DescribeLimitLimitModelMetricsRequest = exports.DescribeLimitCounterMetricsRequest = exports.GetKeyNamespaceMetricsRequest = exports.DescribeKeyNamespaceMetricsRequest = exports.GetInventoryNamespaceMetricsRequest = exports.DescribeInventoryNamespaceMetricsRequest = exports.DescribeInventoryInventoryMetricsRequest = exports.DescribeInventoryItemSetMetricsRequest = exports.GetInboxNamespaceMetricsRequest = exports.DescribeInboxNamespaceMetricsRequest = exports.GetFriendNamespaceMetricsRequest = exports.DescribeFriendNamespaceMetricsRequest = exports.GetFormationNamespaceMetricsRequest = exports.DescribeFormationNamespaceMetricsRequest = exports.DescribeFormationMoldMetricsRequest = exports.DescribeFormationFormMetricsRequest = exports.GetExperienceNamespaceMetricsRequest = exports.DescribeExperienceNamespaceMetricsRequest = exports.GetExperienceExperienceModelMetricsRequest = exports.DescribeExperienceExperienceModelMetricsRequest = exports.DescribeExperienceStatusMetricsRequest = exports.GetExchangeNamespaceMetricsRequest = exports.DescribeExchangeNamespaceMetricsRequest = exports.GetExchangeRateModelMetricsRequest = exports.DescribeExchangeRateModelMetricsRequest = exports.GetDictionaryNamespaceMetricsRequest = exports.DescribeDictionaryNamespaceMetricsRequest = exports.GetDatastoreNamespaceMetricsRequest = exports.DescribeDatastoreNamespaceMetricsRequest = exports.GetChatNamespaceMetricsRequest = exports.DescribeChatNamespaceMetricsRequest = exports.GetAccountNamespaceMetricsRequest = exports.DescribeAccountNamespaceMetricsRequest = exports.GetGeneralMetricsRequest = exports.GetBillingActivityRequest = exports.DescribeBillingActivitiesRequest = exports.GetCumulativeRequest = exports.GetDistributionRequest = exports.GetServiceVersionRequest = exports.GetChartRequest = void 0;
exports.GetStaminaNamespaceMetricsRequest = exports.DescribeStaminaNamespaceMetricsRequest = exports.GetStaminaStaminaModelMetricsRequest = exports.DescribeStaminaStaminaModelMetricsRequest = exports.GetShowcaseNamespaceMetricsRequest = exports.DescribeShowcaseNamespaceMetricsRequest = exports.GetShowcaseShowcaseMetricsRequest = exports.DescribeShowcaseShowcaseMetricsRequest = exports.GetShowcaseDisplayItemMetricsRequest = exports.DescribeShowcaseDisplayItemMetricsRequest = exports.GetRankingNamespaceMetricsRequest = exports.DescribeRankingNamespaceMetricsRequest = exports.GetRankingCategoryModelMetricsRequest = exports.DescribeRankingCategoryModelMetricsRequest = exports.GetQuestNamespaceMetricsRequest = exports.DescribeQuestNamespaceMetricsRequest = exports.GetQuestQuestGroupModelMetricsRequest = exports.DescribeQuestQuestGroupModelMetricsRequest = exports.GetQuestQuestModelMetricsRequest = exports.DescribeQuestQuestModelMetricsRequest = exports.GetMoneyNamespaceMetricsRequest = exports.DescribeMoneyNamespaceMetricsRequest = exports.DescribeMoneyReceiptMetricsRequest = exports.DescribeMoneyWalletMetricsRequest = exports.GetMissionNamespaceMetricsRequest = exports.DescribeMissionNamespaceMetricsRequest = exports.GetMissionMissionGroupModelMetricsRequest = exports.DescribeMissionMissionGroupModelMetricsRequest = void 0;
var tslib_1 = require("tslib");
/*
Copyright 2016 Game Server Services, Inc. or its affiliates. All Rights
Reserved.

Licensed under the Apache License, Version 2.0 (the "License").
You may not use this file except in compliance with the License.
A copy of the License is located at

 http://www.apache.org/licenses/LICENSE-2.0

or in the "license" file accompanying this file. This file is distributed
on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied. See the License for the specific language governing
permissions and limitations under the License.
 */
var GetChartRequest_1 = tslib_1.__importDefault(require("./GetChartRequest"));
exports.GetChartRequest = GetChartRequest_1.default;
var GetServiceVersionRequest_1 = tslib_1.__importDefault(require("./GetServiceVersionRequest"));
exports.GetServiceVersionRequest = GetServiceVersionRequest_1.default;
var GetDistributionRequest_1 = tslib_1.__importDefault(require("./GetDistributionRequest"));
exports.GetDistributionRequest = GetDistributionRequest_1.default;
var GetCumulativeRequest_1 = tslib_1.__importDefault(require("./GetCumulativeRequest"));
exports.GetCumulativeRequest = GetCumulativeRequest_1.default;
var DescribeBillingActivitiesRequest_1 = tslib_1.__importDefault(require("./DescribeBillingActivitiesRequest"));
exports.DescribeBillingActivitiesRequest = DescribeBillingActivitiesRequest_1.default;
var GetBillingActivityRequest_1 = tslib_1.__importDefault(require("./GetBillingActivityRequest"));
exports.GetBillingActivityRequest = GetBillingActivityRequest_1.default;
var GetGeneralMetricsRequest_1 = tslib_1.__importDefault(require("./GetGeneralMetricsRequest"));
exports.GetGeneralMetricsRequest = GetGeneralMetricsRequest_1.default;
var DescribeAccountNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeAccountNamespaceMetricsRequest"));
exports.DescribeAccountNamespaceMetricsRequest = DescribeAccountNamespaceMetricsRequest_1.default;
var GetAccountNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetAccountNamespaceMetricsRequest"));
exports.GetAccountNamespaceMetricsRequest = GetAccountNamespaceMetricsRequest_1.default;
var DescribeChatNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeChatNamespaceMetricsRequest"));
exports.DescribeChatNamespaceMetricsRequest = DescribeChatNamespaceMetricsRequest_1.default;
var GetChatNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetChatNamespaceMetricsRequest"));
exports.GetChatNamespaceMetricsRequest = GetChatNamespaceMetricsRequest_1.default;
var DescribeDatastoreNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeDatastoreNamespaceMetricsRequest"));
exports.DescribeDatastoreNamespaceMetricsRequest = DescribeDatastoreNamespaceMetricsRequest_1.default;
var GetDatastoreNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetDatastoreNamespaceMetricsRequest"));
exports.GetDatastoreNamespaceMetricsRequest = GetDatastoreNamespaceMetricsRequest_1.default;
var DescribeDictionaryNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeDictionaryNamespaceMetricsRequest"));
exports.DescribeDictionaryNamespaceMetricsRequest = DescribeDictionaryNamespaceMetricsRequest_1.default;
var GetDictionaryNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetDictionaryNamespaceMetricsRequest"));
exports.GetDictionaryNamespaceMetricsRequest = GetDictionaryNamespaceMetricsRequest_1.default;
var DescribeExchangeRateModelMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeExchangeRateModelMetricsRequest"));
exports.DescribeExchangeRateModelMetricsRequest = DescribeExchangeRateModelMetricsRequest_1.default;
var GetExchangeRateModelMetricsRequest_1 = tslib_1.__importDefault(require("./GetExchangeRateModelMetricsRequest"));
exports.GetExchangeRateModelMetricsRequest = GetExchangeRateModelMetricsRequest_1.default;
var DescribeExchangeNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeExchangeNamespaceMetricsRequest"));
exports.DescribeExchangeNamespaceMetricsRequest = DescribeExchangeNamespaceMetricsRequest_1.default;
var GetExchangeNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetExchangeNamespaceMetricsRequest"));
exports.GetExchangeNamespaceMetricsRequest = GetExchangeNamespaceMetricsRequest_1.default;
var DescribeExperienceStatusMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeExperienceStatusMetricsRequest"));
exports.DescribeExperienceStatusMetricsRequest = DescribeExperienceStatusMetricsRequest_1.default;
var DescribeExperienceExperienceModelMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeExperienceExperienceModelMetricsRequest"));
exports.DescribeExperienceExperienceModelMetricsRequest = DescribeExperienceExperienceModelMetricsRequest_1.default;
var GetExperienceExperienceModelMetricsRequest_1 = tslib_1.__importDefault(require("./GetExperienceExperienceModelMetricsRequest"));
exports.GetExperienceExperienceModelMetricsRequest = GetExperienceExperienceModelMetricsRequest_1.default;
var DescribeExperienceNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeExperienceNamespaceMetricsRequest"));
exports.DescribeExperienceNamespaceMetricsRequest = DescribeExperienceNamespaceMetricsRequest_1.default;
var GetExperienceNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetExperienceNamespaceMetricsRequest"));
exports.GetExperienceNamespaceMetricsRequest = GetExperienceNamespaceMetricsRequest_1.default;
var DescribeFormationFormMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeFormationFormMetricsRequest"));
exports.DescribeFormationFormMetricsRequest = DescribeFormationFormMetricsRequest_1.default;
var DescribeFormationMoldMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeFormationMoldMetricsRequest"));
exports.DescribeFormationMoldMetricsRequest = DescribeFormationMoldMetricsRequest_1.default;
var DescribeFormationNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeFormationNamespaceMetricsRequest"));
exports.DescribeFormationNamespaceMetricsRequest = DescribeFormationNamespaceMetricsRequest_1.default;
var GetFormationNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetFormationNamespaceMetricsRequest"));
exports.GetFormationNamespaceMetricsRequest = GetFormationNamespaceMetricsRequest_1.default;
var DescribeFriendNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeFriendNamespaceMetricsRequest"));
exports.DescribeFriendNamespaceMetricsRequest = DescribeFriendNamespaceMetricsRequest_1.default;
var GetFriendNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetFriendNamespaceMetricsRequest"));
exports.GetFriendNamespaceMetricsRequest = GetFriendNamespaceMetricsRequest_1.default;
var DescribeInboxNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeInboxNamespaceMetricsRequest"));
exports.DescribeInboxNamespaceMetricsRequest = DescribeInboxNamespaceMetricsRequest_1.default;
var GetInboxNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetInboxNamespaceMetricsRequest"));
exports.GetInboxNamespaceMetricsRequest = GetInboxNamespaceMetricsRequest_1.default;
var DescribeInventoryItemSetMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeInventoryItemSetMetricsRequest"));
exports.DescribeInventoryItemSetMetricsRequest = DescribeInventoryItemSetMetricsRequest_1.default;
var DescribeInventoryInventoryMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeInventoryInventoryMetricsRequest"));
exports.DescribeInventoryInventoryMetricsRequest = DescribeInventoryInventoryMetricsRequest_1.default;
var DescribeInventoryNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeInventoryNamespaceMetricsRequest"));
exports.DescribeInventoryNamespaceMetricsRequest = DescribeInventoryNamespaceMetricsRequest_1.default;
var GetInventoryNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetInventoryNamespaceMetricsRequest"));
exports.GetInventoryNamespaceMetricsRequest = GetInventoryNamespaceMetricsRequest_1.default;
var DescribeKeyNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeKeyNamespaceMetricsRequest"));
exports.DescribeKeyNamespaceMetricsRequest = DescribeKeyNamespaceMetricsRequest_1.default;
var GetKeyNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetKeyNamespaceMetricsRequest"));
exports.GetKeyNamespaceMetricsRequest = GetKeyNamespaceMetricsRequest_1.default;
var DescribeLimitCounterMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeLimitCounterMetricsRequest"));
exports.DescribeLimitCounterMetricsRequest = DescribeLimitCounterMetricsRequest_1.default;
var DescribeLimitLimitModelMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeLimitLimitModelMetricsRequest"));
exports.DescribeLimitLimitModelMetricsRequest = DescribeLimitLimitModelMetricsRequest_1.default;
var GetLimitLimitModelMetricsRequest_1 = tslib_1.__importDefault(require("./GetLimitLimitModelMetricsRequest"));
exports.GetLimitLimitModelMetricsRequest = GetLimitLimitModelMetricsRequest_1.default;
var DescribeLimitNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeLimitNamespaceMetricsRequest"));
exports.DescribeLimitNamespaceMetricsRequest = DescribeLimitNamespaceMetricsRequest_1.default;
var GetLimitNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetLimitNamespaceMetricsRequest"));
exports.GetLimitNamespaceMetricsRequest = GetLimitNamespaceMetricsRequest_1.default;
var DescribeLotteryLotteryMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeLotteryLotteryMetricsRequest"));
exports.DescribeLotteryLotteryMetricsRequest = DescribeLotteryLotteryMetricsRequest_1.default;
var GetLotteryLotteryMetricsRequest_1 = tslib_1.__importDefault(require("./GetLotteryLotteryMetricsRequest"));
exports.GetLotteryLotteryMetricsRequest = GetLotteryLotteryMetricsRequest_1.default;
var DescribeLotteryNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeLotteryNamespaceMetricsRequest"));
exports.DescribeLotteryNamespaceMetricsRequest = DescribeLotteryNamespaceMetricsRequest_1.default;
var GetLotteryNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetLotteryNamespaceMetricsRequest"));
exports.GetLotteryNamespaceMetricsRequest = GetLotteryNamespaceMetricsRequest_1.default;
var DescribeMatchmakingNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeMatchmakingNamespaceMetricsRequest"));
exports.DescribeMatchmakingNamespaceMetricsRequest = DescribeMatchmakingNamespaceMetricsRequest_1.default;
var GetMatchmakingNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetMatchmakingNamespaceMetricsRequest"));
exports.GetMatchmakingNamespaceMetricsRequest = GetMatchmakingNamespaceMetricsRequest_1.default;
var DescribeMissionCounterMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeMissionCounterMetricsRequest"));
exports.DescribeMissionCounterMetricsRequest = DescribeMissionCounterMetricsRequest_1.default;
var DescribeMissionMissionGroupModelMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeMissionMissionGroupModelMetricsRequest"));
exports.DescribeMissionMissionGroupModelMetricsRequest = DescribeMissionMissionGroupModelMetricsRequest_1.default;
var GetMissionMissionGroupModelMetricsRequest_1 = tslib_1.__importDefault(require("./GetMissionMissionGroupModelMetricsRequest"));
exports.GetMissionMissionGroupModelMetricsRequest = GetMissionMissionGroupModelMetricsRequest_1.default;
var DescribeMissionNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeMissionNamespaceMetricsRequest"));
exports.DescribeMissionNamespaceMetricsRequest = DescribeMissionNamespaceMetricsRequest_1.default;
var GetMissionNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetMissionNamespaceMetricsRequest"));
exports.GetMissionNamespaceMetricsRequest = GetMissionNamespaceMetricsRequest_1.default;
var DescribeMoneyWalletMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeMoneyWalletMetricsRequest"));
exports.DescribeMoneyWalletMetricsRequest = DescribeMoneyWalletMetricsRequest_1.default;
var DescribeMoneyReceiptMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeMoneyReceiptMetricsRequest"));
exports.DescribeMoneyReceiptMetricsRequest = DescribeMoneyReceiptMetricsRequest_1.default;
var DescribeMoneyNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeMoneyNamespaceMetricsRequest"));
exports.DescribeMoneyNamespaceMetricsRequest = DescribeMoneyNamespaceMetricsRequest_1.default;
var GetMoneyNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetMoneyNamespaceMetricsRequest"));
exports.GetMoneyNamespaceMetricsRequest = GetMoneyNamespaceMetricsRequest_1.default;
var DescribeQuestQuestModelMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeQuestQuestModelMetricsRequest"));
exports.DescribeQuestQuestModelMetricsRequest = DescribeQuestQuestModelMetricsRequest_1.default;
var GetQuestQuestModelMetricsRequest_1 = tslib_1.__importDefault(require("./GetQuestQuestModelMetricsRequest"));
exports.GetQuestQuestModelMetricsRequest = GetQuestQuestModelMetricsRequest_1.default;
var DescribeQuestQuestGroupModelMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeQuestQuestGroupModelMetricsRequest"));
exports.DescribeQuestQuestGroupModelMetricsRequest = DescribeQuestQuestGroupModelMetricsRequest_1.default;
var GetQuestQuestGroupModelMetricsRequest_1 = tslib_1.__importDefault(require("./GetQuestQuestGroupModelMetricsRequest"));
exports.GetQuestQuestGroupModelMetricsRequest = GetQuestQuestGroupModelMetricsRequest_1.default;
var DescribeQuestNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeQuestNamespaceMetricsRequest"));
exports.DescribeQuestNamespaceMetricsRequest = DescribeQuestNamespaceMetricsRequest_1.default;
var GetQuestNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetQuestNamespaceMetricsRequest"));
exports.GetQuestNamespaceMetricsRequest = GetQuestNamespaceMetricsRequest_1.default;
var DescribeRankingCategoryModelMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeRankingCategoryModelMetricsRequest"));
exports.DescribeRankingCategoryModelMetricsRequest = DescribeRankingCategoryModelMetricsRequest_1.default;
var GetRankingCategoryModelMetricsRequest_1 = tslib_1.__importDefault(require("./GetRankingCategoryModelMetricsRequest"));
exports.GetRankingCategoryModelMetricsRequest = GetRankingCategoryModelMetricsRequest_1.default;
var DescribeRankingNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeRankingNamespaceMetricsRequest"));
exports.DescribeRankingNamespaceMetricsRequest = DescribeRankingNamespaceMetricsRequest_1.default;
var GetRankingNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetRankingNamespaceMetricsRequest"));
exports.GetRankingNamespaceMetricsRequest = GetRankingNamespaceMetricsRequest_1.default;
var DescribeShowcaseDisplayItemMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeShowcaseDisplayItemMetricsRequest"));
exports.DescribeShowcaseDisplayItemMetricsRequest = DescribeShowcaseDisplayItemMetricsRequest_1.default;
var GetShowcaseDisplayItemMetricsRequest_1 = tslib_1.__importDefault(require("./GetShowcaseDisplayItemMetricsRequest"));
exports.GetShowcaseDisplayItemMetricsRequest = GetShowcaseDisplayItemMetricsRequest_1.default;
var DescribeShowcaseShowcaseMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeShowcaseShowcaseMetricsRequest"));
exports.DescribeShowcaseShowcaseMetricsRequest = DescribeShowcaseShowcaseMetricsRequest_1.default;
var GetShowcaseShowcaseMetricsRequest_1 = tslib_1.__importDefault(require("./GetShowcaseShowcaseMetricsRequest"));
exports.GetShowcaseShowcaseMetricsRequest = GetShowcaseShowcaseMetricsRequest_1.default;
var DescribeShowcaseNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeShowcaseNamespaceMetricsRequest"));
exports.DescribeShowcaseNamespaceMetricsRequest = DescribeShowcaseNamespaceMetricsRequest_1.default;
var GetShowcaseNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetShowcaseNamespaceMetricsRequest"));
exports.GetShowcaseNamespaceMetricsRequest = GetShowcaseNamespaceMetricsRequest_1.default;
var DescribeStaminaStaminaModelMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeStaminaStaminaModelMetricsRequest"));
exports.DescribeStaminaStaminaModelMetricsRequest = DescribeStaminaStaminaModelMetricsRequest_1.default;
var GetStaminaStaminaModelMetricsRequest_1 = tslib_1.__importDefault(require("./GetStaminaStaminaModelMetricsRequest"));
exports.GetStaminaStaminaModelMetricsRequest = GetStaminaStaminaModelMetricsRequest_1.default;
var DescribeStaminaNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./DescribeStaminaNamespaceMetricsRequest"));
exports.DescribeStaminaNamespaceMetricsRequest = DescribeStaminaNamespaceMetricsRequest_1.default;
var GetStaminaNamespaceMetricsRequest_1 = tslib_1.__importDefault(require("./GetStaminaNamespaceMetricsRequest"));
exports.GetStaminaNamespaceMetricsRequest = GetStaminaNamespaceMetricsRequest_1.default;
//# sourceMappingURL=index.js.map