import IRequest from '../../core/interface/IRequest';
import * as Gs2Showcase from '../model';
export default class UpdateRandomShowcaseMasterRequest implements IRequest {
    private requestId;
    private contextStack;
    private namespaceName;
    private showcaseName;
    private description;
    private metadata;
    private maximumNumberOfChoice;
    private displayItems;
    private baseTimestamp;
    private resetIntervalHours;
    private salesPeriodEventId;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getShowcaseName(): string | null;
    setShowcaseName(showcaseName: string | null): this;
    withShowcaseName(showcaseName: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getMaximumNumberOfChoice(): number | null;
    setMaximumNumberOfChoice(maximumNumberOfChoice: number | null): this;
    withMaximumNumberOfChoice(maximumNumberOfChoice: number | null): this;
    getDisplayItems(): Gs2Showcase.RandomDisplayItemModel[] | null;
    setDisplayItems(displayItems: Gs2Showcase.RandomDisplayItemModel[] | null): this;
    withDisplayItems(displayItems: Gs2Showcase.RandomDisplayItemModel[] | null): this;
    getBaseTimestamp(): number | null;
    setBaseTimestamp(baseTimestamp: number | null): this;
    withBaseTimestamp(baseTimestamp: number | null): this;
    getResetIntervalHours(): number | null;
    setResetIntervalHours(resetIntervalHours: number | null): this;
    withResetIntervalHours(resetIntervalHours: number | null): this;
    getSalesPeriodEventId(): string | null;
    setSalesPeriodEventId(salesPeriodEventId: string | null): this;
    withSalesPeriodEventId(salesPeriodEventId: string | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): UpdateRandomShowcaseMasterRequest;
    toDict(): {
        [key: string]: any;
    };
}
