import IRequest from '../../core/interface/IRequest';
import * as Gs2Ranking2 from '../model';
export default class UpdateGlobalRankingModelMasterRequest implements IRequest {
    private requestId;
    private contextStack;
    private namespaceName;
    private rankingName;
    private description;
    private metadata;
    private minimumValue;
    private maximumValue;
    private sum;
    private orderDirection;
    private rankingRewards;
    private entryPeriodEventId;
    private accessPeriodEventId;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getRankingName(): string | null;
    setRankingName(rankingName: string | null): this;
    withRankingName(rankingName: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getMinimumValue(): number | null;
    setMinimumValue(minimumValue: number | null): this;
    withMinimumValue(minimumValue: number | null): this;
    getMaximumValue(): number | null;
    setMaximumValue(maximumValue: number | null): this;
    withMaximumValue(maximumValue: number | null): this;
    getSum(): boolean | null;
    setSum(sum: boolean | null): this;
    withSum(sum: boolean | null): this;
    getOrderDirection(): string | null;
    setOrderDirection(orderDirection: string | null): this;
    withOrderDirection(orderDirection: string | null): this;
    getRankingRewards(): Gs2Ranking2.RankingReward[] | null;
    setRankingRewards(rankingRewards: Gs2Ranking2.RankingReward[] | null): this;
    withRankingRewards(rankingRewards: Gs2Ranking2.RankingReward[] | null): this;
    getEntryPeriodEventId(): string | null;
    setEntryPeriodEventId(entryPeriodEventId: string | null): this;
    withEntryPeriodEventId(entryPeriodEventId: string | null): this;
    getAccessPeriodEventId(): string | null;
    setAccessPeriodEventId(accessPeriodEventId: string | null): this;
    withAccessPeriodEventId(accessPeriodEventId: string | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): UpdateGlobalRankingModelMasterRequest;
    toDict(): {
        [key: string]: any;
    };
}
