import IRequest from '../../core/interface/IRequest';
import * as Gs2LoginReward from '../model';
export default class CreateBonusModelMasterRequest implements IRequest {
    private requestId;
    private contextStack;
    private namespaceName;
    private name;
    private description;
    private metadata;
    private mode;
    private periodEventId;
    private resetHour;
    private repeat;
    private rewards;
    private missedReceiveRelief;
    private missedReceiveReliefVerifyActions;
    private missedReceiveReliefConsumeActions;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getMode(): string | null;
    setMode(mode: string | null): this;
    withMode(mode: string | null): this;
    getPeriodEventId(): string | null;
    setPeriodEventId(periodEventId: string | null): this;
    withPeriodEventId(periodEventId: string | null): this;
    getResetHour(): number | null;
    setResetHour(resetHour: number | null): this;
    withResetHour(resetHour: number | null): this;
    getRepeat(): string | null;
    setRepeat(repeat: string | null): this;
    withRepeat(repeat: string | null): this;
    getRewards(): Gs2LoginReward.Reward[] | null;
    setRewards(rewards: Gs2LoginReward.Reward[] | null): this;
    withRewards(rewards: Gs2LoginReward.Reward[] | null): this;
    getMissedReceiveRelief(): string | null;
    setMissedReceiveRelief(missedReceiveRelief: string | null): this;
    withMissedReceiveRelief(missedReceiveRelief: string | null): this;
    getMissedReceiveReliefVerifyActions(): Gs2LoginReward.VerifyAction[] | null;
    setMissedReceiveReliefVerifyActions(missedReceiveReliefVerifyActions: Gs2LoginReward.VerifyAction[] | null): this;
    withMissedReceiveReliefVerifyActions(missedReceiveReliefVerifyActions: Gs2LoginReward.VerifyAction[] | null): this;
    getMissedReceiveReliefConsumeActions(): Gs2LoginReward.ConsumeAction[] | null;
    setMissedReceiveReliefConsumeActions(missedReceiveReliefConsumeActions: Gs2LoginReward.ConsumeAction[] | null): this;
    withMissedReceiveReliefConsumeActions(missedReceiveReliefConsumeActions: Gs2LoginReward.ConsumeAction[] | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): CreateBonusModelMasterRequest;
    toDict(): {
        [key: string]: any;
    };
}
