import IModel from '../../core/interface/IModel';
export default class MissionGroupModelMaster implements IModel {
    private missionGroupId;
    private name;
    private metadata;
    private description;
    private resetType;
    private resetDayOfMonth;
    private resetDayOfWeek;
    private resetHour;
    private anchorTimestamp;
    private days;
    private completeNotificationNamespaceId;
    private createdAt;
    private updatedAt;
    private revision;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static getMissionGroupName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null, missionGroupName: string | null): string | null;
    getMissionGroupId(): string | null;
    setMissionGroupId(missionGroupId: string | null): this;
    withMissionGroupId(missionGroupId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getResetType(): string | null;
    setResetType(resetType: string | null): this;
    withResetType(resetType: string | null): this;
    getResetDayOfMonth(): number | null;
    setResetDayOfMonth(resetDayOfMonth: number | null): this;
    withResetDayOfMonth(resetDayOfMonth: number | null): this;
    getResetDayOfWeek(): string | null;
    setResetDayOfWeek(resetDayOfWeek: string | null): this;
    withResetDayOfWeek(resetDayOfWeek: string | null): this;
    getResetHour(): number | null;
    setResetHour(resetHour: number | null): this;
    withResetHour(resetHour: number | null): this;
    getAnchorTimestamp(): number | null;
    setAnchorTimestamp(anchorTimestamp: number | null): this;
    withAnchorTimestamp(anchorTimestamp: number | null): this;
    getDays(): number | null;
    setDays(days: number | null): this;
    withDays(days: number | null): this;
    getCompleteNotificationNamespaceId(): string | null;
    setCompleteNotificationNamespaceId(completeNotificationNamespaceId: string | null): this;
    withCompleteNotificationNamespaceId(completeNotificationNamespaceId: string | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    getRevision(): number | null;
    setRevision(revision: number | null): this;
    withRevision(revision: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): MissionGroupModelMaster | null;
    toDict(): {
        [key: string]: any;
    };
}
