import IRequest from '../../core/interface/IRequest';
import * as Gs2Money2 from '../model';
export default class CreateNamespaceRequest implements IRequest {
    private requestId;
    private contextStack;
    private name;
    private currencyUsagePriority;
    private description;
    private sharedFreeCurrency;
    private platformSetting;
    private depositBalanceScript;
    private withdrawBalanceScript;
    private subscribeScript;
    private renewScript;
    private unsubscribeScript;
    private takeOverScript;
    private changeSubscriptionStatusNotification;
    private logSetting;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getCurrencyUsagePriority(): string | null;
    setCurrencyUsagePriority(currencyUsagePriority: string | null): this;
    withCurrencyUsagePriority(currencyUsagePriority: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getSharedFreeCurrency(): boolean | null;
    setSharedFreeCurrency(sharedFreeCurrency: boolean | null): this;
    withSharedFreeCurrency(sharedFreeCurrency: boolean | null): this;
    getPlatformSetting(): Gs2Money2.PlatformSetting | null;
    setPlatformSetting(platformSetting: Gs2Money2.PlatformSetting | null): this;
    withPlatformSetting(platformSetting: Gs2Money2.PlatformSetting | null): this;
    getDepositBalanceScript(): Gs2Money2.ScriptSetting | null;
    setDepositBalanceScript(depositBalanceScript: Gs2Money2.ScriptSetting | null): this;
    withDepositBalanceScript(depositBalanceScript: Gs2Money2.ScriptSetting | null): this;
    getWithdrawBalanceScript(): Gs2Money2.ScriptSetting | null;
    setWithdrawBalanceScript(withdrawBalanceScript: Gs2Money2.ScriptSetting | null): this;
    withWithdrawBalanceScript(withdrawBalanceScript: Gs2Money2.ScriptSetting | null): this;
    getSubscribeScript(): string | null;
    setSubscribeScript(subscribeScript: string | null): this;
    withSubscribeScript(subscribeScript: string | null): this;
    getRenewScript(): string | null;
    setRenewScript(renewScript: string | null): this;
    withRenewScript(renewScript: string | null): this;
    getUnsubscribeScript(): string | null;
    setUnsubscribeScript(unsubscribeScript: string | null): this;
    withUnsubscribeScript(unsubscribeScript: string | null): this;
    getTakeOverScript(): Gs2Money2.ScriptSetting | null;
    setTakeOverScript(takeOverScript: Gs2Money2.ScriptSetting | null): this;
    withTakeOverScript(takeOverScript: Gs2Money2.ScriptSetting | null): this;
    getChangeSubscriptionStatusNotification(): Gs2Money2.NotificationSetting | null;
    setChangeSubscriptionStatusNotification(changeSubscriptionStatusNotification: Gs2Money2.NotificationSetting | null): this;
    withChangeSubscriptionStatusNotification(changeSubscriptionStatusNotification: Gs2Money2.NotificationSetting | null): this;
    getLogSetting(): Gs2Money2.LogSetting | null;
    setLogSetting(logSetting: Gs2Money2.LogSetting | null): this;
    withLogSetting(logSetting: Gs2Money2.LogSetting | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): CreateNamespaceRequest;
    toDict(): {
        [key: string]: any;
    };
}
