import IRequest from '../../core/interface/IRequest';
import * as Gs2Money2 from '../model';
export default class UpdateStoreSubscriptionContentModelMasterRequest implements IRequest {
    private requestId;
    private contextStack;
    private namespaceName;
    private contentName;
    private description;
    private metadata;
    private scheduleNamespaceId;
    private triggerName;
    private appleAppStore;
    private googlePlay;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getContentName(): string | null;
    setContentName(contentName: string | null): this;
    withContentName(contentName: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getScheduleNamespaceId(): string | null;
    setScheduleNamespaceId(scheduleNamespaceId: string | null): this;
    withScheduleNamespaceId(scheduleNamespaceId: string | null): this;
    getTriggerName(): string | null;
    setTriggerName(triggerName: string | null): this;
    withTriggerName(triggerName: string | null): this;
    getAppleAppStore(): Gs2Money2.AppleAppStoreSubscriptionContent | null;
    setAppleAppStore(appleAppStore: Gs2Money2.AppleAppStoreSubscriptionContent | null): this;
    withAppleAppStore(appleAppStore: Gs2Money2.AppleAppStoreSubscriptionContent | null): this;
    getGooglePlay(): Gs2Money2.GooglePlaySubscriptionContent | null;
    setGooglePlay(googlePlay: Gs2Money2.GooglePlaySubscriptionContent | null): this;
    withGooglePlay(googlePlay: Gs2Money2.GooglePlaySubscriptionContent | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): UpdateStoreSubscriptionContentModelMasterRequest;
    toDict(): {
        [key: string]: any;
    };
}
