import IModel from '../../core/interface/IModel';
import ConsumeAction from './ConsumeAction';
import AcquireAction from './AcquireAction';
export default class RateModelMaster implements IModel {
    private rateModelId;
    private name;
    private description;
    private metadata;
    private consumeActions;
    private timingType;
    private lockTime;
    private enableSkip;
    private skipConsumeActions;
    private acquireActions;
    private createdAt;
    private updatedAt;
    getRateModelId(): string | null;
    setRateModelId(rateModelId: string | null): this;
    withRateModelId(rateModelId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getConsumeActions(): ConsumeAction[] | null;
    setConsumeActions(consumeActions: ConsumeAction[] | null): this;
    withConsumeActions(consumeActions: ConsumeAction[] | null): this;
    getTimingType(): string | null;
    setTimingType(timingType: string | null): this;
    withTimingType(timingType: string | null): this;
    getLockTime(): number | null;
    setLockTime(lockTime: number | null): this;
    withLockTime(lockTime: number | null): this;
    getEnableSkip(): boolean | null;
    setEnableSkip(enableSkip: boolean | null): this;
    withEnableSkip(enableSkip: boolean | null): this;
    getSkipConsumeActions(): ConsumeAction[] | null;
    setSkipConsumeActions(skipConsumeActions: ConsumeAction[] | null): this;
    withSkipConsumeActions(skipConsumeActions: ConsumeAction[] | null): this;
    getAcquireActions(): AcquireAction[] | null;
    setAcquireActions(acquireActions: AcquireAction[] | null): this;
    withAcquireActions(acquireActions: AcquireAction[] | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): RateModelMaster | null;
    toDict(): {
        [key: string]: any;
    };
}
