import IRequest from '../../core/interface/IRequest';
export default class CreateStaminaModelMasterRequest implements IRequest {
    private requestId;
    private contextStack;
    private namespaceName;
    private name;
    private description;
    private metadata;
    private recoverIntervalMinutes;
    private recoverValue;
    private initialCapacity;
    private isOverflow;
    private maxCapacity;
    private maxStaminaTableName;
    private recoverIntervalTableName;
    private recoverValueTableName;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getRecoverIntervalMinutes(): number | null;
    setRecoverIntervalMinutes(recoverIntervalMinutes: number | null): this;
    withRecoverIntervalMinutes(recoverIntervalMinutes: number | null): this;
    getRecoverValue(): number | null;
    setRecoverValue(recoverValue: number | null): this;
    withRecoverValue(recoverValue: number | null): this;
    getInitialCapacity(): number | null;
    setInitialCapacity(initialCapacity: number | null): this;
    withInitialCapacity(initialCapacity: number | null): this;
    getIsOverflow(): boolean | null;
    setIsOverflow(isOverflow: boolean | null): this;
    withIsOverflow(isOverflow: boolean | null): this;
    getMaxCapacity(): number | null;
    setMaxCapacity(maxCapacity: number | null): this;
    withMaxCapacity(maxCapacity: number | null): this;
    getMaxStaminaTableName(): string | null;
    setMaxStaminaTableName(maxStaminaTableName: string | null): this;
    withMaxStaminaTableName(maxStaminaTableName: string | null): this;
    getRecoverIntervalTableName(): string | null;
    setRecoverIntervalTableName(recoverIntervalTableName: string | null): this;
    withRecoverIntervalTableName(recoverIntervalTableName: string | null): this;
    getRecoverValueTableName(): string | null;
    setRecoverValueTableName(recoverValueTableName: string | null): this;
    withRecoverValueTableName(recoverValueTableName: string | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): CreateStaminaModelMasterRequest;
    toDict(): {
        [key: string]: any;
    };
}
