import IModel from '../../core/interface/IModel';
import AdMob from './AdMob';
import UnityAd from './UnityAd';
import AppLovinMax from './AppLovinMax';
import NotificationSetting from './NotificationSetting';
import LogSetting from './LogSetting';
export default class Namespace implements IModel {
    private namespaceId;
    private name;
    private description;
    private admob;
    private unityAd;
    private appLovinMaxes;
    private changePointNotification;
    private logSetting;
    private createdAt;
    private updatedAt;
    private revision;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null): string | null;
    getNamespaceId(): string | null;
    setNamespaceId(namespaceId: string | null): this;
    withNamespaceId(namespaceId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getAdmob(): AdMob | null;
    setAdmob(admob: AdMob | null): this;
    withAdmob(admob: AdMob | null): this;
    getUnityAd(): UnityAd | null;
    setUnityAd(unityAd: UnityAd | null): this;
    withUnityAd(unityAd: UnityAd | null): this;
    getAppLovinMaxes(): AppLovinMax[] | null;
    setAppLovinMaxes(appLovinMaxes: AppLovinMax[] | null): this;
    withAppLovinMaxes(appLovinMaxes: AppLovinMax[] | null): this;
    getChangePointNotification(): NotificationSetting | null;
    setChangePointNotification(changePointNotification: NotificationSetting | null): this;
    withChangePointNotification(changePointNotification: NotificationSetting | null): this;
    getLogSetting(): LogSetting | null;
    setLogSetting(logSetting: LogSetting | null): this;
    withLogSetting(logSetting: LogSetting | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    getRevision(): number | null;
    setRevision(revision: number | null): this;
    withRevision(revision: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): Namespace | null;
    toDict(): {
        [key: string]: any;
    };
}
