import IModel from '../../core/interface/IModel';
import * as Gs2AdReward from '../../adReward/model';
export default class Namespace implements IModel {
    private namespaceId;
    private name;
    private description;
    private admob;
    private unityAd;
    private appLovinMaxes;
    private acquirePointScript;
    private consumePointScript;
    private changePointNotification;
    private logSetting;
    private createdAt;
    private updatedAt;
    private revision;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null): string | null;
    getNamespaceId(): string | null;
    setNamespaceId(namespaceId: string | null): this;
    withNamespaceId(namespaceId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getAdmob(): Gs2AdReward.AdMob | null;
    setAdmob(admob: Gs2AdReward.AdMob | null): this;
    withAdmob(admob: Gs2AdReward.AdMob | null): this;
    getUnityAd(): Gs2AdReward.UnityAd | null;
    setUnityAd(unityAd: Gs2AdReward.UnityAd | null): this;
    withUnityAd(unityAd: Gs2AdReward.UnityAd | null): this;
    getAppLovinMaxes(): Gs2AdReward.AppLovinMax[] | null;
    setAppLovinMaxes(appLovinMaxes: Gs2AdReward.AppLovinMax[] | null): this;
    withAppLovinMaxes(appLovinMaxes: Gs2AdReward.AppLovinMax[] | null): this;
    getAcquirePointScript(): Gs2AdReward.ScriptSetting | null;
    setAcquirePointScript(acquirePointScript: Gs2AdReward.ScriptSetting | null): this;
    withAcquirePointScript(acquirePointScript: Gs2AdReward.ScriptSetting | null): this;
    getConsumePointScript(): Gs2AdReward.ScriptSetting | null;
    setConsumePointScript(consumePointScript: Gs2AdReward.ScriptSetting | null): this;
    withConsumePointScript(consumePointScript: Gs2AdReward.ScriptSetting | null): this;
    getChangePointNotification(): Gs2AdReward.NotificationSetting | null;
    setChangePointNotification(changePointNotification: Gs2AdReward.NotificationSetting | null): this;
    withChangePointNotification(changePointNotification: Gs2AdReward.NotificationSetting | null): this;
    getLogSetting(): Gs2AdReward.LogSetting | null;
    setLogSetting(logSetting: Gs2AdReward.LogSetting | null): this;
    withLogSetting(logSetting: Gs2AdReward.LogSetting | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    getRevision(): number | null;
    setRevision(revision: number | null): this;
    withRevision(revision: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): Namespace | null;
    toDict(): {
        [key: string]: any;
    };
}
