import IModel from '../../core/interface/IModel';
import * as Gs2Ranking2 from '../../ranking2/model';
export default class ClusterRankingModelMaster implements IModel {
    private clusterRankingModelId;
    private name;
    private description;
    private metadata;
    private clusterType;
    private minimumValue;
    private maximumValue;
    private sum;
    private scoreTtlDays;
    private orderDirection;
    private entryPeriodEventId;
    private rankingRewards;
    private accessPeriodEventId;
    private rewardCalculationIndex;
    private createdAt;
    private updatedAt;
    private revision;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static getRankingName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null, rankingName: string | null): string | null;
    getClusterRankingModelId(): string | null;
    setClusterRankingModelId(clusterRankingModelId: string | null): this;
    withClusterRankingModelId(clusterRankingModelId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getClusterType(): string | null;
    setClusterType(clusterType: string | null): this;
    withClusterType(clusterType: string | null): this;
    getMinimumValue(): number | null;
    setMinimumValue(minimumValue: number | null): this;
    withMinimumValue(minimumValue: number | null): this;
    getMaximumValue(): number | null;
    setMaximumValue(maximumValue: number | null): this;
    withMaximumValue(maximumValue: number | null): this;
    getSum(): boolean | null;
    setSum(sum: boolean | null): this;
    withSum(sum: boolean | null): this;
    getScoreTtlDays(): number | null;
    setScoreTtlDays(scoreTtlDays: number | null): this;
    withScoreTtlDays(scoreTtlDays: number | null): this;
    getOrderDirection(): string | null;
    setOrderDirection(orderDirection: string | null): this;
    withOrderDirection(orderDirection: string | null): this;
    getEntryPeriodEventId(): string | null;
    setEntryPeriodEventId(entryPeriodEventId: string | null): this;
    withEntryPeriodEventId(entryPeriodEventId: string | null): this;
    getRankingRewards(): Gs2Ranking2.RankingReward[] | null;
    setRankingRewards(rankingRewards: Gs2Ranking2.RankingReward[] | null): this;
    withRankingRewards(rankingRewards: Gs2Ranking2.RankingReward[] | null): this;
    getAccessPeriodEventId(): string | null;
    setAccessPeriodEventId(accessPeriodEventId: string | null): this;
    withAccessPeriodEventId(accessPeriodEventId: string | null): this;
    getRewardCalculationIndex(): string | null;
    setRewardCalculationIndex(rewardCalculationIndex: string | null): this;
    withRewardCalculationIndex(rewardCalculationIndex: string | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    getRevision(): number | null;
    setRevision(revision: number | null): this;
    withRevision(revision: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): ClusterRankingModelMaster | null;
    toDict(): {
        [key: string]: any;
    };
}
