/*
Copyright 2016 Game Server Services, Inc. or its affiliates. All Rights
Reserved.

Licensed under the Apache License, Version 2.0 (the "License").
You may not use this file except in compliance with the License.
A copy of the License is located at

 http://www.apache.org/licenses/LICENSE-2.0

or in the "license" file accompanying this file. This file is distributed
on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied. See the License for the specific language governing
permissions and limitations under the License.
 */

import {
  Namespace,
  LotteryModelMaster,
  PrizeTableMaster,
  Box,
  LotteryModel,
  PrizeTable,
  Probability,
  CurrentLotteryMaster,
  ResponseCache,
  GitHubCheckoutSetting,
  LogSetting,
  Prize,
  AcquireAction,
  DrawnPrize,
  BoxItem,
  BoxItems,
  Config,
} from './model';
import {
  DescribeNamespacesRequest,
  CreateNamespaceRequest,
  GetNamespaceStatusRequest,
  GetNamespaceRequest,
  UpdateNamespaceRequest,
  DeleteNamespaceRequest,
  DescribeLotteryModelMastersRequest,
  CreateLotteryModelMasterRequest,
  GetLotteryModelMasterRequest,
  UpdateLotteryModelMasterRequest,
  DeleteLotteryModelMasterRequest,
  DescribePrizeTableMastersRequest,
  CreatePrizeTableMasterRequest,
  GetPrizeTableMasterRequest,
  UpdatePrizeTableMasterRequest,
  DeletePrizeTableMasterRequest,
  DescribeBoxesRequest,
  DescribeBoxesByUserIdRequest,
  GetBoxRequest,
  GetBoxByUserIdRequest,
  GetRawBoxByUserIdRequest,
  ResetBoxRequest,
  ResetBoxByUserIdRequest,
  DescribeLotteryModelsRequest,
  GetLotteryModelRequest,
  DescribePrizeTablesRequest,
  GetPrizeTableRequest,
  ExportMasterRequest,
  GetCurrentLotteryMasterRequest,
  UpdateCurrentLotteryMasterRequest,
  UpdateCurrentLotteryMasterFromGitHubRequest,
} from './request';
import {
  DescribeNamespacesResult,
  CreateNamespaceResult,
  GetNamespaceStatusResult,
  GetNamespaceResult,
  UpdateNamespaceResult,
  DeleteNamespaceResult,
  DescribeLotteryModelMastersResult,
  CreateLotteryModelMasterResult,
  GetLotteryModelMasterResult,
  UpdateLotteryModelMasterResult,
  DeleteLotteryModelMasterResult,
  DescribePrizeTableMastersResult,
  CreatePrizeTableMasterResult,
  GetPrizeTableMasterResult,
  UpdatePrizeTableMasterResult,
  DeletePrizeTableMasterResult,
  DescribeBoxesResult,
  DescribeBoxesByUserIdResult,
  GetBoxResult,
  GetBoxByUserIdResult,
  GetRawBoxByUserIdResult,
  ResetBoxResult,
  ResetBoxByUserIdResult,
  DescribeLotteryModelsResult,
  GetLotteryModelResult,
  DescribePrizeTablesResult,
  GetPrizeTableResult,
  ExportMasterResult,
  GetCurrentLotteryMasterResult,
  UpdateCurrentLotteryMasterResult,
  UpdateCurrentLotteryMasterFromGitHubResult,
} from './result';
import { Gs2LotteryRestClient } from './rest';

export default {
  Namespace,
  LotteryModelMaster,
  PrizeTableMaster,
  Box,
  LotteryModel,
  PrizeTable,
  Probability,
  CurrentLotteryMaster,
  ResponseCache,
  GitHubCheckoutSetting,
  LogSetting,
  Prize,
  AcquireAction,
  DrawnPrize,
  BoxItem,
  BoxItems,
  Config,
  DescribeNamespacesRequest,
  DescribeNamespacesResult,
  CreateNamespaceRequest,
  CreateNamespaceResult,
  GetNamespaceStatusRequest,
  GetNamespaceStatusResult,
  GetNamespaceRequest,
  GetNamespaceResult,
  UpdateNamespaceRequest,
  UpdateNamespaceResult,
  DeleteNamespaceRequest,
  DeleteNamespaceResult,
  DescribeLotteryModelMastersRequest,
  DescribeLotteryModelMastersResult,
  CreateLotteryModelMasterRequest,
  CreateLotteryModelMasterResult,
  GetLotteryModelMasterRequest,
  GetLotteryModelMasterResult,
  UpdateLotteryModelMasterRequest,
  UpdateLotteryModelMasterResult,
  DeleteLotteryModelMasterRequest,
  DeleteLotteryModelMasterResult,
  DescribePrizeTableMastersRequest,
  DescribePrizeTableMastersResult,
  CreatePrizeTableMasterRequest,
  CreatePrizeTableMasterResult,
  GetPrizeTableMasterRequest,
  GetPrizeTableMasterResult,
  UpdatePrizeTableMasterRequest,
  UpdatePrizeTableMasterResult,
  DeletePrizeTableMasterRequest,
  DeletePrizeTableMasterResult,
  DescribeBoxesRequest,
  DescribeBoxesResult,
  DescribeBoxesByUserIdRequest,
  DescribeBoxesByUserIdResult,
  GetBoxRequest,
  GetBoxResult,
  GetBoxByUserIdRequest,
  GetBoxByUserIdResult,
  GetRawBoxByUserIdRequest,
  GetRawBoxByUserIdResult,
  ResetBoxRequest,
  ResetBoxResult,
  ResetBoxByUserIdRequest,
  ResetBoxByUserIdResult,
  DescribeLotteryModelsRequest,
  DescribeLotteryModelsResult,
  GetLotteryModelRequest,
  GetLotteryModelResult,
  DescribePrizeTablesRequest,
  DescribePrizeTablesResult,
  GetPrizeTableRequest,
  GetPrizeTableResult,
  ExportMasterRequest,
  ExportMasterResult,
  GetCurrentLotteryMasterRequest,
  GetCurrentLotteryMasterResult,
  UpdateCurrentLotteryMasterRequest,
  UpdateCurrentLotteryMasterResult,
  UpdateCurrentLotteryMasterFromGitHubRequest,
  UpdateCurrentLotteryMasterFromGitHubResult,
  Gs2LotteryRestClient,
};
