import IModel from '../../core/interface/IModel';
import * as Gs2Version from '../../version/model';
export default class Namespace implements IModel {
    private namespaceId;
    private name;
    private description;
    private assumeUserId;
    private acceptVersionScript;
    private checkVersionTriggerScriptId;
    private logSetting;
    private createdAt;
    private updatedAt;
    private revision;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null): string | null;
    getNamespaceId(): string | null;
    setNamespaceId(namespaceId: string | null): this;
    withNamespaceId(namespaceId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getAssumeUserId(): string | null;
    setAssumeUserId(assumeUserId: string | null): this;
    withAssumeUserId(assumeUserId: string | null): this;
    getAcceptVersionScript(): Gs2Version.ScriptSetting | null;
    setAcceptVersionScript(acceptVersionScript: Gs2Version.ScriptSetting | null): this;
    withAcceptVersionScript(acceptVersionScript: Gs2Version.ScriptSetting | null): this;
    getCheckVersionTriggerScriptId(): string | null;
    setCheckVersionTriggerScriptId(checkVersionTriggerScriptId: string | null): this;
    withCheckVersionTriggerScriptId(checkVersionTriggerScriptId: string | null): this;
    getLogSetting(): Gs2Version.LogSetting | null;
    setLogSetting(logSetting: Gs2Version.LogSetting | null): this;
    withLogSetting(logSetting: Gs2Version.LogSetting | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    getRevision(): number | null;
    setRevision(revision: number | null): this;
    withRevision(revision: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): Namespace | null;
    toDict(): {
        [key: string]: any;
    };
}
