import IModel from '../../core/interface/IModel';
import * as Gs2Version from '../../version/model';
export default class VersionModel implements IModel {
    private versionModelId;
    private name;
    private metadata;
    private scope;
    private type;
    private currentVersion;
    private warningVersion;
    private errorVersion;
    private scheduleVersions;
    private needSignature;
    private signatureKeyId;
    private approveRequirement;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static getVersionName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null, versionName: string | null): string | null;
    getVersionModelId(): string | null;
    setVersionModelId(versionModelId: string | null): this;
    withVersionModelId(versionModelId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getScope(): string | null;
    setScope(scope: string | null): this;
    withScope(scope: string | null): this;
    getType(): string | null;
    setType(type: string | null): this;
    withType(type: string | null): this;
    getCurrentVersion(): Gs2Version.Version | null;
    setCurrentVersion(currentVersion: Gs2Version.Version | null): this;
    withCurrentVersion(currentVersion: Gs2Version.Version | null): this;
    getWarningVersion(): Gs2Version.Version | null;
    setWarningVersion(warningVersion: Gs2Version.Version | null): this;
    withWarningVersion(warningVersion: Gs2Version.Version | null): this;
    getErrorVersion(): Gs2Version.Version | null;
    setErrorVersion(errorVersion: Gs2Version.Version | null): this;
    withErrorVersion(errorVersion: Gs2Version.Version | null): this;
    getScheduleVersions(): Gs2Version.ScheduleVersion[] | null;
    setScheduleVersions(scheduleVersions: Gs2Version.ScheduleVersion[] | null): this;
    withScheduleVersions(scheduleVersions: Gs2Version.ScheduleVersion[] | null): this;
    getNeedSignature(): boolean | null;
    setNeedSignature(needSignature: boolean | null): this;
    withNeedSignature(needSignature: boolean | null): this;
    getSignatureKeyId(): string | null;
    setSignatureKeyId(signatureKeyId: string | null): this;
    withSignatureKeyId(signatureKeyId: string | null): this;
    getApproveRequirement(): string | null;
    setApproveRequirement(approveRequirement: string | null): this;
    withApproveRequirement(approveRequirement: string | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): VersionModel | null;
    toDict(): {
        [key: string]: any;
    };
}
