/*
Copyright 2016 Game Server Services, Inc. or its affiliates. All Rights
Reserved.

Licensed under the Apache License, Version 2.0 (the "License").
You may not use this file except in compliance with the License.
A copy of the License is located at

 http://www.apache.org/licenses/LICENSE-2.0

or in the "license" file accompanying this file. This file is distributed
on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied. See the License for the specific language governing
permissions and limitations under the License.
 */

import {
  Namespace,
  CategoryModel,
  CategoryModelMaster,
  Subscribe,
  Score,
  Ranking,
  ResponseCache,
  CurrentRankingMaster,
  CalculatedAt,
  SubscribeUser,
  GitHubCheckoutSetting,
  LogSetting,
} from './model';
import {
  DescribeNamespacesRequest,
  CreateNamespaceRequest,
  GetNamespaceStatusRequest,
  GetNamespaceRequest,
  UpdateNamespaceRequest,
  DeleteNamespaceRequest,
  DescribeCategoryModelsRequest,
  GetCategoryModelRequest,
  DescribeCategoryModelMastersRequest,
  CreateCategoryModelMasterRequest,
  GetCategoryModelMasterRequest,
  UpdateCategoryModelMasterRequest,
  DeleteCategoryModelMasterRequest,
  DescribeSubscribesByCategoryNameRequest,
  DescribeSubscribesByCategoryNameAndUserIdRequest,
  SubscribeRequest,
  SubscribeByUserIdRequest,
  GetSubscribeRequest,
  GetSubscribeByUserIdRequest,
  UnsubscribeRequest,
  UnsubscribeByUserIdRequest,
  DescribeRankingsRequest,
  DescribeRankingssByUserIdRequest,
  DescribeNearRankingsRequest,
  PutScoreRequest,
  PutScoreByUserIdRequest,
  ExportMasterRequest,
  GetCurrentRankingMasterRequest,
  UpdateCurrentRankingMasterRequest,
  UpdateCurrentRankingMasterFromGitHubRequest,
} from './request';
import {
  DescribeNamespacesResult,
  CreateNamespaceResult,
  GetNamespaceStatusResult,
  GetNamespaceResult,
  UpdateNamespaceResult,
  DeleteNamespaceResult,
  DescribeCategoryModelsResult,
  GetCategoryModelResult,
  DescribeCategoryModelMastersResult,
  CreateCategoryModelMasterResult,
  GetCategoryModelMasterResult,
  UpdateCategoryModelMasterResult,
  DeleteCategoryModelMasterResult,
  DescribeSubscribesByCategoryNameResult,
  DescribeSubscribesByCategoryNameAndUserIdResult,
  SubscribeResult,
  SubscribeByUserIdResult,
  GetSubscribeResult,
  GetSubscribeByUserIdResult,
  UnsubscribeResult,
  UnsubscribeByUserIdResult,
  DescribeRankingsResult,
  DescribeRankingssByUserIdResult,
  DescribeNearRankingsResult,
  PutScoreResult,
  PutScoreByUserIdResult,
  ExportMasterResult,
  GetCurrentRankingMasterResult,
  UpdateCurrentRankingMasterResult,
  UpdateCurrentRankingMasterFromGitHubResult,
} from './result';
import { Gs2RankingRestClient } from './rest';

export default {
  Namespace,
  CategoryModel,
  CategoryModelMaster,
  Subscribe,
  Score,
  Ranking,
  ResponseCache,
  CurrentRankingMaster,
  CalculatedAt,
  SubscribeUser,
  GitHubCheckoutSetting,
  LogSetting,
  DescribeNamespacesRequest,
  DescribeNamespacesResult,
  CreateNamespaceRequest,
  CreateNamespaceResult,
  GetNamespaceStatusRequest,
  GetNamespaceStatusResult,
  GetNamespaceRequest,
  GetNamespaceResult,
  UpdateNamespaceRequest,
  UpdateNamespaceResult,
  DeleteNamespaceRequest,
  DeleteNamespaceResult,
  DescribeCategoryModelsRequest,
  DescribeCategoryModelsResult,
  GetCategoryModelRequest,
  GetCategoryModelResult,
  DescribeCategoryModelMastersRequest,
  DescribeCategoryModelMastersResult,
  CreateCategoryModelMasterRequest,
  CreateCategoryModelMasterResult,
  GetCategoryModelMasterRequest,
  GetCategoryModelMasterResult,
  UpdateCategoryModelMasterRequest,
  UpdateCategoryModelMasterResult,
  DeleteCategoryModelMasterRequest,
  DeleteCategoryModelMasterResult,
  DescribeSubscribesByCategoryNameRequest,
  DescribeSubscribesByCategoryNameResult,
  DescribeSubscribesByCategoryNameAndUserIdRequest,
  DescribeSubscribesByCategoryNameAndUserIdResult,
  SubscribeRequest,
  SubscribeResult,
  SubscribeByUserIdRequest,
  SubscribeByUserIdResult,
  GetSubscribeRequest,
  GetSubscribeResult,
  GetSubscribeByUserIdRequest,
  GetSubscribeByUserIdResult,
  UnsubscribeRequest,
  UnsubscribeResult,
  UnsubscribeByUserIdRequest,
  UnsubscribeByUserIdResult,
  DescribeRankingsRequest,
  DescribeRankingsResult,
  DescribeRankingssByUserIdRequest,
  DescribeRankingssByUserIdResult,
  DescribeNearRankingsRequest,
  DescribeNearRankingsResult,
  PutScoreRequest,
  PutScoreResult,
  PutScoreByUserIdRequest,
  PutScoreByUserIdResult,
  ExportMasterRequest,
  ExportMasterResult,
  GetCurrentRankingMasterRequest,
  GetCurrentRankingMasterResult,
  UpdateCurrentRankingMasterRequest,
  UpdateCurrentRankingMasterResult,
  UpdateCurrentRankingMasterFromGitHubRequest,
  UpdateCurrentRankingMasterFromGitHubResult,
  Gs2RankingRestClient,
};
