import IRequest from '../../core/interface/IRequest';
import * as Gs2Money from '../model';
export default class CreateNamespaceRequest implements IRequest {
    private requestId;
    private contextStack;
    private name;
    private description;
    private transactionSetting;
    private priority;
    private shareFree;
    private currency;
    private appleKey;
    private googleKey;
    private enableFakeReceipt;
    private createWalletScript;
    private depositScript;
    private withdrawScript;
    private logSetting;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getTransactionSetting(): Gs2Money.TransactionSetting | null;
    setTransactionSetting(transactionSetting: Gs2Money.TransactionSetting | null): this;
    withTransactionSetting(transactionSetting: Gs2Money.TransactionSetting | null): this;
    getPriority(): string | null;
    setPriority(priority: string | null): this;
    withPriority(priority: string | null): this;
    getShareFree(): boolean | null;
    setShareFree(shareFree: boolean | null): this;
    withShareFree(shareFree: boolean | null): this;
    getCurrency(): string | null;
    setCurrency(currency: string | null): this;
    withCurrency(currency: string | null): this;
    getAppleKey(): string | null;
    setAppleKey(appleKey: string | null): this;
    withAppleKey(appleKey: string | null): this;
    getGoogleKey(): string | null;
    setGoogleKey(googleKey: string | null): this;
    withGoogleKey(googleKey: string | null): this;
    getEnableFakeReceipt(): boolean | null;
    setEnableFakeReceipt(enableFakeReceipt: boolean | null): this;
    withEnableFakeReceipt(enableFakeReceipt: boolean | null): this;
    getCreateWalletScript(): Gs2Money.ScriptSetting | null;
    setCreateWalletScript(createWalletScript: Gs2Money.ScriptSetting | null): this;
    withCreateWalletScript(createWalletScript: Gs2Money.ScriptSetting | null): this;
    getDepositScript(): Gs2Money.ScriptSetting | null;
    setDepositScript(depositScript: Gs2Money.ScriptSetting | null): this;
    withDepositScript(depositScript: Gs2Money.ScriptSetting | null): this;
    getWithdrawScript(): Gs2Money.ScriptSetting | null;
    setWithdrawScript(withdrawScript: Gs2Money.ScriptSetting | null): this;
    withWithdrawScript(withdrawScript: Gs2Money.ScriptSetting | null): this;
    getLogSetting(): Gs2Money.LogSetting | null;
    setLogSetting(logSetting: Gs2Money.LogSetting | null): this;
    withLogSetting(logSetting: Gs2Money.LogSetting | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): CreateNamespaceRequest;
    toDict(): {
        [key: string]: any;
    };
}
