import IRequest from '../../core/interface/IRequest';
import * as Gs2Money from '../model';
export default class UpdateNamespaceRequest implements IRequest {
    private requestId;
    private contextStack;
    private namespaceName;
    private description;
    private priority;
    private appleKey;
    private googleKey;
    private enableFakeReceipt;
    private createWalletScript;
    private depositScript;
    private withdrawScript;
    private logSetting;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getPriority(): string | null;
    setPriority(priority: string | null): this;
    withPriority(priority: string | null): this;
    getAppleKey(): string | null;
    setAppleKey(appleKey: string | null): this;
    withAppleKey(appleKey: string | null): this;
    getGoogleKey(): string | null;
    setGoogleKey(googleKey: string | null): this;
    withGoogleKey(googleKey: string | null): this;
    getEnableFakeReceipt(): boolean | null;
    setEnableFakeReceipt(enableFakeReceipt: boolean | null): this;
    withEnableFakeReceipt(enableFakeReceipt: boolean | null): this;
    getCreateWalletScript(): Gs2Money.ScriptSetting | null;
    setCreateWalletScript(createWalletScript: Gs2Money.ScriptSetting | null): this;
    withCreateWalletScript(createWalletScript: Gs2Money.ScriptSetting | null): this;
    getDepositScript(): Gs2Money.ScriptSetting | null;
    setDepositScript(depositScript: Gs2Money.ScriptSetting | null): this;
    withDepositScript(depositScript: Gs2Money.ScriptSetting | null): this;
    getWithdrawScript(): Gs2Money.ScriptSetting | null;
    setWithdrawScript(withdrawScript: Gs2Money.ScriptSetting | null): this;
    withWithdrawScript(withdrawScript: Gs2Money.ScriptSetting | null): this;
    getLogSetting(): Gs2Money.LogSetting | null;
    setLogSetting(logSetting: Gs2Money.LogSetting | null): this;
    withLogSetting(logSetting: Gs2Money.LogSetting | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): UpdateNamespaceRequest;
    toDict(): {
        [key: string]: any;
    };
}
