import IRequest from '../../core/interface/IRequest';
import * as Gs2Idle from '../model';
export default class CreateCategoryModelMasterRequest implements IRequest {
    private requestId;
    private contextStack;
    private namespaceName;
    private name;
    private description;
    private metadata;
    private rewardIntervalMinutes;
    private defaultMaximumIdleMinutes;
    private acquireActions;
    private idlePeriodScheduleId;
    private receivePeriodScheduleId;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getRewardIntervalMinutes(): number | null;
    setRewardIntervalMinutes(rewardIntervalMinutes: number | null): this;
    withRewardIntervalMinutes(rewardIntervalMinutes: number | null): this;
    getDefaultMaximumIdleMinutes(): number | null;
    setDefaultMaximumIdleMinutes(defaultMaximumIdleMinutes: number | null): this;
    withDefaultMaximumIdleMinutes(defaultMaximumIdleMinutes: number | null): this;
    getAcquireActions(): Gs2Idle.AcquireActionList[] | null;
    setAcquireActions(acquireActions: Gs2Idle.AcquireActionList[] | null): this;
    withAcquireActions(acquireActions: Gs2Idle.AcquireActionList[] | null): this;
    getIdlePeriodScheduleId(): string | null;
    setIdlePeriodScheduleId(idlePeriodScheduleId: string | null): this;
    withIdlePeriodScheduleId(idlePeriodScheduleId: string | null): this;
    getReceivePeriodScheduleId(): string | null;
    setReceivePeriodScheduleId(receivePeriodScheduleId: string | null): this;
    withReceivePeriodScheduleId(receivePeriodScheduleId: string | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): CreateCategoryModelMasterRequest;
    toDict(): {
        [key: string]: any;
    };
}
