import IModel from '../../core/interface/IModel';
import * as Gs2Buff from '../../buff/model';
export default class BuffEntryModel implements IModel {
    private buffEntryModelId;
    private name;
    private metadata;
    private expression;
    private targetType;
    private targetModel;
    private targetAction;
    private priority;
    private applyPeriodScheduleEventId;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static getBuffEntryName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null, buffEntryName: string | null): string | null;
    getBuffEntryModelId(): string | null;
    setBuffEntryModelId(buffEntryModelId: string | null): this;
    withBuffEntryModelId(buffEntryModelId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getExpression(): string | null;
    setExpression(expression: string | null): this;
    withExpression(expression: string | null): this;
    getTargetType(): string | null;
    setTargetType(targetType: string | null): this;
    withTargetType(targetType: string | null): this;
    getTargetModel(): Gs2Buff.BuffTargetModel | null;
    setTargetModel(targetModel: Gs2Buff.BuffTargetModel | null): this;
    withTargetModel(targetModel: Gs2Buff.BuffTargetModel | null): this;
    getTargetAction(): Gs2Buff.BuffTargetAction | null;
    setTargetAction(targetAction: Gs2Buff.BuffTargetAction | null): this;
    withTargetAction(targetAction: Gs2Buff.BuffTargetAction | null): this;
    getPriority(): number | null;
    setPriority(priority: number | null): this;
    withPriority(priority: number | null): this;
    getApplyPeriodScheduleEventId(): string | null;
    setApplyPeriodScheduleEventId(applyPeriodScheduleEventId: string | null): this;
    withApplyPeriodScheduleEventId(applyPeriodScheduleEventId: string | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): BuffEntryModel | null;
    toDict(): {
        [key: string]: any;
    };
}
