import IModel from '../../core/interface/IModel';
import ScriptSetting from './ScriptSetting';
import LogSetting from './LogSetting';
export default class Namespace implements IModel {
    private namespaceId;
    private name;
    private description;
    private startQuestScript;
    private completeQuestScript;
    private failedQuestScript;
    private queueNamespaceId;
    private keyId;
    private logSetting;
    private createdAt;
    private updatedAt;
    getNamespaceId(): string | null;
    setNamespaceId(namespaceId: string | null): this;
    withNamespaceId(namespaceId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getStartQuestScript(): ScriptSetting | null;
    setStartQuestScript(startQuestScript: ScriptSetting | null): this;
    withStartQuestScript(startQuestScript: ScriptSetting | null): this;
    getCompleteQuestScript(): ScriptSetting | null;
    setCompleteQuestScript(completeQuestScript: ScriptSetting | null): this;
    withCompleteQuestScript(completeQuestScript: ScriptSetting | null): this;
    getFailedQuestScript(): ScriptSetting | null;
    setFailedQuestScript(failedQuestScript: ScriptSetting | null): this;
    withFailedQuestScript(failedQuestScript: ScriptSetting | null): this;
    getQueueNamespaceId(): string | null;
    setQueueNamespaceId(queueNamespaceId: string | null): this;
    withQueueNamespaceId(queueNamespaceId: string | null): this;
    getKeyId(): string | null;
    setKeyId(keyId: string | null): this;
    withKeyId(keyId: string | null): this;
    getLogSetting(): LogSetting | null;
    setLogSetting(logSetting: LogSetting | null): this;
    withLogSetting(logSetting: LogSetting | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): Namespace | null;
    toDict(): {
        [key: string]: any;
    };
}
