import IModel from '../../core/interface/IModel';
import * as Gs2Quest from '../../quest/model';
export default class QuestModel implements IModel {
    private questModelId;
    private name;
    private metadata;
    private contents;
    private challengePeriodEventId;
    private firstCompleteAcquireActions;
    private verifyActions;
    private consumeActions;
    private failedAcquireActions;
    private premiseQuestNames;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static getQuestGroupName(grn: string): string | null;
    static getQuestName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null, questGroupName: string | null, questName: string | null): string | null;
    getQuestModelId(): string | null;
    setQuestModelId(questModelId: string | null): this;
    withQuestModelId(questModelId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getContents(): Gs2Quest.Contents[] | null;
    setContents(contents: Gs2Quest.Contents[] | null): this;
    withContents(contents: Gs2Quest.Contents[] | null): this;
    getChallengePeriodEventId(): string | null;
    setChallengePeriodEventId(challengePeriodEventId: string | null): this;
    withChallengePeriodEventId(challengePeriodEventId: string | null): this;
    getFirstCompleteAcquireActions(): Gs2Quest.AcquireAction[] | null;
    setFirstCompleteAcquireActions(firstCompleteAcquireActions: Gs2Quest.AcquireAction[] | null): this;
    withFirstCompleteAcquireActions(firstCompleteAcquireActions: Gs2Quest.AcquireAction[] | null): this;
    getVerifyActions(): Gs2Quest.VerifyAction[] | null;
    setVerifyActions(verifyActions: Gs2Quest.VerifyAction[] | null): this;
    withVerifyActions(verifyActions: Gs2Quest.VerifyAction[] | null): this;
    getConsumeActions(): Gs2Quest.ConsumeAction[] | null;
    setConsumeActions(consumeActions: Gs2Quest.ConsumeAction[] | null): this;
    withConsumeActions(consumeActions: Gs2Quest.ConsumeAction[] | null): this;
    getFailedAcquireActions(): Gs2Quest.AcquireAction[] | null;
    setFailedAcquireActions(failedAcquireActions: Gs2Quest.AcquireAction[] | null): this;
    withFailedAcquireActions(failedAcquireActions: Gs2Quest.AcquireAction[] | null): this;
    getPremiseQuestNames(): string[] | null;
    setPremiseQuestNames(premiseQuestNames: string[] | null): this;
    withPremiseQuestNames(premiseQuestNames: string[] | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): QuestModel | null;
    toDict(): {
        [key: string]: any;
    };
}
