import IModel from '../../core/interface/IModel';
import ScriptSetting from './ScriptSetting';
import NotificationSetting from './NotificationSetting';
import LogSetting from './LogSetting';
export default class Namespace implements IModel {
    private namespaceId;
    private name;
    private description;
    private followScript;
    private unfollowScript;
    private sendRequestScript;
    private cancelRequestScript;
    private acceptRequestScript;
    private rejectRequestScript;
    private deleteFriendScript;
    private updateProfileScript;
    private followNotification;
    private receiveRequestNotification;
    private acceptRequestNotification;
    private logSetting;
    private createdAt;
    private updatedAt;
    private revision;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null): string | null;
    getNamespaceId(): string | null;
    setNamespaceId(namespaceId: string | null): this;
    withNamespaceId(namespaceId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getFollowScript(): ScriptSetting | null;
    setFollowScript(followScript: ScriptSetting | null): this;
    withFollowScript(followScript: ScriptSetting | null): this;
    getUnfollowScript(): ScriptSetting | null;
    setUnfollowScript(unfollowScript: ScriptSetting | null): this;
    withUnfollowScript(unfollowScript: ScriptSetting | null): this;
    getSendRequestScript(): ScriptSetting | null;
    setSendRequestScript(sendRequestScript: ScriptSetting | null): this;
    withSendRequestScript(sendRequestScript: ScriptSetting | null): this;
    getCancelRequestScript(): ScriptSetting | null;
    setCancelRequestScript(cancelRequestScript: ScriptSetting | null): this;
    withCancelRequestScript(cancelRequestScript: ScriptSetting | null): this;
    getAcceptRequestScript(): ScriptSetting | null;
    setAcceptRequestScript(acceptRequestScript: ScriptSetting | null): this;
    withAcceptRequestScript(acceptRequestScript: ScriptSetting | null): this;
    getRejectRequestScript(): ScriptSetting | null;
    setRejectRequestScript(rejectRequestScript: ScriptSetting | null): this;
    withRejectRequestScript(rejectRequestScript: ScriptSetting | null): this;
    getDeleteFriendScript(): ScriptSetting | null;
    setDeleteFriendScript(deleteFriendScript: ScriptSetting | null): this;
    withDeleteFriendScript(deleteFriendScript: ScriptSetting | null): this;
    getUpdateProfileScript(): ScriptSetting | null;
    setUpdateProfileScript(updateProfileScript: ScriptSetting | null): this;
    withUpdateProfileScript(updateProfileScript: ScriptSetting | null): this;
    getFollowNotification(): NotificationSetting | null;
    setFollowNotification(followNotification: NotificationSetting | null): this;
    withFollowNotification(followNotification: NotificationSetting | null): this;
    getReceiveRequestNotification(): NotificationSetting | null;
    setReceiveRequestNotification(receiveRequestNotification: NotificationSetting | null): this;
    withReceiveRequestNotification(receiveRequestNotification: NotificationSetting | null): this;
    getAcceptRequestNotification(): NotificationSetting | null;
    setAcceptRequestNotification(acceptRequestNotification: NotificationSetting | null): this;
    withAcceptRequestNotification(acceptRequestNotification: NotificationSetting | null): this;
    getLogSetting(): LogSetting | null;
    setLogSetting(logSetting: LogSetting | null): this;
    withLogSetting(logSetting: LogSetting | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    getRevision(): number | null;
    setRevision(revision: number | null): this;
    withRevision(revision: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): Namespace | null;
    toDict(): {
        [key: string]: any;
    };
}
