import IModel from '../../core/interface/IModel';
import * as Gs2Distributor from '../../distributor/model';
export default class StampSheetResult implements IModel {
    private stampSheetResultId;
    private userId;
    private transactionId;
    private verifyTaskRequests;
    private taskRequests;
    private sheetRequest;
    private verifyTaskResultCodes;
    private verifyTaskResults;
    private taskResultCodes;
    private taskResults;
    private sheetResultCode;
    private sheetResult;
    private nextTransactionId;
    private createdAt;
    private revision;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static getUserId(grn: string): string | null;
    static getTransactionId(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null, userId: string | null, transactionId: string | null): string | null;
    getStampSheetResultId(): string | null;
    setStampSheetResultId(stampSheetResultId: string | null): this;
    withStampSheetResultId(stampSheetResultId: string | null): this;
    getUserId(): string | null;
    setUserId(userId: string | null): this;
    withUserId(userId: string | null): this;
    getTransactionId(): string | null;
    setTransactionId(transactionId: string | null): this;
    withTransactionId(transactionId: string | null): this;
    getVerifyTaskRequests(): Gs2Distributor.VerifyAction[] | null;
    setVerifyTaskRequests(verifyTaskRequests: Gs2Distributor.VerifyAction[] | null): this;
    withVerifyTaskRequests(verifyTaskRequests: Gs2Distributor.VerifyAction[] | null): this;
    getTaskRequests(): Gs2Distributor.ConsumeAction[] | null;
    setTaskRequests(taskRequests: Gs2Distributor.ConsumeAction[] | null): this;
    withTaskRequests(taskRequests: Gs2Distributor.ConsumeAction[] | null): this;
    getSheetRequest(): Gs2Distributor.AcquireAction | null;
    setSheetRequest(sheetRequest: Gs2Distributor.AcquireAction | null): this;
    withSheetRequest(sheetRequest: Gs2Distributor.AcquireAction | null): this;
    getVerifyTaskResultCodes(): number[] | null;
    setVerifyTaskResultCodes(verifyTaskResultCodes: number[] | null): this;
    withVerifyTaskResultCodes(verifyTaskResultCodes: number[] | null): this;
    getVerifyTaskResults(): string[] | null;
    setVerifyTaskResults(verifyTaskResults: string[] | null): this;
    withVerifyTaskResults(verifyTaskResults: string[] | null): this;
    getTaskResultCodes(): number[] | null;
    setTaskResultCodes(taskResultCodes: number[] | null): this;
    withTaskResultCodes(taskResultCodes: number[] | null): this;
    getTaskResults(): string[] | null;
    setTaskResults(taskResults: string[] | null): this;
    withTaskResults(taskResults: string[] | null): this;
    getSheetResultCode(): number | null;
    setSheetResultCode(sheetResultCode: number | null): this;
    withSheetResultCode(sheetResultCode: number | null): this;
    getSheetResult(): string | null;
    setSheetResult(sheetResult: string | null): this;
    withSheetResult(sheetResult: string | null): this;
    getNextTransactionId(): string | null;
    setNextTransactionId(nextTransactionId: string | null): this;
    withNextTransactionId(nextTransactionId: string | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getRevision(): number | null;
    setRevision(revision: number | null): this;
    withRevision(revision: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): StampSheetResult | null;
    toDict(): {
        [key: string]: any;
    };
}
