import IModel from '../../core/interface/IModel';
import * as Gs2StateMachine from '../../stateMachine/model';
export default class Namespace implements IModel {
    private namespaceId;
    private name;
    private description;
    private supportSpeculativeExecution;
    private transactionSetting;
    private startScript;
    private passScript;
    private errorScript;
    private lowestStateMachineVersion;
    private logSetting;
    private createdAt;
    private updatedAt;
    private revision;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null): string | null;
    getNamespaceId(): string | null;
    setNamespaceId(namespaceId: string | null): this;
    withNamespaceId(namespaceId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getSupportSpeculativeExecution(): string | null;
    setSupportSpeculativeExecution(supportSpeculativeExecution: string | null): this;
    withSupportSpeculativeExecution(supportSpeculativeExecution: string | null): this;
    getTransactionSetting(): Gs2StateMachine.TransactionSetting | null;
    setTransactionSetting(transactionSetting: Gs2StateMachine.TransactionSetting | null): this;
    withTransactionSetting(transactionSetting: Gs2StateMachine.TransactionSetting | null): this;
    getStartScript(): Gs2StateMachine.ScriptSetting | null;
    setStartScript(startScript: Gs2StateMachine.ScriptSetting | null): this;
    withStartScript(startScript: Gs2StateMachine.ScriptSetting | null): this;
    getPassScript(): Gs2StateMachine.ScriptSetting | null;
    setPassScript(passScript: Gs2StateMachine.ScriptSetting | null): this;
    withPassScript(passScript: Gs2StateMachine.ScriptSetting | null): this;
    getErrorScript(): Gs2StateMachine.ScriptSetting | null;
    setErrorScript(errorScript: Gs2StateMachine.ScriptSetting | null): this;
    withErrorScript(errorScript: Gs2StateMachine.ScriptSetting | null): this;
    getLowestStateMachineVersion(): number | null;
    setLowestStateMachineVersion(lowestStateMachineVersion: number | null): this;
    withLowestStateMachineVersion(lowestStateMachineVersion: number | null): this;
    getLogSetting(): Gs2StateMachine.LogSetting | null;
    setLogSetting(logSetting: Gs2StateMachine.LogSetting | null): this;
    withLogSetting(logSetting: Gs2StateMachine.LogSetting | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    getRevision(): number | null;
    setRevision(revision: number | null): this;
    withRevision(revision: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): Namespace | null;
    toDict(): {
        [key: string]: any;
    };
}
