import IModel from '../../core/interface/IModel';
import StackEntry from './StackEntry';
import Variable from './Variable';
export default class Status implements IModel {
    private statusId;
    private userId;
    private name;
    private stateMachineVersion;
    private stacks;
    private variables;
    private status;
    private lastError;
    private transitionCount;
    private createdAt;
    private updatedAt;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static getUserId(grn: string): string | null;
    static getStatusName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null, userId: string | null, statusName: string | null): string | null;
    getStatusId(): string | null;
    setStatusId(statusId: string | null): this;
    withStatusId(statusId: string | null): this;
    getUserId(): string | null;
    setUserId(userId: string | null): this;
    withUserId(userId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getStateMachineVersion(): number | null;
    setStateMachineVersion(stateMachineVersion: number | null): this;
    withStateMachineVersion(stateMachineVersion: number | null): this;
    getStacks(): StackEntry[] | null;
    setStacks(stacks: StackEntry[] | null): this;
    withStacks(stacks: StackEntry[] | null): this;
    getVariables(): Variable[] | null;
    setVariables(variables: Variable[] | null): this;
    withVariables(variables: Variable[] | null): this;
    getStatus(): string | null;
    setStatus(status: string | null): this;
    withStatus(status: string | null): this;
    getLastError(): string | null;
    setLastError(lastError: string | null): this;
    withLastError(lastError: string | null): this;
    getTransitionCount(): number | null;
    setTransitionCount(transitionCount: number | null): this;
    withTransitionCount(transitionCount: number | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): Status | null;
    toDict(): {
        [key: string]: any;
    };
}
