import IRequest from '../../core/interface/IRequest';
import * as Gs2Exchange from '../model';
export default class CreateRateModelMasterRequest implements IRequest {
    private requestId;
    private contextStack;
    private namespaceName;
    private name;
    private description;
    private metadata;
    private timingType;
    private lockTime;
    private enableSkip;
    private skipConsumeActions;
    private acquireActions;
    private consumeActions;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getTimingType(): string | null;
    setTimingType(timingType: string | null): this;
    withTimingType(timingType: string | null): this;
    getLockTime(): number | null;
    setLockTime(lockTime: number | null): this;
    withLockTime(lockTime: number | null): this;
    getEnableSkip(): boolean | null;
    setEnableSkip(enableSkip: boolean | null): this;
    withEnableSkip(enableSkip: boolean | null): this;
    getSkipConsumeActions(): Gs2Exchange.ConsumeAction[] | null;
    setSkipConsumeActions(skipConsumeActions: Gs2Exchange.ConsumeAction[] | null): this;
    withSkipConsumeActions(skipConsumeActions: Gs2Exchange.ConsumeAction[] | null): this;
    getAcquireActions(): Gs2Exchange.AcquireAction[] | null;
    setAcquireActions(acquireActions: Gs2Exchange.AcquireAction[] | null): this;
    withAcquireActions(acquireActions: Gs2Exchange.AcquireAction[] | null): this;
    getConsumeActions(): Gs2Exchange.ConsumeAction[] | null;
    setConsumeActions(consumeActions: Gs2Exchange.ConsumeAction[] | null): this;
    withConsumeActions(consumeActions: Gs2Exchange.ConsumeAction[] | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): CreateRateModelMasterRequest;
    toDict(): {
        [key: string]: any;
    };
}
