import IRequest from '../../core/interface/IRequest';
import * as Gs2Exchange from '../model';
export default class CreateIncrementalRateModelMasterRequest implements IRequest {
    private requestId;
    private contextStack;
    private namespaceName;
    private name;
    private description;
    private metadata;
    private consumeAction;
    private calculateType;
    private baseValue;
    private coefficientValue;
    private calculateScriptId;
    private exchangeCountId;
    private acquireActions;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getConsumeAction(): Gs2Exchange.ConsumeAction | null;
    setConsumeAction(consumeAction: Gs2Exchange.ConsumeAction | null): this;
    withConsumeAction(consumeAction: Gs2Exchange.ConsumeAction | null): this;
    getCalculateType(): string | null;
    setCalculateType(calculateType: string | null): this;
    withCalculateType(calculateType: string | null): this;
    getBaseValue(): number | null;
    setBaseValue(baseValue: number | null): this;
    withBaseValue(baseValue: number | null): this;
    getCoefficientValue(): number | null;
    setCoefficientValue(coefficientValue: number | null): this;
    withCoefficientValue(coefficientValue: number | null): this;
    getCalculateScriptId(): string | null;
    setCalculateScriptId(calculateScriptId: string | null): this;
    withCalculateScriptId(calculateScriptId: string | null): this;
    getExchangeCountId(): string | null;
    setExchangeCountId(exchangeCountId: string | null): this;
    withExchangeCountId(exchangeCountId: string | null): this;
    getAcquireActions(): Gs2Exchange.AcquireAction[] | null;
    setAcquireActions(acquireActions: Gs2Exchange.AcquireAction[] | null): this;
    withAcquireActions(acquireActions: Gs2Exchange.AcquireAction[] | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): CreateIncrementalRateModelMasterRequest;
    toDict(): {
        [key: string]: any;
    };
}
