import IRequest from '../../core/interface/IRequest';
import * as Gs2Exchange from '../model';
export default class UpdateRateModelMasterRequest implements IRequest {
    private requestId;
    private contextStack;
    private namespaceName;
    private rateName;
    private description;
    private metadata;
    private timingType;
    private lockTime;
    private acquireActions;
    private verifyActions;
    private consumeActions;
    getRequestId(): string | null;
    setRequestId(requestId: string | null): this;
    withRequestId(requestId: string | null): this;
    getContextStack(): string | null;
    setContextStack(contextStack: string | null): this;
    withContextStack(contextStack: string | null): this;
    getNamespaceName(): string | null;
    setNamespaceName(namespaceName: string | null): this;
    withNamespaceName(namespaceName: string | null): this;
    getRateName(): string | null;
    setRateName(rateName: string | null): this;
    withRateName(rateName: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getTimingType(): string | null;
    setTimingType(timingType: string | null): this;
    withTimingType(timingType: string | null): this;
    getLockTime(): number | null;
    setLockTime(lockTime: number | null): this;
    withLockTime(lockTime: number | null): this;
    getAcquireActions(): Gs2Exchange.AcquireAction[] | null;
    setAcquireActions(acquireActions: Gs2Exchange.AcquireAction[] | null): this;
    withAcquireActions(acquireActions: Gs2Exchange.AcquireAction[] | null): this;
    getVerifyActions(): Gs2Exchange.VerifyAction[] | null;
    setVerifyActions(verifyActions: Gs2Exchange.VerifyAction[] | null): this;
    withVerifyActions(verifyActions: Gs2Exchange.VerifyAction[] | null): this;
    getConsumeActions(): Gs2Exchange.ConsumeAction[] | null;
    setConsumeActions(consumeActions: Gs2Exchange.ConsumeAction[] | null): this;
    withConsumeActions(consumeActions: Gs2Exchange.ConsumeAction[] | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): UpdateRateModelMasterRequest;
    toDict(): {
        [key: string]: any;
    };
}
