/*
Copyright 2016 Game Server Services, Inc. or its affiliates. All Rights
Reserved.

Licensed under the Apache License, Version 2.0 (the "License").
You may not use this file except in compliance with the License.
A copy of the License is located at

 http://www.apache.org/licenses/LICENSE-2.0

or in the "license" file accompanying this file. This file is distributed
on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied. See the License for the specific language governing
permissions and limitations under the License.
 */

import {
  Namespace,
  DataObject,
  DataObjectHistory,
  ResponseCache,
  LogSetting,
} from './model';
import {
  DescribeNamespacesRequest,
  CreateNamespaceRequest,
  GetNamespaceStatusRequest,
  GetNamespaceRequest,
  UpdateNamespaceRequest,
  DeleteNamespaceRequest,
  DescribeDataObjectsRequest,
  DescribeDataObjectsByUserIdRequest,
  PrepareUploadRequest,
  PrepareUploadByUserIdRequest,
  UpdateDataObjectRequest,
  UpdateDataObjectByUserIdRequest,
  PrepareReUploadRequest,
  PrepareReUploadByUserIdRequest,
  DoneUploadRequest,
  DoneUploadByUserIdRequest,
  DeleteDataObjectRequest,
  DeleteDataObjectByUserIdRequest,
  PrepareDownloadRequest,
  PrepareDownloadByUserIdRequest,
  PrepareDownloadByGenerationRequest,
  PrepareDownloadByGenerationAndUserIdRequest,
  PrepareDownloadOwnDataRequest,
  PrepareDownloadOwnDataByGenerationRequest,
  PrepareDownloadOwnDataByGenerationAndUserIdRequest,
  DescribeDataObjectHistoriesRequest,
  DescribeDataObjectHistoriesByUserIdRequest,
  GetDataObjectHistoryRequest,
  GetDataObjectHistoryByUserIdRequest,
} from './request';
import {
  DescribeNamespacesResult,
  CreateNamespaceResult,
  GetNamespaceStatusResult,
  GetNamespaceResult,
  UpdateNamespaceResult,
  DeleteNamespaceResult,
  DescribeDataObjectsResult,
  DescribeDataObjectsByUserIdResult,
  PrepareUploadResult,
  PrepareUploadByUserIdResult,
  UpdateDataObjectResult,
  UpdateDataObjectByUserIdResult,
  PrepareReUploadResult,
  PrepareReUploadByUserIdResult,
  DoneUploadResult,
  DoneUploadByUserIdResult,
  DeleteDataObjectResult,
  DeleteDataObjectByUserIdResult,
  PrepareDownloadResult,
  PrepareDownloadByUserIdResult,
  PrepareDownloadByGenerationResult,
  PrepareDownloadByGenerationAndUserIdResult,
  PrepareDownloadOwnDataResult,
  PrepareDownloadOwnDataByGenerationResult,
  PrepareDownloadOwnDataByGenerationAndUserIdResult,
  DescribeDataObjectHistoriesResult,
  DescribeDataObjectHistoriesByUserIdResult,
  GetDataObjectHistoryResult,
  GetDataObjectHistoryByUserIdResult,
} from './result';
import { Gs2DatastoreRestClient } from './rest';

export default {
  Namespace,
  DataObject,
  DataObjectHistory,
  ResponseCache,
  LogSetting,
  DescribeNamespacesRequest,
  DescribeNamespacesResult,
  CreateNamespaceRequest,
  CreateNamespaceResult,
  GetNamespaceStatusRequest,
  GetNamespaceStatusResult,
  GetNamespaceRequest,
  GetNamespaceResult,
  UpdateNamespaceRequest,
  UpdateNamespaceResult,
  DeleteNamespaceRequest,
  DeleteNamespaceResult,
  DescribeDataObjectsRequest,
  DescribeDataObjectsResult,
  DescribeDataObjectsByUserIdRequest,
  DescribeDataObjectsByUserIdResult,
  PrepareUploadRequest,
  PrepareUploadResult,
  PrepareUploadByUserIdRequest,
  PrepareUploadByUserIdResult,
  UpdateDataObjectRequest,
  UpdateDataObjectResult,
  UpdateDataObjectByUserIdRequest,
  UpdateDataObjectByUserIdResult,
  PrepareReUploadRequest,
  PrepareReUploadResult,
  PrepareReUploadByUserIdRequest,
  PrepareReUploadByUserIdResult,
  DoneUploadRequest,
  DoneUploadResult,
  DoneUploadByUserIdRequest,
  DoneUploadByUserIdResult,
  DeleteDataObjectRequest,
  DeleteDataObjectResult,
  DeleteDataObjectByUserIdRequest,
  DeleteDataObjectByUserIdResult,
  PrepareDownloadRequest,
  PrepareDownloadResult,
  PrepareDownloadByUserIdRequest,
  PrepareDownloadByUserIdResult,
  PrepareDownloadByGenerationRequest,
  PrepareDownloadByGenerationResult,
  PrepareDownloadByGenerationAndUserIdRequest,
  PrepareDownloadByGenerationAndUserIdResult,
  PrepareDownloadOwnDataRequest,
  PrepareDownloadOwnDataResult,
  PrepareDownloadOwnDataByGenerationRequest,
  PrepareDownloadOwnDataByGenerationResult,
  PrepareDownloadOwnDataByGenerationAndUserIdRequest,
  PrepareDownloadOwnDataByGenerationAndUserIdResult,
  DescribeDataObjectHistoriesRequest,
  DescribeDataObjectHistoriesResult,
  DescribeDataObjectHistoriesByUserIdRequest,
  DescribeDataObjectHistoriesByUserIdResult,
  GetDataObjectHistoryRequest,
  GetDataObjectHistoryResult,
  GetDataObjectHistoryByUserIdRequest,
  GetDataObjectHistoryByUserIdResult,
  Gs2DatastoreRestClient,
};
