import IModel from '../../core/interface/IModel';
export default class CategoryModel implements IModel {
    private categoryModelId;
    private name;
    private metadata;
    private minimumValue;
    private maximumValue;
    private orderDirection;
    private scope;
    private uniqueByUserId;
    private sum;
    private calculateFixedTimingHour;
    private calculateFixedTimingMinute;
    private calculateIntervalMinutes;
    private entryPeriodEventId;
    private accessPeriodEventId;
    private ignoreUserIds;
    private generation;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static getCategoryName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null, categoryName: string | null): string | null;
    getCategoryModelId(): string | null;
    setCategoryModelId(categoryModelId: string | null): this;
    withCategoryModelId(categoryModelId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getMetadata(): string | null;
    setMetadata(metadata: string | null): this;
    withMetadata(metadata: string | null): this;
    getMinimumValue(): number | null;
    setMinimumValue(minimumValue: number | null): this;
    withMinimumValue(minimumValue: number | null): this;
    getMaximumValue(): number | null;
    setMaximumValue(maximumValue: number | null): this;
    withMaximumValue(maximumValue: number | null): this;
    getOrderDirection(): string | null;
    setOrderDirection(orderDirection: string | null): this;
    withOrderDirection(orderDirection: string | null): this;
    getScope(): string | null;
    setScope(scope: string | null): this;
    withScope(scope: string | null): this;
    getUniqueByUserId(): boolean | null;
    setUniqueByUserId(uniqueByUserId: boolean | null): this;
    withUniqueByUserId(uniqueByUserId: boolean | null): this;
    getSum(): boolean | null;
    setSum(sum: boolean | null): this;
    withSum(sum: boolean | null): this;
    getCalculateFixedTimingHour(): number | null;
    setCalculateFixedTimingHour(calculateFixedTimingHour: number | null): this;
    withCalculateFixedTimingHour(calculateFixedTimingHour: number | null): this;
    getCalculateFixedTimingMinute(): number | null;
    setCalculateFixedTimingMinute(calculateFixedTimingMinute: number | null): this;
    withCalculateFixedTimingMinute(calculateFixedTimingMinute: number | null): this;
    getCalculateIntervalMinutes(): number | null;
    setCalculateIntervalMinutes(calculateIntervalMinutes: number | null): this;
    withCalculateIntervalMinutes(calculateIntervalMinutes: number | null): this;
    getEntryPeriodEventId(): string | null;
    setEntryPeriodEventId(entryPeriodEventId: string | null): this;
    withEntryPeriodEventId(entryPeriodEventId: string | null): this;
    getAccessPeriodEventId(): string | null;
    setAccessPeriodEventId(accessPeriodEventId: string | null): this;
    withAccessPeriodEventId(accessPeriodEventId: string | null): this;
    getIgnoreUserIds(): string[] | null;
    setIgnoreUserIds(ignoreUserIds: string[] | null): this;
    withIgnoreUserIds(ignoreUserIds: string[] | null): this;
    getGeneration(): string | null;
    setGeneration(generation: string | null): this;
    withGeneration(generation: string | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): CategoryModel | null;
    toDict(): {
        [key: string]: any;
    };
}
