import IModel from '../../core/interface/IModel';
import BanStatus from './BanStatus';
export default class Account implements IModel {
    private accountId;
    private userId;
    private password;
    private timeOffset;
    private banStatuses;
    private banned;
    private lastAuthenticatedAt;
    private createdAt;
    private revision;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static getUserId(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null, userId: string | null): string | null;
    getAccountId(): string | null;
    setAccountId(accountId: string | null): this;
    withAccountId(accountId: string | null): this;
    getUserId(): string | null;
    setUserId(userId: string | null): this;
    withUserId(userId: string | null): this;
    getPassword(): string | null;
    setPassword(password: string | null): this;
    withPassword(password: string | null): this;
    getTimeOffset(): number | null;
    setTimeOffset(timeOffset: number | null): this;
    withTimeOffset(timeOffset: number | null): this;
    getBanStatuses(): BanStatus[] | null;
    setBanStatuses(banStatuses: BanStatus[] | null): this;
    withBanStatuses(banStatuses: BanStatus[] | null): this;
    getBanned(): boolean | null;
    setBanned(banned: boolean | null): this;
    withBanned(banned: boolean | null): this;
    getLastAuthenticatedAt(): number | null;
    setLastAuthenticatedAt(lastAuthenticatedAt: number | null): this;
    withLastAuthenticatedAt(lastAuthenticatedAt: number | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getRevision(): number | null;
    setRevision(revision: number | null): this;
    withRevision(revision: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): Account | null;
    toDict(): {
        [key: string]: any;
    };
}
