import IModel from '../../core/interface/IModel';
import ScriptSetting from './ScriptSetting';
import LogSetting from './LogSetting';
export default class Namespace implements IModel {
    private namespaceId;
    private name;
    private description;
    private changePasswordIfTakeOver;
    private differentUserIdForLoginAndDataRetention;
    private createAccountScript;
    private authenticationScript;
    private createTakeOverScript;
    private doTakeOverScript;
    private logSetting;
    private createdAt;
    private updatedAt;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null): string | null;
    getNamespaceId(): string | null;
    setNamespaceId(namespaceId: string | null): this;
    withNamespaceId(namespaceId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getChangePasswordIfTakeOver(): boolean | null;
    setChangePasswordIfTakeOver(changePasswordIfTakeOver: boolean | null): this;
    withChangePasswordIfTakeOver(changePasswordIfTakeOver: boolean | null): this;
    getDifferentUserIdForLoginAndDataRetention(): boolean | null;
    setDifferentUserIdForLoginAndDataRetention(differentUserIdForLoginAndDataRetention: boolean | null): this;
    withDifferentUserIdForLoginAndDataRetention(differentUserIdForLoginAndDataRetention: boolean | null): this;
    getCreateAccountScript(): ScriptSetting | null;
    setCreateAccountScript(createAccountScript: ScriptSetting | null): this;
    withCreateAccountScript(createAccountScript: ScriptSetting | null): this;
    getAuthenticationScript(): ScriptSetting | null;
    setAuthenticationScript(authenticationScript: ScriptSetting | null): this;
    withAuthenticationScript(authenticationScript: ScriptSetting | null): this;
    getCreateTakeOverScript(): ScriptSetting | null;
    setCreateTakeOverScript(createTakeOverScript: ScriptSetting | null): this;
    withCreateTakeOverScript(createTakeOverScript: ScriptSetting | null): this;
    getDoTakeOverScript(): ScriptSetting | null;
    setDoTakeOverScript(doTakeOverScript: ScriptSetting | null): this;
    withDoTakeOverScript(doTakeOverScript: ScriptSetting | null): this;
    getLogSetting(): LogSetting | null;
    setLogSetting(logSetting: LogSetting | null): this;
    withLogSetting(logSetting: LogSetting | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): Namespace | null;
    toDict(): {
        [key: string]: any;
    };
}
