import IModel from '../../core/interface/IModel';
import * as Gs2Account from '../../account/model';
export default class Namespace implements IModel {
    private namespaceId;
    private name;
    private description;
    private transactionSetting;
    private changePasswordIfTakeOver;
    private differentUserIdForLoginAndDataRetention;
    private createAccountScript;
    private authenticationScript;
    private createTakeOverScript;
    private doTakeOverScript;
    private banScript;
    private unBanScript;
    private logSetting;
    private createdAt;
    private updatedAt;
    private revision;
    static getRegion(grn: string): string | null;
    static getOwnerId(grn: string): string | null;
    static getNamespaceName(grn: string): string | null;
    static isValid(grn: string): boolean;
    static createGrn(region: string | null, ownerId: string | null, namespaceName: string | null): string | null;
    getNamespaceId(): string | null;
    setNamespaceId(namespaceId: string | null): this;
    withNamespaceId(namespaceId: string | null): this;
    getName(): string | null;
    setName(name: string | null): this;
    withName(name: string | null): this;
    getDescription(): string | null;
    setDescription(description: string | null): this;
    withDescription(description: string | null): this;
    getTransactionSetting(): Gs2Account.TransactionSetting | null;
    setTransactionSetting(transactionSetting: Gs2Account.TransactionSetting | null): this;
    withTransactionSetting(transactionSetting: Gs2Account.TransactionSetting | null): this;
    getChangePasswordIfTakeOver(): boolean | null;
    setChangePasswordIfTakeOver(changePasswordIfTakeOver: boolean | null): this;
    withChangePasswordIfTakeOver(changePasswordIfTakeOver: boolean | null): this;
    getDifferentUserIdForLoginAndDataRetention(): boolean | null;
    setDifferentUserIdForLoginAndDataRetention(differentUserIdForLoginAndDataRetention: boolean | null): this;
    withDifferentUserIdForLoginAndDataRetention(differentUserIdForLoginAndDataRetention: boolean | null): this;
    getCreateAccountScript(): Gs2Account.ScriptSetting | null;
    setCreateAccountScript(createAccountScript: Gs2Account.ScriptSetting | null): this;
    withCreateAccountScript(createAccountScript: Gs2Account.ScriptSetting | null): this;
    getAuthenticationScript(): Gs2Account.ScriptSetting | null;
    setAuthenticationScript(authenticationScript: Gs2Account.ScriptSetting | null): this;
    withAuthenticationScript(authenticationScript: Gs2Account.ScriptSetting | null): this;
    getCreateTakeOverScript(): Gs2Account.ScriptSetting | null;
    setCreateTakeOverScript(createTakeOverScript: Gs2Account.ScriptSetting | null): this;
    withCreateTakeOverScript(createTakeOverScript: Gs2Account.ScriptSetting | null): this;
    getDoTakeOverScript(): Gs2Account.ScriptSetting | null;
    setDoTakeOverScript(doTakeOverScript: Gs2Account.ScriptSetting | null): this;
    withDoTakeOverScript(doTakeOverScript: Gs2Account.ScriptSetting | null): this;
    getBanScript(): Gs2Account.ScriptSetting | null;
    setBanScript(banScript: Gs2Account.ScriptSetting | null): this;
    withBanScript(banScript: Gs2Account.ScriptSetting | null): this;
    getUnBanScript(): Gs2Account.ScriptSetting | null;
    setUnBanScript(unBanScript: Gs2Account.ScriptSetting | null): this;
    withUnBanScript(unBanScript: Gs2Account.ScriptSetting | null): this;
    getLogSetting(): Gs2Account.LogSetting | null;
    setLogSetting(logSetting: Gs2Account.LogSetting | null): this;
    withLogSetting(logSetting: Gs2Account.LogSetting | null): this;
    getCreatedAt(): number | null;
    setCreatedAt(createdAt: number | null): this;
    withCreatedAt(createdAt: number | null): this;
    getUpdatedAt(): number | null;
    setUpdatedAt(updatedAt: number | null): this;
    withUpdatedAt(updatedAt: number | null): this;
    getRevision(): number | null;
    setRevision(revision: number | null): this;
    withRevision(revision: number | null): this;
    static fromDict(data: {
        [key: string]: any;
    }): Namespace | null;
    toDict(): {
        [key: string]: any;
    };
}
