/*
Copyright 2016 Game Server Services, Inc. or its affiliates. All Rights
Reserved.

Licensed under the Apache License, Version 2.0 (the "License").
You may not use this file except in compliance with the License.
A copy of the License is located at

 http://www.apache.org/licenses/LICENSE-2.0

or in the "license" file accompanying this file. This file is distributed
on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied. See the License for the specific language governing
permissions and limitations under the License.
 */

import {
  Namespace,
  SalesItemMaster,
  SalesItemGroupMaster,
  ShowcaseMaster,
  CurrentShowcaseMaster,
  ResponseCache,
  GitHubCheckoutSetting,
  LogSetting,
  SalesItem,
  SalesItemGroup,
  Showcase,
  DisplayItem,
  Config,
  ConsumeAction,
  AcquireAction,
  DisplayItemMaster,
} from './model';
import {
  DescribeNamespacesRequest,
  CreateNamespaceRequest,
  GetNamespaceStatusRequest,
  GetNamespaceRequest,
  UpdateNamespaceRequest,
  DeleteNamespaceRequest,
  DescribeSalesItemMastersRequest,
  CreateSalesItemMasterRequest,
  GetSalesItemMasterRequest,
  UpdateSalesItemMasterRequest,
  DeleteSalesItemMasterRequest,
  DescribeSalesItemGroupMastersRequest,
  CreateSalesItemGroupMasterRequest,
  GetSalesItemGroupMasterRequest,
  UpdateSalesItemGroupMasterRequest,
  DeleteSalesItemGroupMasterRequest,
  DescribeShowcaseMastersRequest,
  CreateShowcaseMasterRequest,
  GetShowcaseMasterRequest,
  UpdateShowcaseMasterRequest,
  DeleteShowcaseMasterRequest,
  ExportMasterRequest,
  GetCurrentShowcaseMasterRequest,
  UpdateCurrentShowcaseMasterRequest,
  UpdateCurrentShowcaseMasterFromGitHubRequest,
  DescribeShowcasesRequest,
  DescribeShowcasesByUserIdRequest,
  GetShowcaseRequest,
  GetShowcaseByUserIdRequest,
  BuyRequest,
  BuyByUserIdRequest,
} from './request';
import {
  DescribeNamespacesResult,
  CreateNamespaceResult,
  GetNamespaceStatusResult,
  GetNamespaceResult,
  UpdateNamespaceResult,
  DeleteNamespaceResult,
  DescribeSalesItemMastersResult,
  CreateSalesItemMasterResult,
  GetSalesItemMasterResult,
  UpdateSalesItemMasterResult,
  DeleteSalesItemMasterResult,
  DescribeSalesItemGroupMastersResult,
  CreateSalesItemGroupMasterResult,
  GetSalesItemGroupMasterResult,
  UpdateSalesItemGroupMasterResult,
  DeleteSalesItemGroupMasterResult,
  DescribeShowcaseMastersResult,
  CreateShowcaseMasterResult,
  GetShowcaseMasterResult,
  UpdateShowcaseMasterResult,
  DeleteShowcaseMasterResult,
  ExportMasterResult,
  GetCurrentShowcaseMasterResult,
  UpdateCurrentShowcaseMasterResult,
  UpdateCurrentShowcaseMasterFromGitHubResult,
  DescribeShowcasesResult,
  DescribeShowcasesByUserIdResult,
  GetShowcaseResult,
  GetShowcaseByUserIdResult,
  BuyResult,
  BuyByUserIdResult,
} from './result';
import { Gs2ShowcaseRestClient } from './rest';

export default {
  Namespace,
  SalesItemMaster,
  SalesItemGroupMaster,
  ShowcaseMaster,
  CurrentShowcaseMaster,
  ResponseCache,
  GitHubCheckoutSetting,
  LogSetting,
  SalesItem,
  SalesItemGroup,
  Showcase,
  DisplayItem,
  Config,
  ConsumeAction,
  AcquireAction,
  DisplayItemMaster,
  DescribeNamespacesRequest,
  DescribeNamespacesResult,
  CreateNamespaceRequest,
  CreateNamespaceResult,
  GetNamespaceStatusRequest,
  GetNamespaceStatusResult,
  GetNamespaceRequest,
  GetNamespaceResult,
  UpdateNamespaceRequest,
  UpdateNamespaceResult,
  DeleteNamespaceRequest,
  DeleteNamespaceResult,
  DescribeSalesItemMastersRequest,
  DescribeSalesItemMastersResult,
  CreateSalesItemMasterRequest,
  CreateSalesItemMasterResult,
  GetSalesItemMasterRequest,
  GetSalesItemMasterResult,
  UpdateSalesItemMasterRequest,
  UpdateSalesItemMasterResult,
  DeleteSalesItemMasterRequest,
  DeleteSalesItemMasterResult,
  DescribeSalesItemGroupMastersRequest,
  DescribeSalesItemGroupMastersResult,
  CreateSalesItemGroupMasterRequest,
  CreateSalesItemGroupMasterResult,
  GetSalesItemGroupMasterRequest,
  GetSalesItemGroupMasterResult,
  UpdateSalesItemGroupMasterRequest,
  UpdateSalesItemGroupMasterResult,
  DeleteSalesItemGroupMasterRequest,
  DeleteSalesItemGroupMasterResult,
  DescribeShowcaseMastersRequest,
  DescribeShowcaseMastersResult,
  CreateShowcaseMasterRequest,
  CreateShowcaseMasterResult,
  GetShowcaseMasterRequest,
  GetShowcaseMasterResult,
  UpdateShowcaseMasterRequest,
  UpdateShowcaseMasterResult,
  DeleteShowcaseMasterRequest,
  DeleteShowcaseMasterResult,
  ExportMasterRequest,
  ExportMasterResult,
  GetCurrentShowcaseMasterRequest,
  GetCurrentShowcaseMasterResult,
  UpdateCurrentShowcaseMasterRequest,
  UpdateCurrentShowcaseMasterResult,
  UpdateCurrentShowcaseMasterFromGitHubRequest,
  UpdateCurrentShowcaseMasterFromGitHubResult,
  DescribeShowcasesRequest,
  DescribeShowcasesResult,
  DescribeShowcasesByUserIdRequest,
  DescribeShowcasesByUserIdResult,
  GetShowcaseRequest,
  GetShowcaseResult,
  GetShowcaseByUserIdRequest,
  GetShowcaseByUserIdResult,
  BuyRequest,
  BuyResult,
  BuyByUserIdRequest,
  BuyByUserIdResult,
  Gs2ShowcaseRestClient,
};
